export interface TriviaQuestion {
  id: number;
  question: string;
  options: string[];
  answer: number; // 0-indexed
  fact: string;   // shown after answering
}

export const ALL_QUESTIONS: TriviaQuestion[] = [
  // WINNERS & HISTORY
  {
    id: 1,
    question: 'How many times has Brazil won the FIFA World Cup?',
    options: ['3', '4', '5', '6'],
    answer: 2,
    fact: 'Brazil won in 1958, 1962, 1970, 1994, and 2002 — the most of any nation.',
  },
  {
    id: 2,
    question: 'Which country hosted the very first FIFA World Cup in 1930?',
    options: ['Argentina', 'Brazil', 'Italy', 'Uruguay'],
    answer: 3,
    fact: 'Uruguay also won that first tournament, beating Argentina 4–2 in the final.',
  },
  {
    id: 3,
    question: 'Which country won back-to-back World Cups in 1934 and 1938?',
    options: ['Brazil', 'Argentina', 'Germany', 'Italy'],
    answer: 3,
    fact: 'Italy under Vittorio Pozzo remains the only manager to win the World Cup twice.',
  },
  {
    id: 4,
    question: 'In which year did England win their only World Cup title?',
    options: ['1962', '1966', '1970', '1974'],
    answer: 1,
    fact: 'England beat West Germany 4–2 at Wembley. Geoff Hurst scored a hat-trick.',
  },
  {
    id: 5,
    question: 'How many World Cup titles has Italy won?',
    options: ['2', '3', '4', '5'],
    answer: 2,
    fact: 'Italy won in 1934, 1938, 1982, and 2006 — their last title.',
  },
  {
    id: 6,
    question: 'Which country has qualified for every single FIFA World Cup since the first in 1930?',
    options: ['Germany', 'Italy', 'Argentina', 'Brazil'],
    answer: 3,
    fact: 'Brazil is the only nation to have participated in all editions of the World Cup.',
  },
  {
    id: 7,
    question: 'What year did France win their first FIFA World Cup?',
    options: ['1994', '1998', '2002', '2006'],
    answer: 1,
    fact: 'France beat Brazil 3–0 in the Paris final, with Zidane scoring two headers.',
  },
  {
    id: 8,
    question: 'Which country won the inaugural FIFA World Cup in 1930?',
    options: ['Argentina', 'Brazil', 'USA', 'Uruguay'],
    answer: 3,
    fact: 'Hosts Uruguay beat Argentina 4–2 in the final in Montevideo.',
  },

  // TOP SCORERS & RECORDS
  {
    id: 9,
    question: 'Who is the all-time top scorer in World Cup history with 16 goals?',
    options: ['Pelé', 'Ronaldo (Brazil)', 'Miroslav Klose', 'Gerd Müller'],
    answer: 2,
    fact: 'Klose scored 16 goals across four World Cups (2002–2014) for Germany.',
  },
  {
    id: 10,
    question: 'What single-tournament scoring record did Just Fontaine set at the 1958 World Cup?',
    options: ['10 goals', '11 goals', '12 goals', '13 goals'],
    answer: 3,
    fact: 'Playing for France, Fontaine scored 13 goals in just 6 matches — a record that still stands.',
  },
  {
    id: 11,
    question: 'Who scored the fastest goal in World Cup history — in just 11 seconds?',
    options: ['Clint Dempsey', 'Hakan Şükür', 'Bryan Ruiz', 'Oleg Salenko'],
    answer: 1,
    fact: 'Şükür scored for Turkey against South Korea in the 2002 third-place match.',
  },
  {
    id: 12,
    question: 'Who scored the most goals in a single World Cup match, netting 5 against Cameroon in 1994?',
    options: ['Gerd Müller', 'Just Fontaine', 'Oleg Salenko', 'Miroslav Klose'],
    answer: 2,
    fact: 'Salenko scored 5 for Russia vs Cameroon in 1994 — still a record for one match.',
  },
  {
    id: 13,
    question: 'Who won the Golden Boot at the 2018 World Cup in Russia?',
    options: ['Antoine Griezmann', 'Cristiano Ronaldo', 'Romelu Lukaku', 'Harry Kane'],
    answer: 3,
    fact: 'Kane scored 6 goals for England including two hat-tricks — the most of any player at Russia 2018.',
  },
  {
    id: 14,
    question: 'Which World Cup produced the highest average goals per match (5.38 goals/game)?',
    options: ['1930 Uruguay', '1954 Switzerland', '1970 Mexico', '1982 Spain'],
    answer: 1,
    fact: '1954 had legendary high scorers: Hungary beat West Germany 8–3 in the group stage.',
  },
  {
    id: 15,
    question: 'Who was the oldest player to score a goal in World Cup history, doing so at age 42?',
    options: ['Essam El-Hadary', 'Roger Milla', 'Lothar Matthäus', 'Peter Shilton'],
    answer: 1,
    fact: 'Milla came out of retirement to play for Cameroon at both 1990 and 1994 World Cups.',
  },
  {
    id: 16,
    question: 'Which player has appeared in the most World Cup matches ever (25)?',
    options: ['Miroslav Klose', 'Cafu', 'Paolo Maldini', 'Lothar Matthäus'],
    answer: 3,
    fact: 'Matthäus played in 5 World Cups for West Germany/Germany between 1982 and 1998.',
  },
  {
    id: 17,
    question: 'Who is the youngest player ever to score a goal in the World Cup?',
    options: ['Michael Owen', 'Pelé', 'Cesc Fàbregas', 'Wayne Rooney'],
    answer: 1,
    fact: 'Pelé scored in the 1958 World Cup at just 17 years and 239 days old.',
  },
  {
    id: 18,
    question: 'How many goals did Ronaldo (Brazil) score at the 2002 World Cup, including 2 in the final?',
    options: ['6', '7', '8', '9'],
    answer: 2,
    fact: "Ronaldo's 8 goals made him Golden Boot winner. He scored both in the 2–0 final win over Germany.",
  },

  // MEMORABLE MOMENTS
  {
    id: 19,
    question: "Who scored the infamous 'Hand of God' goal against England at the 1986 World Cup?",
    options: ['Pelé', 'Diego Maradona', 'Ronaldo', 'Ronaldinho'],
    answer: 1,
    fact: "In the same match, Maradona also scored the 'Goal of the Century,' voted the greatest WC goal ever.",
  },
  {
    id: 20,
    question: 'Which country beat Germany 7–1 in the 2014 World Cup semi-final (the "Mineirazo")?',
    options: ['Argentina', 'France', 'Netherlands', 'Brazil'],
    answer: 3,
    fact: 'The match in Belo Horizonte is considered one of the biggest shocks in football history.',
  },
  {
    id: 21,
    question: 'Who scored the winning goal for Germany in the 2014 World Cup Final, in extra time?',
    options: ['Thomas Müller', 'Mesut Özil', 'Bastian Schweinsteiger', 'Mario Götze'],
    answer: 3,
    fact: 'Götze, a substitute, scored in the 113th minute to beat Argentina 1–0.',
  },
  {
    id: 22,
    question: 'Who was sent off for headbutting Marco Materazzi in the 2006 World Cup Final?',
    options: ['Patrick Vieira', 'Thierry Henry', 'Zinedine Zidane', 'Franck Ribéry'],
    answer: 2,
    fact: 'In his final professional match, Zidane was red-carded — yet still won the Golden Ball that tournament.',
  },
  {
    id: 23,
    question: 'Which African team reached the World Cup semi-finals for the first time ever at Qatar 2022?',
    options: ['Senegal', 'Ghana', 'Nigeria', 'Morocco'],
    answer: 3,
    fact: 'Morocco beat Spain and Portugal on the way before losing to France in the semi-finals.',
  },
  {
    id: 24,
    question: 'Which player scored a hat-trick in the 2022 World Cup Final, yet still ended on the losing side?',
    options: ['Antoine Griezmann', 'Ousmane Dembélé', 'Olivier Giroud', 'Kylian Mbappé'],
    answer: 3,
    fact: "Mbappé's hat-trick made France the first team since 1966 to score 3 WC final goals and lose.",
  },
  {
    id: 25,
    question: 'Which World Cup was the first to use VAR (Video Assistant Referee)?',
    options: ['2014 Brazil', '2018 Russia', '2022 Qatar', '2010 South Africa'],
    answer: 1,
    fact: 'VAR debuted at Russia 2018 and led to a record number of penalties being awarded.',
  },
  {
    id: 26,
    question: 'Which team had the record biggest win in World Cup history, beating El Salvador 10–1?',
    options: ['Hungary', 'Yugoslavia', 'Germany', 'Brazil'],
    answer: 0,
    fact: 'Hungary beat El Salvador 10–1 at the 1982 World Cup in Spain.',
  },

  // HOST COUNTRIES
  {
    id: 27,
    question: 'In which country was the 2010 World Cup held?',
    options: ['South Africa', 'Brazil', 'Germany', 'Japan'],
    answer: 0,
    fact: 'South Africa 2010 was the first World Cup hosted on the African continent.',
  },
  {
    id: 28,
    question: 'The 2026 FIFA World Cup will be co-hosted by which three countries?',
    options: ['USA, Mexico & Brazil', 'USA, Canada & Mexico', 'Mexico, Canada & Colombia', 'USA, Canada & Argentina'],
    answer: 1,
    fact: 'With 16 host cities across three nations, 2026 is the first ever tri-host World Cup.',
  },
  {
    id: 29,
    question: 'Which World Cup was the first to be held in Asia?',
    options: ['1998 France', '2002 Japan & South Korea', '2006 Germany', '2010 South Africa'],
    answer: 1,
    fact: 'Japan and South Korea co-hosted in 2002 — also the first ever co-hosted World Cup.',
  },
  {
    id: 30,
    question: 'How many teams will compete in the 2026 FIFA World Cup, up from 32?',
    options: ['36', '40', '48', '64'],
    answer: 2,
    fact: 'The 48-team format adds a new Round of 32 and gives more nations a chance to qualify.',
  },

  // TROPHIES
  {
    id: 31,
    question: 'What was the original World Cup trophy called, awarded from 1930 to 1970?',
    options: ['Henri Delaunay Trophy', 'Jules Rimet Trophy', 'FIFA World Cup', 'Coupe du Monde'],
    answer: 1,
    fact: 'Brazil won it permanently in 1970 after their third title. The original was later stolen and never recovered.',
  },
  {
    id: 32,
    question: 'In what year was the current FIFA World Cup trophy first awarded?',
    options: ['1966', '1970', '1974', '1982'],
    answer: 2,
    fact: 'Made of 18-carat gold with a malachite base, the current trophy was designed by Italian artist Silvio Gazzaniga.',
  },

  // MASCOTS
  {
    id: 33,
    question: 'What was the name of the first-ever FIFA World Cup mascot, introduced at England 1966?',
    options: ['Striker', 'World Cup Willie', 'Footix', 'Goleo'],
    answer: 1,
    fact: 'World Cup Willie was a lion wearing a Union Jack shirt — the pioneer of all WC mascots.',
  },
  {
    id: 34,
    question: 'What was the mascot of the 1998 World Cup in France?',
    options: ['Ciao', 'Footix', 'Pique', 'Naranjito'],
    answer: 1,
    fact: "Footix was a blue rooster — France's national symbol (the Gallic rooster) wearing a football kit.",
  },
  {
    id: 35,
    question: 'What animal was Fuleco, the mascot of the 2014 World Cup in Brazil?',
    options: ['Toucan', 'Jaguar', 'Three-banded armadillo', 'Tree frog'],
    answer: 2,
    fact: 'Fuleco represented an endangered species native to Brazil, raising awareness for conservation.',
  },
  {
    id: 36,
    question: 'What was the mascot of the 2010 World Cup in South Africa?',
    options: ['Fuleco', 'Zakumi', 'Footix', 'Goleo'],
    answer: 1,
    fact: '"Za" stands for South Africa and "kumi" means "ten" in several African languages.',
  },
  {
    id: 37,
    question: 'What was the mascot of the 2018 World Cup in Russia?',
    options: ['Zabivaka', 'Goleo VI', 'Striker', 'Ciao'],
    answer: 0,
    fact: '"Zabivaka" means "one who scores goals" in Russian — a friendly wolf in football kit.',
  },
  {
    id: 38,
    question: "What was the mascot of the 2022 World Cup in Qatar?",
    options: ['Goleo VI', 'Zabivaka', "La'eeb", 'Tazuni'],
    answer: 2,
    fact: "La'eeb means 'super-skilled player' in Arabic and was depicted as a ghost-like flowing figure.",
  },
  {
    id: 39,
    question: 'What was the mascot for the 1994 World Cup in the USA?',
    options: ['Striker', 'Ciao', 'Pique', 'Naranjito'],
    answer: 0,
    fact: 'Striker was a dog in a USA soccer shirt — one of the first WC mascots designed by a Hollywood studio.',
  },
  {
    id: 40,
    question: 'Naranjito, the mascot of the 1982 World Cup in Spain, was dressed as what fruit?',
    options: ['Lemon', 'Orange', 'Watermelon', 'Tomato'],
    answer: 1,
    fact: '"Naranja" means orange in Spanish. Naranjito wore a Spain jersey and was hugely popular.',
  },

  // WC FINALS
  {
    id: 41,
    question: 'Which stadium is the only one in history to have hosted two separate World Cup Finals?',
    options: ['Maracanã', 'Estadio Azteca', 'Luzhniki', 'Wembley'],
    answer: 1,
    fact: 'The Azteca in Mexico City hosted the 1970 final (Brazil 4–1 Italy) and the 1986 final (Argentina 3–2 West Germany).',
  },
  {
    id: 42,
    question: "Who scored the winning goal in Spain's 2010 World Cup Final victory over the Netherlands?",
    options: ['David Villa', 'Fernando Torres', 'Andrés Iniesta', 'Xavi'],
    answer: 2,
    fact: "Iniesta struck in the 116th minute of extra time. It remains Spain's only World Cup title.",
  },
  {
    id: 43,
    question: "The 1994 World Cup Final ended 0–0 and went to penalties. Who missed Italy's decisive spot kick?",
    options: ['Franco Baresi', 'Daniele Massaro', 'Roberto Baggio', 'Demetrio Albertini'],
    answer: 2,
    fact: "Baggio's miss over the bar handed Brazil the title 3–2 on penalties — one of football's most iconic images.",
  },
  {
    id: 44,
    question: 'Which country has appeared in the most World Cup Finals (8 times)?',
    options: ['Brazil', 'Italy', 'Germany', 'Argentina'],
    answer: 2,
    fact: 'Germany/West Germany have reached 8 finals (1954, 1966, 1974, 1982, 1986, 1990, 2002, 2014), winning 4.',
  },

  // FAMOUS UPSETS
  {
    id: 45,
    question: 'Which country shocked reigning champion France 1–0 in the opening match of the 2002 World Cup?',
    options: ['South Korea', 'Senegal', 'Japan', 'Turkey'],
    answer: 1,
    fact: "Senegal, in just their second World Cup, stunned France who had won in 1998 and Euro 2000.",
  },
  {
    id: 46,
    question: 'Which defending World Cup champion was eliminated in the group stage at Russia 2018?',
    options: ['Spain', 'Germany', 'Italy', 'Brazil'],
    answer: 1,
    fact: 'Germany — winners in 2014 — finished bottom of their group after losses to Mexico and South Korea.',
  },
  {
    id: 47,
    question: "The USA beat England 1–0 at the 1950 World Cup in one of football's greatest upsets. Who scored?",
    options: ['Joe Gaetjens', 'Walter Bahr', 'Frank Wallace', 'Eddie McIlvenny'],
    answer: 0,
    fact: "Joe Gaetjens' header in the 37th minute produced one of the biggest upsets in World Cup history.",
  },
  {
    id: 48,
    question: "Which African nation opened Italia '90 by beating defending champions Argentina?",
    options: ['Nigeria', 'Ghana', 'Senegal', 'Cameroon'],
    answer: 3,
    fact: "Roger Milla's Cameroon beat Argentina 1–0 in the opening match — a result that stunned the football world.",
  },
  {
    id: 49,
    question: 'Saudi Arabia came from behind to pull off a stunning 2022 WC group stage upset. Who did they beat 2–1?',
    options: ['Brazil', 'France', 'Argentina', 'England'],
    answer: 2,
    fact: "Saudi Arabia ended Argentina's 36-game unbeaten run — widely called one of the greatest WC upsets ever.",
  },

  // TEAM NICKNAMES
  {
    id: 50,
    question: "Brazil's national team is nicknamed 'A Seleção.' What does this mean?",
    options: ['The Warriors', 'The Selection', 'The Yellow', 'The Champions'],
    answer: 1,
    fact: '"A Seleção" simply means "The Selection" — used so universally in Brazil that no further description is needed.',
  },
  {
    id: 51,
    question: "What is Germany's national football team nicknamed?",
    options: ['Die Roten', 'Die Adler', 'Die Mannschaft', 'Das Team'],
    answer: 2,
    fact: '"Die Mannschaft" means "The Team" in German — embraced globally after their dominant 2014 triumph.',
  },
  {
    id: 52,
    question: "What is Argentina's national team nicknamed, referring to the colours of their shirt?",
    options: ['Los Pumas', 'La Albiceleste', 'Los Gauchos', 'El Tri'],
    answer: 1,
    fact: '"La Albiceleste" means "the white and sky blue" — the iconic stripes worn since 1908.',
  },
  {
    id: 53,
    question: "Mexico's national team is nicknamed 'El Tri.' What does it refer to?",
    options: ['Three legends', 'The Tricolour (flag)', 'Triple champions', 'Trinity of attack'],
    answer: 1,
    fact: '"El Tri" is short for "El Tricolor" — a reference to the green, white, and red of the Mexican flag.',
  },

  // COACHES & MANAGERS
  {
    id: 54,
    question: 'Vittorio Pozzo is the only manager to win the World Cup twice (1934 & 1938). Which country?',
    options: ['Argentina', 'Brazil', 'Italy', 'Uruguay'],
    answer: 2,
    fact: 'Pozzo led Italy to back-to-back titles — a feat no other manager has ever matched in World Cup history.',
  },
  {
    id: 55,
    question: 'Which Dutch manager guided South Korea to the 2002 World Cup semi-finals on home soil?',
    options: ['Louis van Gaal', 'Guus Hiddink', 'Dick Advocaat', 'Johan Cruyff'],
    answer: 1,
    fact: "Hiddink's Korea beat Spain and Italy to reach the semis — one of the great coaching stories in WC history.",
  },
  {
    id: 56,
    question: 'Didier Deschamps (2018) was the third person to win the WC as both player and coach. Who was the first?',
    options: ['Franz Beckenbauer', 'Johan Cruyff', 'Pelé', 'Michel Platini'],
    answer: 0,
    fact: 'Beckenbauer won as player in 1974 and coach in 1990 (both Germany). Zagallo did it for Brazil; Deschamps for France.',
  },

  // ICONIC STADIUMS
  {
    id: 57,
    question: "What is the name given to Uruguay's shock 1950 World Cup win over Brazil in their own Maracanã stadium?",
    options: ['The Miracle of Bern', 'O Maracanazo', 'The Tragedy of Rio', 'The Final Shock'],
    answer: 1,
    fact: '"O Maracanazo" — Uruguay beat Brazil 2–1 before ~200,000 fans in Rio. It remains Brazil\'s most painful footballing memory.',
  },
  {
    id: 58,
    question: 'Which stadium will host the 2026 World Cup Final?',
    options: ['AT&T Stadium, Dallas', 'Rose Bowl, Los Angeles', 'MetLife Stadium, New Jersey', 'SoFi Stadium, Los Angeles'],
    answer: 2,
    fact: 'MetLife Stadium in East Rutherford, NJ — serving the New York metro area — will stage the 2026 WC Final.',
  },

  // WC SONGS
  {
    id: 59,
    question: "Who performed 'Waka Waka (This Time for Africa)', the official song of the 2010 World Cup?",
    options: ['Beyoncé', 'Shakira', 'Jennifer Lopez', 'Rihanna'],
    answer: 1,
    fact: "Shakira's Waka Waka became one of the best-selling WC songs ever, surpassing 1 billion YouTube views.",
  },
  {
    id: 60,
    question: "Which operatic piece became the BBC's iconic theme for the 1990 World Cup in Italy?",
    options: ['World in Motion', 'Three Lions', 'Nessun Dorma', 'La Copa de la Vida'],
    answer: 2,
    fact: "Pavarotti's Nessun Dorma — used as the BBC broadcast theme — became one of Italia '90's defining symbols.",
  },
  {
    id: 61,
    question: "Ricky Martin's 'La Copa de la Vida' was the official song of which World Cup?",
    options: ['1994 USA', '1998 France', '2002 Korea/Japan', '2006 Germany'],
    answer: 1,
    fact: '"La Copa de la Vida" (The Cup of Life) — performed live at the final ceremony in Paris — became a global stadium anthem.',
  },

  // HAT-TRICKS
  {
    id: 62,
    question: 'Who is the only player ever to score a hat-trick in a World Cup Final?',
    options: ['Pelé', 'Geoff Hurst', 'Ronaldo (Brazil)', 'Zinedine Zidane'],
    answer: 1,
    fact: "Hurst scored 3 of England's 4 goals in the 1966 Final against West Germany — the only hat-trick in any WC Final.",
  },
  {
    id: 63,
    question: 'Cristiano Ronaldo scored a hat-trick at the 2018 World Cup. Against which opponent?',
    options: ['Morocco', 'Iran', 'Spain', 'Uruguay'],
    answer: 2,
    fact: "Ronaldo's hat-trick — including a stunning late free-kick — sealed a thrilling 3–3 draw against Spain in the group stage.",
  },

  // PENALTIES & SHOOTOUTS
  {
    id: 64,
    question: 'Which World Cup Final was the first ever decided by a penalty shootout?',
    options: ['1982 Spain', '1986 Mexico', '1990 Italy', '1994 USA'],
    answer: 3,
    fact: "The 1994 Brazil vs Italy final was the first WC final decided by shootout — Brazil won 3–2 after Baggio's miss.",
  },
  {
    id: 65,
    question: 'Which country has won all 5 of their World Cup penalty shootouts, earning the "penalty kings" tag?',
    options: ['Germany', 'Brazil', 'Argentina', 'Spain'],
    answer: 0,
    fact: "Germany's perfect WC shootout record (5 from 5) is unmatched by any other major nation.",
  },

  // AFRICAN & ASIAN MILESTONES
  {
    id: 66,
    question: "Cameroon became the first African team to reach the World Cup quarter-finals. In which year?",
    options: ['1982', '1986', '1990', '1994'],
    answer: 2,
    fact: "The 'Indomitable Lions' at Italia '90 beat Argentina in the opener and reached the QF — inspiring a continent.",
  },
  {
    id: 67,
    question: 'Which Asian team reached the World Cup semi-finals for the first time ever in 2002?',
    options: ['Japan', 'South Korea', 'Saudi Arabia', 'China'],
    answer: 1,
    fact: 'Co-hosts South Korea beat both Spain and Italy to reach the semis — still the best-ever result by an Asian side.',
  },

  // INNOVATION & FORMAT
  {
    id: 68,
    question: 'Which World Cup was the first broadcast worldwide in colour television?',
    options: ['1966 England', '1970 Mexico', '1974 West Germany', '1978 Argentina'],
    answer: 1,
    fact: 'Mexico 1970 was the first WC in glorious colour TV — transforming how billions of fans experienced football.',
  },
  {
    id: 69,
    question: 'Brazil 2014 introduced goal-line technology. Which other innovation also debuted at that same tournament?',
    options: ['VAR', 'Vanishing spray for free kicks', 'Wearable GPS trackers', 'Video replays on screens'],
    answer: 1,
    fact: 'Vanishing foam spray for free-kick walls was used for the first time at Brazil 2014, adopted worldwide shortly after.',
  },
  {
    id: 70,
    question: "How many groups will the 2026 World Cup have with its 48-team format?",
    options: ['8', '10', '12', '16'],
    answer: 2,
    fact: '48 teams in 12 groups of 4 — the top 2 plus 8 best third-place teams advance to the new Round of 32.',
  },

  // MORE RECORDS & MOMENTS
  {
    id: 71,
    question: "Maradona's 'Goal of the Century' in 1986 — where he dribbled past 5 players — was scored against?",
    options: ['Belgium', 'West Germany', 'England', 'France'],
    answer: 2,
    fact: "Voted the greatest WC goal ever, Maradona's run vs England came in the same match as the infamous 'Hand of God.'",
  },
  {
    id: 72,
    question: 'Diego Maradona was sent home from the 1994 World Cup mid-tournament. What for?',
    options: ['Violent conduct', 'Failed a drug test', 'Passport forgery', 'Refusing to play'],
    answer: 1,
    fact: 'Maradona tested positive for ephedrine after Argentina beat Greece — ending his World Cup career in disgrace.',
  },
  {
    id: 73,
    question: 'The 1950 World Cup had no knockout final. How was the champion decided?',
    options: ['Golden goal', 'Final round-robin group', 'Penalty shootout', 'Coin toss'],
    answer: 1,
    fact: "A 4-team 'Final Pool' round-robin — Uruguay beat Brazil in the decisive last match to claim the title.",
  },
  {
    id: 74,
    question: 'Which World Cup was the first held outside of Europe or the Americas?',
    options: ['1994 USA', '2002 Japan & South Korea', '2010 South Africa', '2022 Qatar'],
    answer: 1,
    fact: 'Japan and South Korea 2002 was the first WC in Asia and the first co-hosted edition of the tournament.',
  },
  {
    id: 75,
    question: 'Which nation hosted AND won the 1978 World Cup?',
    options: ['Chile', 'Brazil', 'Argentina', 'Peru'],
    answer: 2,
    fact: 'Argentina beat the Netherlands 3–1 in AET in Buenos Aires — their first-ever World Cup title on home soil.',
  },
  {
    id: 76,
    question: 'Who won the Golden Ball (best player) at the 2022 World Cup in Qatar?',
    options: ['Kylian Mbappé', 'Luka Modrić', 'Lionel Messi', 'Antoine Griezmann'],
    answer: 2,
    fact: "Messi's 7 goals and 3 assists earned the Golden Ball — completing his journey to football's ultimate honour.",
  },
  {
    id: 77,
    question: "The 'Battle of Santiago' in 1962 is remembered as the most violent WC match in history. Which teams played?",
    options: ['Brazil vs Argentina', 'Italy vs Chile', 'Germany vs Netherlands', 'England vs France'],
    answer: 1,
    fact: "Chile beat Italy 2–0 but the match had 2 red cards, mass brawling, and police on the pitch. BBC's Coleman called it 'the most disgraceful match in WC history.'",
  },
  {
    id: 78,
    question: 'Which country scored in every single one of their 7 matches at Russia 2018?',
    options: ['France', 'England', 'Belgium', 'Croatia'],
    answer: 2,
    fact: 'Belgium scored in all 7 matches at Russia 2018 on their way to a record 3rd-place finish.',
  },

  // MORE CHAMPIONS & HISTORY
  {
    id: 79,
    question: 'Argentina has won the World Cup three times. In which years?',
    options: ['1966, 1982, 2014', '1978, 1986, 2022', '1970, 1990, 2014', '1978, 1998, 2022'],
    answer: 1,
    fact: 'Argentina won in 1978 (home soil), 1986 (Maradona era), and 2022 (Messi era) — spanning 44 years.',
  },
  {
    id: 80,
    question: 'Which country won the 2022 FIFA World Cup in Qatar?',
    options: ['France', 'Croatia', 'Morocco', 'Argentina'],
    answer: 3,
    fact: "Argentina beat France on penalties after a dramatic 3–3 draw — Messi finally completing football's ultimate achievement.",
  },
  {
    id: 81,
    question: 'How many different countries have ever won the FIFA World Cup?',
    options: ['6', '7', '8', '9'],
    answer: 2,
    fact: 'Brazil (5), Germany (4), Italy (4), Argentina (3), France (2), Uruguay (2), England (1), Spain (1) — 8 nations in total.',
  },
  {
    id: 82,
    question: 'Uruguay has won the World Cup twice. In which years?',
    options: ['1930 and 1938', '1930 and 1950', '1950 and 1966', '1934 and 1950'],
    answer: 1,
    fact: 'Uruguay won the very first WC in 1930 on home soil and then the 1950 edition — famously beating Brazil in the Maracanã.',
  },
  {
    id: 83,
    question: 'How many times did Pelé win the World Cup?',
    options: ['1', '2', '3', '4'],
    answer: 2,
    fact: 'Pelé won in 1958 (aged 17), 1962 and 1970 — the only player ever to be part of three World Cup-winning squads.',
  },
  {
    id: 84,
    question: 'Which of these sets of host nations ALL won the World Cup on home soil?',
    options: ['Uruguay, Italy, England, Argentina, France', 'Brazil, England, Germany, Argentina, France', 'Italy, England, Brazil, Argentina, Spain', 'Uruguay, Italy, Argentina, Germany, France'],
    answer: 0,
    fact: 'Uruguay (1930), Italy (1934), England (1966), Argentina (1978) and France (1998) all won hosting the WC. Germany 2006 finished third.',
  },
  {
    id: 85,
    question: "Who scored France's third goal in the 1998 World Cup Final to seal a 3–0 win over Brazil?",
    options: ['Thierry Henry', 'David Trezeguet', 'Zinedine Zidane', 'Emmanuel Petit'],
    answer: 3,
    fact: "Petit scored a breakaway goal in the 90th minute. Zidane had scored two headers earlier — his most iconic night.",
  },
  {
    id: 86,
    question: 'France are two-time World Cup champions. In which two years?',
    options: ['1994 and 2010', '1998 and 2014', '1998 and 2018', '2002 and 2018'],
    answer: 2,
    fact: 'France won as hosts in 1998 (beating Brazil 3–0) and in Russia 2018 (beating Croatia 4–2).',
  },
  {
    id: 87,
    question: 'Germany has won 4 World Cups. Which year was NOT one of them?',
    options: ['1954', '1966', '1990', '2014'],
    answer: 1,
    fact: 'Germany won in 1954, 1974, 1990 and 2014. They lost finals in 1966, 1982, 1986, and 2002.',
  },

  // MORE TOP SCORERS
  {
    id: 88,
    question: 'Who won the Golden Boot as top scorer at the 2014 World Cup in Brazil?',
    options: ['Neymar', 'Thomas Müller', 'James Rodríguez', 'Lionel Messi'],
    answer: 2,
    fact: "Colombia's James Rodríguez scored 6 goals in 5 matches at just 22 — including a stunning volley vs Uruguay.",
  },
  {
    id: 89,
    question: 'Who was the top scorer at the 1998 World Cup in France with 6 goals?',
    options: ['Ronaldo (Brazil)', 'Davor Šuker', 'Gabriel Batistuta', 'Marcelo Salas'],
    answer: 1,
    fact: "Croatia's Davor Šuker scored 6 goals including a sublime chip vs Denmark — helping Croatia finish 3rd on debut.",
  },
  {
    id: 90,
    question: 'Who scored 8 goals at the very first World Cup in 1930, winning the top scorer award?',
    options: ['José Andrade', 'Guillermo Stábile', 'Pedro Cea', 'Héctor Castro'],
    answer: 1,
    fact: "Argentina's Stábile scored 8 goals in just 4 matches — despite not playing in the opening game.",
  },
  {
    id: 91,
    question: 'Sándor Kocsis scored 11 goals at the 1954 WC for which country?',
    options: ['Czechoslovakia', 'Poland', 'Hungary', 'Romania'],
    answer: 2,
    fact: "Hungary's 'Golden Head' Kocsis scored 11 goals in 5 matches — yet Hungary still lost the final 3–2 to West Germany.",
  },
  {
    id: 92,
    question: "Gabriel Batistuta scored World Cup hat-tricks at two different tournaments. Which years?",
    options: ['1990 and 1994', '1994 and 1998', '1998 and 2002', '1986 and 1990'],
    answer: 1,
    fact: "Batistuta scored vs Greece in 1994 and vs Jamaica in 1998 — one of only two players to score WC hat-tricks at two different editions.",
  },
  {
    id: 93,
    question: "Who is Brazil's all-time top scorer at the World Cup with 15 goals?",
    options: ['Pelé', 'Zico', 'Ronaldo (Fenômeno)', 'Neymar'],
    answer: 2,
    fact: "Ronaldo (Brazil) scored 15 WC goals across four tournaments (1994–2006) — more than Pelé's 12 or Neymar's 8.",
  },
  {
    id: 94,
    question: "How many World Cup goals did Pelé score across his three winning campaigns?",
    options: ['8', '10', '12', '14'],
    answer: 2,
    fact: "Pelé scored 12 WC goals across 1958, 1962 and 1970 — including a then-record 6 goals in his debut WC at age 17.",
  },
  {
    id: 95,
    question: "Before Messi surpassed him in 2022, who was Argentina's all-time WC top scorer?",
    options: ['Diego Maradona', 'Gabriel Batistuta', 'Mario Kempes', 'Hernán Crespo'],
    answer: 1,
    fact: "Batistuta's 10 career WC goals stood as Argentina's record until Messi overtook him in Qatar 2022, finishing with 13.",
  },

  // MORE MEMORABLE MOMENTS
  {
    id: 96,
    question: "The 'Miracle of Bern' was West Germany's shock 1954 WC Final win. Who did they beat from 2–0 down?",
    options: ['Brazil', 'Uruguay', 'Hungary', 'Czechoslovakia'],
    answer: 2,
    fact: "Hungary had been unbeaten for 4 years across 33 matches. West Germany came back to win 3–2 in one of the greatest upsets.",
  },
  {
    id: 97,
    question: "Which 1970 WC semi-final became known as 'The Game of the Century'?",
    options: ['Brazil vs England', 'Italy vs West Germany', 'Brazil vs Uruguay', 'England vs West Germany'],
    answer: 1,
    fact: "Italy beat West Germany 4–3 in an extraordinary extra-time match — 4 goals came in the final 19 minutes.",
  },
  {
    id: 98,
    question: "Roger Milla's iconic goal celebrations at the 1990 World Cup involved dancing around what?",
    options: ['The goalpost', 'The corner flag', 'The referee', 'The trophy'],
    answer: 1,
    fact: "Milla's corner-flag dance at Italia '90 became one of football's most beloved celebrations. He repeated it 4 years later at age 42.",
  },
  {
    id: 99,
    question: "Laurent Blanc scored the first-ever golden goal in WC history in 1998. Against which country?",
    options: ['Mexico', 'Colombia', 'Paraguay', 'Ecuador'],
    answer: 2,
    fact: "Blanc's extra-time header eliminated Paraguay in the Round of 16 — the first WC match ever decided by the golden goal rule.",
  },
  {
    id: 100,
    question: "Paolo Rossi scored a hat-trick at the 1982 WC to eliminate which heavily-favoured team?",
    options: ['West Germany', 'Argentina', 'Brazil', 'France'],
    answer: 2,
    fact: "Rossi's 3 goals vs Brazil (3–2) ended the run of Zico and Falcão — many people's favourites — and led Italy to the title.",
  },
  {
    id: 101,
    question: "Who scored the winning penalty for West Germany in the 1990 World Cup Final vs Argentina?",
    options: ['Lothar Matthäus', 'Andreas Brehme', 'Rudi Völler', 'Thomas Häßler'],
    answer: 1,
    fact: "Brehme converted in the 85th minute to make it 1–0 — the first WC final decided by a penalty awarded in normal play.",
  },
  {
    id: 102,
    question: "Gordon Banks made what many consider the greatest save in football history at the 1970 WC. Whose shot did he stop?",
    options: ['Garrincha', 'Eusébio', 'Jairzinho', 'Pelé'],
    answer: 3,
    fact: "Banks scooped Pelé's downward header off the line with his right hand. Pelé said: 'It was the greatest save I have ever seen.'",
  },
  {
    id: 103,
    question: "Archie Gemmill scored a famous solo goal at the 1978 WC against the Netherlands — for which country?",
    options: ['England', 'Republic of Ireland', 'Scotland', 'Wales'],
    answer: 2,
    fact: "Gemmill's weaving dribble is Scotland's most celebrated WC moment — yet they were still eliminated in the group stage.",
  },
  {
    id: 104,
    question: "Ronaldo (Brazil) played the 1998 WC Final despite a mystery illness the night before. What was the result?",
    options: ['Brazil won 1–0', 'Brazil drew 0–0 and won on penalties', 'France won 3–0', 'France won 2–1 in AET'],
    answer: 2,
    fact: "France won 3–0 with Zidane's two headers. Ronaldo started despite his condition — the circumstances were never fully explained.",
  },
  {
    id: 105,
    question: "The 'Disgrace of Gijón' in 1982 saw West Germany and Austria play a result that eliminated Algeria. What rule change followed?",
    options: ['Yellow cards became stricter', 'Final group games must be played simultaneously', 'Goal difference replaced goals scored', 'Away goals introduced'],
    answer: 1,
    fact: "From 1986, all final group games are played simultaneously so teams cannot collude. The 1–0 to West Germany both teams needed is still controversial.",
  },
  {
    id: 106,
    question: "Carlos Alberto Torres scored a legendary 4th goal for Brazil in the 1970 WC Final after a sweeping team move. Who was the final passer?",
    options: ['Jairzinho', 'Tostão', 'Rivelino', 'Pelé'],
    answer: 3,
    fact: "Pelé's perfectly weighted pass sent Carlos Alberto surging through — his thunderous finish sealed the 4–1 win over Italy.",
  },

  // GOALKEEPERS
  {
    id: 107,
    question: "Which Italian goalkeeper went a WC record 517 minutes without conceding at the 1990 World Cup?",
    options: ['Giovanni Galli', 'Walter Zenga', 'Dino Zoff', 'Gianluigi Buffon'],
    answer: 1,
    fact: "Zenga's run ended when Argentina's Caniggia headed in during the semi-final — a heartbreaking end to a remarkable streak.",
  },
  {
    id: 108,
    question: "Who won the 2002 World Cup Golden Glove despite Germany losing the final — the only goalkeeper to win the Golden Ball?",
    options: ['Brad Friedel', 'Gianluigi Buffon', 'Oliver Kahn', 'Rüştü Reçber'],
    answer: 2,
    fact: "Kahn was outstanding throughout but made a crucial error in the final. He is still the only goalkeeper ever to win the Golden Ball award.",
  },
  {
    id: 109,
    question: "Which goalkeeper was England's hero in 1966, keeping 3 clean sheets in the knockout rounds?",
    options: ['Peter Bonetti', 'Gordon Banks', 'Ron Springett', 'Alex Stepney'],
    answer: 1,
    fact: "Banks conceded just 3 goals in the entire tournament and was widely considered the world's best keeper at the time.",
  },
  {
    id: 110,
    question: "Which goalkeeper used a cheat sheet of penalty takers to save two spot kicks vs Argentina at the 2006 WC quarter-final?",
    options: ['Oliver Kahn', 'Jens Lehmann', 'Robert Enke', 'Andreas Köpke'],
    answer: 1,
    fact: "Lehmann saved from Ayala and Cambiasso using notes from his goalkeeper coach — sending Germany through to the semi-finals.",
  },

  // OFFICIAL MATCH BALLS
  {
    id: 111,
    question: "Which company has supplied every official FIFA World Cup match ball since 1970?",
    options: ['Nike', 'Puma', 'Adidas', 'Umbro'],
    answer: 2,
    fact: "Adidas has been the official WC ball supplier since 1970's Telstar — the iconic black-and-white design that became synonymous with football.",
  },
  {
    id: 112,
    question: "What was the official 2010 South Africa WC ball, criticised by goalkeepers for its unpredictable flight?",
    options: ['Tango', 'Jabulani', 'Brazuca', 'Al Rihla'],
    answer: 1,
    fact: "The Jabulani's knuckling flight path baffled goalkeepers — including England's Robert Green who dropped it vs USA.",
  },
  {
    id: 113,
    question: "What does 'Al Rihla' — the official ball of the 2022 Qatar World Cup — mean in Arabic?",
    options: ['The Dream', 'The Journey', 'The Star', 'The Future'],
    answer: 1,
    fact: "'Al Rihla' (the journey) was the fastest-moving WC ball ever tested — designed by Adidas using sustainable materials.",
  },
  {
    id: 114,
    question: "What was the official match ball for the 2014 Brazil World Cup?",
    options: ['Jabulani', 'Tango', 'Brazuca', 'Telstar'],
    answer: 2,
    fact: "'Brazuca' (Brazilian slang for 'Brazilian way of life') was praised by players for its consistency and performance.",
  },

  // MORE NICKNAMES & COLORS
  {
    id: 115,
    question: "Italy's national team is nicknamed 'Gli Azzurri.' What does Azzurri mean?",
    options: ['The Greens', 'The Blues', 'The Reds', 'The Whites'],
    answer: 1,
    fact: "Azzurri means 'The Blues' — Italy has worn blue since 1911, inspired by the House of Savoy's royal colour.",
  },
  {
    id: 116,
    question: "What is Spain's national team most commonly nicknamed?",
    options: ['La Albiceleste', 'La Roja', 'Los Blancos', 'Los Matadores'],
    answer: 1,
    fact: "'La Roja' (The Red) or 'La Furia Roja' (The Red Fury) — Spain's traditional red kit has become iconic since their dominant 2008–2012 era.",
  },
  {
    id: 117,
    question: "What is France's national football team nicknamed?",
    options: ['Les Bleus', 'Les Tricolores', 'Les Coqs', 'Les Gallois'],
    answer: 0,
    fact: "'Les Bleus' (The Blues) — France's home kit is traditionally blue, from the French tricolour flag.",
  },
  {
    id: 118,
    question: "What is England's national team nickname, derived from their famous badge?",
    options: ['The Bulls', 'The Red Dragons', 'The Three Lions', 'The Saints'],
    answer: 2,
    fact: "Three lions have appeared on England's badge since the 12th century — the same symbol used by Richard I of England.",
  },
  {
    id: 119,
    question: "What is the Netherlands' national team nicknamed?",
    options: ['Het Elftal', 'Oranje', 'De Vlammen', 'Tulpen'],
    answer: 1,
    fact: "'Oranje' (Orange) — the Netherlands wears the national colour (from the Royal House of Orange) in all competitions.",
  },
  {
    id: 120,
    question: "What is Portugal's national team nickname, referencing their coat of arms?",
    options: ['Os Verdes', 'A Seleção das Quinas', 'Os Navegadores', 'A Fúria Lusitana'],
    answer: 1,
    fact: "'A Seleção das Quinas' (The Selection of the Shields) — quinas are the five shields on the Portuguese coat of arms.",
  },

  // WC FORMAT HISTORY
  {
    id: 121,
    question: "How many teams participated in the very first World Cup in 1930?",
    options: ['10', '13', '16', '18'],
    answer: 1,
    fact: "Only 13 nations entered the inaugural WC — most European sides refused the long sea voyage to Uruguay.",
  },
  {
    id: 122,
    question: "The World Cup expanded to 24 teams in which year?",
    options: ['1974', '1978', '1982', '1986'],
    answer: 2,
    fact: "Spain 1982 was the first WC with 24 teams — up from 16. It also introduced the second group-stage format.",
  },
  {
    id: 123,
    question: "The World Cup expanded to 32 teams in which year?",
    options: ['1990', '1994', '1998', '2002'],
    answer: 2,
    fact: "France 1998 was the first 32-team WC — the format that ran continuously until 2022.",
  },
  {
    id: 124,
    question: "How many matches are played in a standard 32-team World Cup?",
    options: ['56', '60', '64', '68'],
    answer: 2,
    fact: "64 matches: 48 group stage + 8 Round of 16 + 4 QFs + 2 SFs + 1 third-place play-off + 1 final.",
  },
  {
    id: 125,
    question: "Which continent has produced the most World Cup winners?",
    options: ['South America', 'Europe', 'Equal — 6 each', 'North America'],
    answer: 1,
    fact: "Europe has won 12 WC titles (Germany 4, Italy 4, France 2, England 1, Spain 1) vs South America's 10 (Brazil 5, Argentina 3, Uruguay 2).",
  },
  {
    id: 126,
    question: "No World Cup has ever been won by a team from which group of continents?",
    options: ['North America', 'Africa', 'Asia', 'All three of the above'],
    answer: 3,
    fact: "No team from Africa, Asia, or North/Central America has won the WC — though the 2026 edition gives North America its first realistic shot.",
  },

  // DISCIPLINE & RECORDS
  {
    id: 127,
    question: "Who received the first red card in World Cup history, in 1974?",
    options: ['Carlos Caszely (Chile)', 'Johan Cruyff (Netherlands)', 'Franz Beckenbauer (West Germany)', 'Gerd Müller (West Germany)'],
    answer: 0,
    fact: "Carlos Caszely of Chile was shown the first-ever WC red card against West Germany — making history for the wrong reasons.",
  },
  {
    id: 128,
    question: "At Italia '90 the WC had its lowest ever goals-per-game average. What change came in 1992 to improve attacking play?",
    options: ['3 points for a win was introduced', 'The backpass rule (keepers cannot pick up deliberate kicks)', 'The golden goal rule', 'Offside rule was relaxed'],
    answer: 1,
    fact: "After Italia '90's defensive football (2.21 goals/game), FIFA introduced the backpass rule in 1992 — goalkeepers can no longer pick up a deliberate back pass.",
  },
  {
    id: 129,
    question: "Which World Cup edition introduced 3 points for a win (instead of 2) to reward attacking play?",
    options: ['1990 Italy', '1994 USA', '1998 France', '2002 Korea/Japan'],
    answer: 1,
    fact: "USA 1994 introduced 3 points for a win — encouraging teams to go for victories rather than safe draws.",
  },

  // SPECIFIC MATCH RECORDS
  {
    id: 130,
    question: "What is the record total goals in a single World Cup match?",
    options: ['10 (Hungary 10-1 El Salvador)', '11 (Hungary 8-3 West Germany)', '12 (Austria 7-5 Switzerland)', '9 (Yugoslavia 9-0 Zaire)'],
    answer: 2,
    fact: "Austria vs Switzerland in 1954 produced 12 goals (7–5) — still the highest-scoring match in World Cup history.",
  },
  {
    id: 131,
    question: "Yugoslavia vs Zaire at the 1974 WC ended 9–0. What is the significance of that match?",
    options: ['First African team in WC', 'Second biggest winning margin in WC history', 'First WC match with a red card', 'Record own goals in one match'],
    answer: 1,
    fact: "9–0 remains the second-biggest winning margin in WC history, behind Hungary's 10–1 vs El Salvador in 1982.",
  },

  // FIFA HISTORY
  {
    id: 132,
    question: "When was FIFA, world football's governing body, founded?",
    options: ['1896', '1900', '1904', '1912'],
    answer: 2,
    fact: "FIFA was founded on 21 May 1904 in Paris by representatives from France, Belgium, Denmark, Netherlands, Spain, Sweden and Switzerland.",
  },
  {
    id: 133,
    question: "Where is FIFA's headquarters located?",
    options: ['Geneva', 'Zurich', 'Bern', 'Basel'],
    answer: 1,
    fact: "FIFA has been based in Zurich, Switzerland since its foundation. The modern FIFA House opened in 2007.",
  },
  {
    id: 134,
    question: "Which FIFA president championed the creation of the World Cup, and lent his name to the original trophy?",
    options: ['Sepp Blatter', 'João Havelange', 'Jules Rimet', 'Gianni Infantino'],
    answer: 2,
    fact: "Jules Rimet (FIFA president 1921–1954) drove the creation of the WC — the first trophy was named in his honour.",
  },

  // CULTURE & INNOVATION
  {
    id: 135,
    question: "Which noisy instrument became synonymous with the 2010 South Africa World Cup?",
    options: ['Steel drums', 'Vuvuzela', 'Djembe', 'Maracas'],
    answer: 1,
    fact: "The vuvuzela — a long plastic horn — dominated every match in South Africa, dividing fans and broadcasters worldwide.",
  },
  {
    id: 136,
    question: "The chant 'Football's Coming Home' is associated with which national team?",
    options: ['Australia', 'USA', 'England', 'Scotland'],
    answer: 2,
    fact: "'Three Lions' by Baddiel, Skinner and Lightning Seeds was England's anthem for Euro 96 — revived passionately at every major tournament since.",
  },
  {
    id: 137,
    question: "In which year did substitutes first become allowed in World Cup matches?",
    options: ['1958', '1962', '1966', '1970'],
    answer: 3,
    fact: "Substitutes were introduced at the 1970 WC in Mexico — the 1966 England WC was the last where injured players had to play on or leave the field.",
  },
  {
    id: 138,
    question: "How many substitutes per team are allowed in a standard World Cup match since 2022?",
    options: ['3', '4', '5', '6'],
    answer: 2,
    fact: "5 substitutions per team were allowed from the 2022 WC onwards — originally trialled during the COVID-19 pandemic disruptions.",
  },
  {
    id: 139,
    question: "The Jules Rimet trophy was stolen in England before the 1966 WC and found by a dog. What was the dog's name?",
    options: ['Rover', 'Pickles', 'Buster', 'Bobby'],
    answer: 1,
    fact: "A mongrel dog named Pickles found the trophy wrapped in newspaper under a garden hedge in South London — becoming a national hero.",
  },

  // PLAYER RECORDS
  {
    id: 140,
    question: "Which player appeared in the most World Cup final matches (3)?",
    options: ['Pelé', 'Cafu', 'Ronaldo (Brazil)', 'Miroslav Klose'],
    answer: 1,
    fact: "Cafu appeared in three WC finals for Brazil — 1994 (won), 1998 (lost), 2002 (won) — an unmatched record.",
  },
  {
    id: 141,
    question: "Who is the only player to score in every match of a single World Cup tournament?",
    options: ['Pelé', 'Gerd Müller', 'Jairzinho', 'Just Fontaine'],
    answer: 2,
    fact: "Jairzinho scored in all 6 of Brazil's matches at the 1970 World Cup — a feat never replicated at any tournament since.",
  },
  {
    id: 142,
    question: "Miroslav Klose scored WC goals across four consecutive tournaments. Which years?",
    options: ['1998, 2002, 2006, 2010', '2002, 2006, 2010, 2014', '2006, 2010, 2014, 2018', '2002, 2006, 2010, 2018'],
    answer: 1,
    fact: "Klose scored in 2002, 2006, 2010 and 2014 for Germany — winning gold in 2014 and bronze in 2006 and 2010.",
  },
  {
    id: 143,
    question: "Lionel Messi appeared in how many World Cups during his career?",
    options: ['3', '4', '5', '6'],
    answer: 2,
    fact: "Messi played in 2006, 2010, 2014, 2018 and 2022 — finally winning in Qatar 2022 at his fifth and last attempt.",
  },
  {
    id: 144,
    question: "Which legendary Dutch player did NOT appear at the 1978 WC, despite Netherlands reaching the final?",
    options: ['Ruud Gullit', 'Marco van Basten', 'Johan Cruyff', 'Dennis Bergkamp'],
    answer: 2,
    fact: "Cruyff refused to travel after a kidnapping attempt at his home in 1977. Netherlands still reached the final without him, losing to Argentina.",
  },
  {
    id: 145,
    question: "Zinedine Zidane played in three World Cups — winning one and being sent off in the final of another. Which WCs were they?",
    options: ['1994, 1998, 2002', '1998, 2002, 2006', '2002, 2006, 2010', '1994, 2002, 2006'],
    answer: 1,
    fact: "Zidane played in 1998 (won), 2002 (group exit) and 2006 (final, red card). His two headers in '98 remain iconic.",
  },
  {
    id: 146,
    question: "Who was the oldest player to appear in a World Cup match?",
    options: ['Roger Milla', 'Essam El-Hadary', 'Faryd Mondragón', 'Peter Shilton'],
    answer: 1,
    fact: "Egypt's Essam El-Hadary played vs Saudi Arabia at the 2018 WC at 45 years and 161 days old — a record that still stands.",
  },
  {
    id: 147,
    question: "Who was the youngest player ever to appear in a World Cup match?",
    options: ['Pelé', 'Rubén Marcos', 'Norman Whiteside', 'Cesc Fàbregas'],
    answer: 2,
    fact: "Northern Ireland's Norman Whiteside played vs Yugoslavia in 1982 at just 17 years and 41 days — younger than Pelé was in 1958.",
  },
  {
    id: 148,
    question: "Who was the youngest player to score in a World Cup Final?",
    options: ['Pelé', 'Ronaldo (Brazil)', 'Kylian Mbappé', 'Vavá'],
    answer: 0,
    fact: "Pelé scored in the 1958 WC Final at age 17 years and 249 days — the youngest goal scorer in any WC Final ever.",
  },
  {
    id: 149,
    question: "Lionel Messi won the Golden Ball at the 2014 WC despite Argentina losing the final. Who did they lose to?",
    options: ['Brazil', 'France', 'Germany', 'Netherlands'],
    answer: 2,
    fact: "Germany beat Argentina 1–0 with Götze's extra-time goal. Messi's Golden Ball was awarded but was controversial.",
  },
  {
    id: 150,
    question: "Italy missed the 2018 World Cup — their first absence from a WC since which year?",
    options: ['1950', '1954', '1958', '1966'],
    answer: 2,
    fact: "Italy last failed to qualify in 1958. Their absence from Russia 2018 ended a 60-year run of consecutive World Cup appearances.",
  },

  // OPENING MATCHES & FIRSTS
  {
    id: 151,
    question: "Which teams played in the very first World Cup match ever, on 13 July 1930?",
    options: ['Uruguay vs Argentina', 'France vs Mexico', 'USA vs Belgium', 'Brazil vs Bolivia'],
    answer: 1,
    fact: "France vs Mexico was the first-ever WC match. France won 4–1, with Lucien Laurent scoring the first-ever WC goal.",
  },
  {
    id: 152,
    question: "Who scored the very first goal in World Cup history?",
    options: ['Manuel Rosas', 'Héctor Scarone', 'Lucien Laurent', 'Bert Patenaude'],
    answer: 2,
    fact: "France's Lucien Laurent scored after 19 minutes against Mexico on 13 July 1930 — the very first WC goal in history.",
  },
  {
    id: 153,
    question: "Who scored in the opening match of the 2022 Qatar WC, netting twice for Ecuador against the hosts?",
    options: ['Romario Ibarra', 'Enner Valencia', 'Félix Torres', 'Pervis Estupiñán'],
    answer: 1,
    fact: "Enner Valencia scored twice in Ecuador's 2–0 win — Qatar became the first host nation to lose their opening WC match.",
  },
  {
    id: 154,
    question: "The first WC penalty shootout in history was played in 1982. Which teams were involved?",
    options: ['Brazil vs Italy', 'West Germany vs France', 'England vs Spain', 'Argentina vs Netherlands'],
    answer: 1,
    fact: "West Germany beat France 5–4 on penalties in Seville — the very first WC shootout, remembered as 'The Night in Seville'.",
  },
  {
    id: 155,
    question: "Who scored the first golden goal in World Cup history, ending Paraguay's 1998 campaign?",
    options: ['Thierry Henry', 'David Trezeguet', 'Laurent Blanc', 'Youri Djorkaeff'],
    answer: 2,
    fact: "Laurent Blanc headed in the golden goal for France vs Paraguay in the Round of 16 — the first WC match decided by a golden goal.",
  },

  // AWARDS & MORE MASCOTS
  {
    id: 156,
    question: "Which award is given to the World Cup's best overall player?",
    options: ['Golden Ball', 'Golden Boot', 'Platinum Award', 'FIFA Player Prize'],
    answer: 0,
    fact: "The Golden Ball has been awarded since 1930. Messi has won it twice (2014, 2022) — Ronaldo has never won one.",
  },
  {
    id: 157,
    question: "What was the mascot of the 2006 World Cup in Germany?",
    options: ['Goleo VI', 'Zakumi', 'Striker', 'Ciao'],
    answer: 0,
    fact: "Goleo VI was a lion in a Germany jersey accompanied by a talking football named Pille — named by combining 'goal' and 'leo' (lion).",
  },
  {
    id: 158,
    question: "What were the 2002 World Cup mascots — three futuristic creatures — collectively called?",
    options: ['The Zubizarri', 'The Spheriks', 'The Triblasts', 'The Futuro'],
    answer: 1,
    fact: "Ato, Kaz and Nik — known collectively as the Spheriks — were the alien-like mascots of the Japan/South Korea 2002 WC.",
  },
  {
    id: 159,
    question: "Ciao, the 1990 World Cup mascot, was a distinctive geometric figure. What shape was its body made from?",
    options: ['Circles and triangles', 'Coloured cubes stacked as a stick figure', 'A football shape', 'An Italian boot shape'],
    answer: 1,
    fact: "Ciao was a stick figure built from differently coloured cubes — one of the most abstract and memorable WC mascots ever.",
  },
  {
    id: 160,
    question: "What animal was Pique, the mascot of the 1986 World Cup in Mexico?",
    options: ['An eagle', 'A jaguar', 'A jalapeño pepper', 'An armadillo'],
    answer: 2,
    fact: "Pique was a friendly jalapeño pepper wearing a sombrero and a Mexican football kit — perfectly capturing the spirit of Mexico.",
  },

  // WC FINAL VENUES
  {
    id: 161,
    question: "Where was the 1994 World Cup Final played?",
    options: ['Giants Stadium, New Jersey', 'Rose Bowl, Pasadena', 'Stanford Stadium, San Francisco', 'Silverdome, Detroit'],
    answer: 1,
    fact: "The Rose Bowl in Pasadena, California hosted the 1994 final between Brazil and Italy before 94,194 fans.",
  },
  {
    id: 162,
    question: "Which city hosted the 2006 World Cup Final?",
    options: ['Munich', 'Hamburg', 'Frankfurt', 'Berlin'],
    answer: 3,
    fact: "Berlin's Olympiastadion hosted the 2006 final — the controversial Zidane headbutt vs Materazzi match.",
  },
  {
    id: 163,
    question: "Where was the 2018 World Cup Final played?",
    options: ['St. Petersburg', 'Moscow', 'Sochi', 'Kazan'],
    answer: 1,
    fact: "Luzhniki Stadium in Moscow hosted the 2018 final — France beat Croatia 4–2 in a thrilling match.",
  },
  {
    id: 164,
    question: "Where was the 2014 World Cup Final — Germany vs Argentina — played?",
    options: ['São Paulo', 'Salvador', 'Brasília', 'Rio de Janeiro'],
    answer: 3,
    fact: "The iconic Maracanã in Rio hosted the 2014 final — Germany won 1–0 with Götze's extra-time goal.",
  },
  {
    id: 165,
    question: "Which city hosted the 1966 World Cup Final?",
    options: ['Manchester', 'Birmingham', 'Liverpool', 'London'],
    answer: 3,
    fact: "Wembley Stadium in London hosted the 1966 final — England beat West Germany 4–2 before 98,000 fans.",
  },

  // SHOOTOUT HISTORY & ATTENDANCE
  {
    id: 166,
    question: "Which WC saw penalty shootouts introduced to resolve knockout draws (replacing replays)?",
    options: ['1966 England', '1970 Mexico', '1974 West Germany', '1978 Argentina'],
    answer: 2,
    fact: "Shootouts were introduced in the 1974 WC regulations — but the first one was actually used in a match in 1982.",
  },
  {
    id: 167,
    question: "In the first-ever WC penalty shootout (1982), which team did West Germany beat?",
    options: ['Brazil', 'France', 'England', 'Spain'],
    answer: 1,
    fact: "West Germany beat France 5–4 in Seville. The match is remembered for Harald Schumacher's brutal foul on Patrick Battiston.",
  },
  {
    id: 168,
    question: "Which WC match holds the world record for live football attendance (~199,854)?",
    options: ['1970 Mexico vs Brazil', '1950 Brazil vs Uruguay', '1966 England vs West Germany', '1986 Argentina vs West Germany'],
    answer: 1,
    fact: "The 1950 Maracanazo (Brazil vs Uruguay) drew ~200,000 fans — still the largest crowd ever at a football match.",
  },

  // MORE HISTORY
  {
    id: 169,
    question: "Which WC was the first broadcast worldwide in colour television?",
    options: ['1966 England', '1970 Mexico', '1974 West Germany', '1978 Argentina'],
    answer: 1,
    fact: "Mexico 1970 was the first WC broadcast in colour globally — revolutionising how fans worldwide experienced football.",
  },
  {
    id: 170,
    question: "What rule change followed the 'Disgrace of Gijón' (1982), where West Germany and Austria played a convenient score?",
    options: ['Bigger groups', 'Final group games played simultaneously', 'Away goals rule introduced', 'Goal difference changed'],
    answer: 1,
    fact: "From 1986, all final group games are simultaneous — preventing teams from colluding on a result that suits both.",
  },
  {
    id: 171,
    question: "The 2022 WC was the first held in which month, due to Qatar's extreme summer heat?",
    options: ['September', 'October', 'November', 'January'],
    answer: 2,
    fact: "Qatar 2022 ran November–December — the first WC not held in June/July since the inaugural 1930 tournament in Uruguay.",
  },
  {
    id: 172,
    question: "How many goals did Kylian Mbappé score at the 2022 World Cup, winning the Golden Boot at age 23?",
    options: ['6', '7', '8', '9'],
    answer: 2,
    fact: "Mbappé scored 8 goals — including a hat-trick in the final — to win the Golden Boot and become France's WC hero despite losing.",
  },
  {
    id: 173,
    question: "What was the score in the 1954 WC Final — the 'Miracle of Bern' — between West Germany and Hungary?",
    options: ['2-0', '3-1', '3-2', '4-2'],
    answer: 2,
    fact: "West Germany came from 2–0 down to win 3–2 — widely seen as a defining post-war moment for the German nation.",
  },
  {
    id: 174,
    question: "Argentina's 2022 WC win broke a 36-year drought since their previous title. What year was that?",
    options: ['1978', '1982', '1986', '1990'],
    answer: 2,
    fact: "Argentina's 1986 Maradona-inspired title and 2022 Messi-inspired title are separated by 36 years — the longest gap between titles in WC history.",
  },
  {
    id: 175,
    question: "Which country has hosted the World Cup the most times (twice, and a third time in 2026)?",
    options: ['Brazil', 'Germany', 'Mexico', 'France'],
    answer: 2,
    fact: "Mexico hosted in 1970 and 1986 — and will co-host in 2026, making it the only country to host three World Cups.",
  },
  {
    id: 176,
    question: "The current FIFA World Cup trophy is made of solid 18-carat gold. How much does it weigh?",
    options: ['4.2 kg', '6.1 kg', '8.5 kg', '10.0 kg'],
    answer: 1,
    fact: "The trophy weighs 6.175 kg and stands 36.8 cm tall — designed by Italian sculptor Silvio Gazzaniga and first awarded in 1974.",
  },
  {
    id: 177,
    question: "Which WC saw the introduction of goal-line technology for the first time?",
    options: ['2010 South Africa', '2014 Brazil', '2018 Russia', '2022 Qatar'],
    answer: 1,
    fact: "Brazil 2014 introduced Hawk-Eye goal-line technology — and also vanishing foam spray for free kicks.",
  },
  {
    id: 178,
    question: "Which team scored the most goals in a single WC tournament (27 goals in 5 matches)?",
    options: ['Brazil 1970', 'Hungary 1954', 'West Germany 1954', 'France 1958'],
    answer: 1,
    fact: "Hungary scored 27 goals in 5 matches at the 1954 WC (5.4 goals/game) — yet still lost the final to West Germany.",
  },
  {
    id: 179,
    question: "Who made his World Cup debut at age 17 in 1958, going on to win it three times?",
    options: ['Ronaldo (Brazil)', 'Garrincha', 'Pelé', 'Rivaldo'],
    answer: 2,
    fact: "Pelé debuted at 17 in 1958 (winning it), then again in 1962 and 1970 — the only player to win the WC three times.",
  },
  {
    id: 180,
    question: "Which WC was the first where the backpass rule (keepers cannot use hands on backpass) was in effect?",
    options: ['1990 Italy', '1992 European Championship', '1994 USA', '1998 France'],
    answer: 2,
    fact: "The backpass rule was introduced by FIFA in 1992 — so USA 1994 was the first WC played under this rule, encouraging more attacking football.",
  },

  // 2026 WC & CULTURE
  {
    id: 181,
    question: "How many cities in the USA will host 2026 World Cup matches?",
    options: ['8', '10', '11', '12'],
    answer: 1,
    fact: "10 US cities (NY/NJ, LA, Dallas, Miami, San Francisco, Seattle, Boston, Philadelphia, Kansas City, Atlanta) plus 3 each in Canada and Mexico.",
  },
  {
    id: 182,
    question: "Which Canadian cities will host 2026 World Cup matches?",
    options: ['Montreal and Ottawa', 'Toronto and Vancouver', 'Calgary and Edmonton', 'Toronto only'],
    answer: 1,
    fact: "Toronto (BMO Field) and Vancouver (BC Place) are Canada's two 2026 WC host cities.",
  },
  {
    id: 183,
    question: "The 2022 WC was the most compact in history — all stadiums were within how many km of Doha?",
    options: ['30 km', '55 km', '80 km', '120 km'],
    answer: 1,
    fact: "All 2022 WC stadiums were within 55 km of Doha — fans could attend multiple matches per day for the first time in WC history.",
  },

  // FAMOUS GOALS & PLAYERS
  {
    id: 184,
    question: "Which WC match saw a 17-year-old Michael Owen burst onto the world stage with a solo goal?",
    options: ['England vs Colombia 1998', 'England vs Argentina 1998', 'England vs Germany 2002', 'England vs Brazil 2002'],
    answer: 1,
    fact: "Owen's surging run and finish vs Argentina in the 1998 Round of 16 announced him to the world — though England lost on penalties.",
  },
  {
    id: 185,
    question: "Brazil won 11 consecutive WC matches between 2002 and 2006 — the longest winning streak. Who ended it?",
    options: ['Germany', 'France', 'Argentina', 'Ghana'],
    answer: 1,
    fact: "France ended Brazil's 11-game run in the 2006 WC quarter-finals, winning 1–0 with a Thierry Henry goal.",
  },
  {
    id: 186,
    question: "Which country won the WC without conceding a single goal in the knockout rounds at France 1998?",
    options: ['Brazil', 'France', 'Netherlands', 'Germany'],
    answer: 1,
    fact: "France kept clean sheets in every knockout match vs Paraguay, Italy (AET), Croatia and Brazil — conceding 0 in the knockout stages.",
  },

  // MORE RECORDS & TRIVIA
  {
    id: 187,
    question: "Who is the top scorer at the 2006 World Cup in Germany?",
    options: ['Thierry Henry', 'Miroslav Klose', 'Fernando Torres', 'Luca Toni'],
    answer: 1,
    fact: "Klose scored 5 goals at Germany 2006 — his third WC, eventually leading him to the all-time record in Brazil 2014.",
  },
  {
    id: 188,
    question: "Which WC is famous for the 'Battle of Santiago' — the most violent match in WC history?",
    options: ['1958 Sweden', '1962 Chile', '1966 England', '1974 West Germany'],
    answer: 1,
    fact: "The 1962 Italy vs Chile match had 2 red cards, brawling and police on the pitch. BBC's David Coleman called it 'the most disgraceful match in WC history.'",
  },
  {
    id: 189,
    question: "Which South American team surprised everyone by reaching the semi-finals in both 2018 and 2022?",
    options: ['Colombia', 'Ecuador', 'Uruguay', 'Croatia'],
    answer: 3,
    fact: "Croatia reached the 2018 final (lost to France 4–2) and the 2022 semi-finals (lost to Argentina) — remarkable for a country of 4 million.",
  },
  {
    id: 190,
    question: "Pelé missed the final of which World Cup he won due to injury?",
    options: ['1958', '1962', '1970', 'He played in all three finals'],
    answer: 1,
    fact: "Pelé was injured during the 1962 WC group stage and missed the final — Brazil still won 3–1 vs Czechoslovakia without him.",
  },
  {
    id: 191,
    question: "Which country recorded the most World Cup wins (matches won) in WC history?",
    options: ['Italy', 'Argentina', 'Brazil', 'Germany'],
    answer: 2,
    fact: "Brazil has won more WC matches than any other nation — having qualified for all 22 editions and consistently going deep.",
  },
  {
    id: 192,
    question: "Which WC edition first used an all-seater stadium for a final?",
    options: ['1966 England', '1974 West Germany', '1990 Italy', '1994 USA'],
    answer: 2,
    fact: "The 1990 Olympic Stadium in Rome was all-seater for the final — part of Italy's hosting improvements for that WC.",
  },
  {
    id: 193,
    question: "Cafu appeared in THREE World Cup finals for Brazil. How many did he win?",
    options: ['1 (1994)', '1 (2002)', '2 (1994 and 2002)', 'None'],
    answer: 2,
    fact: "Cafu won in 1994 and 2002 — and lost the 1998 final to France. No other player has appeared in three WC finals.",
  },
  {
    id: 194,
    question: "Which German legend scored 14 WC goals — a record until Klose beat it in 2014?",
    options: ['Franz Beckenbauer', 'Karl-Heinz Rummenigge', 'Gerd Müller', 'Rudi Völler'],
    answer: 2,
    fact: "'Der Bomber' Gerd Müller scored 14 WC goals for West Germany across 1970 and 1974 — his record stood for 40 years.",
  },
  {
    id: 195,
    question: "At which World Cup did Ronaldinho — widely seen as the world's best player at the time — perform poorly and get eliminated early?",
    options: ['2002', '2006', '2010', '2014'],
    answer: 1,
    fact: "Ronaldinho and Brazil were knocked out in the 2006 QF by France. His lack of form was one of the WC's biggest disappointments.",
  },
  {
    id: 196,
    question: "Which country's national team sport IS football, yet they have never qualified for the World Cup?",
    options: ['Greenland', 'Kosovo', 'Gibraltar', 'Faroe Islands'],
    answer: 0,
    fact: "Greenland's national football association is not affiliated with FIFA, preventing them from qualifying despite football being popular there.",
  },
  {
    id: 197,
    question: "Which WC tournament did Argentina NOT participate in — the only time in their history?",
    options: ['1930', '1934', '1938', 'They have participated in every WC'],
    answer: 2,
    fact: "Argentina skipped the 1938 WC in France, protesting that South America should host again. They have attended every other edition.",
  },
  {
    id: 198,
    question: "How many times has Mexico reached the World Cup quarter-finals?",
    options: ['1', '2', '3', '4'],
    answer: 1,
    fact: "Mexico has reached the QF twice — in 1970 and 1986 (both as hosts). They lost in the Round of 16 in six consecutive WCs (1994–2018).",
  },
  {
    id: 199,
    question: "Which WC Final is the only one ever to end without a goal in normal time and require extra time and penalties?",
    options: ['1990 West Germany vs Argentina', '1994 Brazil vs Italy', '2006 Italy vs France', '2022 Argentina vs France'],
    answer: 1,
    fact: "The 1994 final finished 0–0 after 120 minutes — the only scoreless WC final ever, decided by Brazil's 3–2 penalty win.",
  },
  {
    id: 200,
    question: "Which African team became the first to reach the WC semi-finals in 2022?",
    options: ['Senegal', 'Cameroon', 'Nigeria', 'Morocco'],
    answer: 3,
    fact: "Morocco beat Spain and Portugal on the way to the semi-finals — the first African nation to reach the last four of a World Cup.",
  },
  {
    id: 201,
    question: "Who was sent off in the very first minute of a World Cup match — the fastest red card in WC history?",
    options: ['Zinedine Zidane', 'Luis Suárez', 'José Batista (Uruguay)', 'Giorgio Chiellini'],
    answer: 2,
    fact: "José Batista of Uruguay was red-carded after just 56 seconds vs Scotland in 1986 — the fastest dismissal in WC history.",
  },
  {
    id: 202,
    question: "Which country's fans are famous for always cleaning up after themselves at World Cup stadiums?",
    options: ['Germany', 'Japan', 'South Korea', 'Brazil'],
    answer: 1,
    fact: "Japanese supporters have become iconic for staying after matches to clean up their section — a tradition celebrated worldwide at multiple WCs.",
  },
  {
    id: 203,
    question: "In the 2014 WC, which host nation suffered the biggest defeat in a WC semi-final, losing 7–1?",
    options: ['Argentina', 'Uruguay', 'Brazil', 'Colombia'],
    answer: 2,
    fact: "Brazil lost 7–1 to Germany in Belo Horizonte — the 'Mineirazo'. Germany scored five goals in 18 minutes between the 23rd and 29th minutes.",
  },
];

export function getRandomQuestions(n?: number): TriviaQuestion[] {
  const shuffled = [...ALL_QUESTIONS].sort(() => Math.random() - 0.5);
  return n !== undefined ? shuffled.slice(0, Math.min(n, shuffled.length)) : shuffled;
}
