import { TriviaQuestion } from './trivia';

export const ALL_QUESTIONS_ES: TriviaQuestion[] = [
  // GANADORES E HISTORIA
  { id: 1, question: '¿Cuántas veces ha ganado Brasil la Copa del Mundo FIFA?', options: ['3', '4', '5', '6'], answer: 2, fact: 'Brasil ganó en 1958, 1962, 1970, 1994 y 2002, más que cualquier otra nación.' },
  { id: 2, question: '¿Qué país organizó el primer Mundial de Fútbol en 1930?', options: ['Argentina', 'Brasil', 'Italia', 'Uruguay'], answer: 3, fact: 'Uruguay también ganó ese primer torneo, venciendo a Argentina 4–2 en la final.' },
  { id: 3, question: '¿Qué país ganó los Mundiales consecutivos de 1934 y 1938?', options: ['Brasil', 'Argentina', 'Alemania', 'Italia'], answer: 3, fact: 'Vittorio Pozzo, seleccionador de Italia, sigue siendo el único técnico que ha ganado el Mundial dos veces.' },
  { id: 4, question: '¿En qué año ganó Inglaterra su único título Mundial?', options: ['1962', '1966', '1970', '1974'], answer: 1, fact: 'Inglaterra venció a Alemania Occidental 4–2 en Wembley. Geoff Hurst marcó un hat-trick.' },
  { id: 5, question: '¿Cuántos títulos mundiales ha ganado Italia?', options: ['2', '3', '4', '5'], answer: 2, fact: 'Italia ganó en 1934, 1938, 1982 y 2006, su último título hasta la fecha.' },
  { id: 6, question: '¿Qué país se ha clasificado para todos y cada uno de los Mundiales desde 1930?', options: ['Alemania', 'Italia', 'Argentina', 'Brasil'], answer: 3, fact: 'Brasil es la única nación que ha participado en todas las ediciones de la Copa del Mundo.' },
  { id: 7, question: '¿En qué año ganó Francia su primer Mundial de Fútbol?', options: ['1994', '1998', '2002', '2006'], answer: 1, fact: 'Francia venció a Brasil 3–0 en la final de París; Zidane marcó dos goles de cabeza.' },
  { id: 8, question: '¿Qué país ganó el primer Mundial de la FIFA en 1930?', options: ['Argentina', 'Brasil', 'EE. UU.', 'Uruguay'], answer: 3, fact: 'El anfitrión Uruguay venció a Argentina 4–2 en la final de Montevideo.' },

  // GOLEADORES Y RÉCORDS
  { id: 9, question: '¿Quién es el máximo goleador histórico del Mundial con 16 goles?', options: ['Pelé', 'Ronaldo (Brasil)', 'Miroslav Klose', 'Gerd Müller'], answer: 2, fact: 'Klose marcó 16 goles en cuatro Mundiales (2002–2014) con Alemania.' },
  { id: 10, question: '¿Qué récord de goles en un solo torneo estableció Just Fontaine en 1958?', options: ['10 goles', '11 goles', '12 goles', '13 goles'], answer: 3, fact: 'Jugando con Francia, Fontaine anotó 13 goles en solo 6 partidos, récord que aún se mantiene.' },
  { id: 11, question: '¿Quién marcó el gol más rápido en la historia del Mundial, en apenas 11 segundos?', options: ['Clint Dempsey', 'Hakan Şükür', 'Bryan Ruiz', 'Oleg Salenko'], answer: 1, fact: 'Şükür marcó para Turquía ante Corea del Sur en el partido por el tercer puesto de 2002.' },
  { id: 12, question: '¿Quién marcó más goles en un solo partido del Mundial, anotando 5 ante Camerún en 1994?', options: ['Gerd Müller', 'Just Fontaine', 'Oleg Salenko', 'Miroslav Klose'], answer: 2, fact: 'Salenko marcó 5 goles para Rusia frente a Camerún en 1994, récord absoluto en un partido.' },
  { id: 13, question: '¿Quién ganó la Bota de Oro en el Mundial de Rusia 2018?', options: ['Antoine Griezmann', 'Cristiano Ronaldo', 'Romelu Lukaku', 'Harry Kane'], answer: 3, fact: 'Kane marcó 6 goles con Inglaterra, incluyendo dos hat-tricks, más que ningún otro jugador en Rusia 2018.' },
  { id: 14, question: '¿Qué Mundial registró el promedio de goles por partido más alto (5,38 goles/partido)?', options: ['1930 Uruguay', '1954 Suiza', '1970 México', '1982 España'], answer: 1, fact: 'En 1954 hubo goleadores legendarios: Hungría venció a Alemania Occidental 8–3 en la fase de grupos.' },
  { id: 15, question: '¿Quién fue el jugador más veterano en marcar un gol en la historia del Mundial, a los 42 años?', options: ['Essam El-Hadary', 'Roger Milla', 'Lothar Matthäus', 'Peter Shilton'], answer: 1, fact: 'Milla salió de su retiro para jugar con Camerún en los Mundiales de 1990 y 1994.' },
  { id: 16, question: '¿Qué jugador ha disputado más partidos mundialistas (25)?', options: ['Miroslav Klose', 'Cafu', 'Paolo Maldini', 'Lothar Matthäus'], answer: 3, fact: 'Matthäus jugó en 5 Mundiales con Alemania Occidental/Alemania entre 1982 y 1998.' },
  { id: 17, question: '¿Quién es el jugador más joven en marcar un gol en la historia del Mundial?', options: ['Michael Owen', 'Pelé', 'Cesc Fàbregas', 'Wayne Rooney'], answer: 1, fact: 'Pelé anotó en el Mundial de 1958 con tan solo 17 años y 239 días.' },
  { id: 18, question: '¿Cuántos goles marcó Ronaldo (Brasil) en el Mundial de 2002, incluyendo 2 en la final?', options: ['6', '7', '8', '9'], answer: 2, fact: 'Los 8 goles de Ronaldo le valieron la Bota de Oro. Marcó los dos tantos en la victoria 2–0 sobre Alemania.' },

  // MOMENTOS MEMORABLES
  { id: 19, question: '¿Quién marcó el infame gol con "La Mano de Dios" ante Inglaterra en el Mundial de 1986?', options: ['Pelé', 'Diego Maradona', 'Ronaldo', 'Ronaldinho'], answer: 1, fact: 'En ese mismo partido, Maradona también marcó el "Gol del Siglo", elegido el mejor gol mundialista de la historia.' },
  { id: 20, question: '¿Qué país venció a Alemania 7–1 en la semifinal del Mundial 2014 ("el Mineirazo")?', options: ['Argentina', 'Francia', 'Países Bajos', 'Brasil'], answer: 3, fact: 'El partido en Belo Horizonte se considera uno de los mayores shocks de la historia del fútbol.' },
  { id: 21, question: '¿Quién marcó el gol de la victoria de Alemania en la Final del Mundial 2014, en la prórroga?', options: ['Thomas Müller', 'Mesut Özil', 'Bastian Schweinsteiger', 'Mario Götze'], answer: 3, fact: 'Götze, llegado desde el banquillo, anotó en el minuto 113 para ganar a Argentina 1–0.' },
  { id: 22, question: '¿Quién fue expulsado por dar un cabezazo a Marco Materazzi en la Final del Mundial 2006?', options: ['Patrick Vieira', 'Thierry Henry', 'Zinedine Zidane', 'Franck Ribéry'], answer: 2, fact: 'En su último partido profesional, Zidane fue expulsado con tarjeta roja y aun así ganó el Balón de Oro del torneo.' },
  { id: 23, question: '¿Qué selección africana llegó por primera vez a las semifinales de un Mundial en Catar 2022?', options: ['Senegal', 'Ghana', 'Nigeria', 'Marruecos'], answer: 3, fact: 'Marruecos eliminó a España y Portugal antes de caer ante Francia en semifinales.' },
  { id: 24, question: '¿Qué jugador marcó un hat-trick en la Final del Mundial 2022 pero acabó en el lado perdedor?', options: ['Antoine Griezmann', 'Ousmane Dembélé', 'Olivier Giroud', 'Kylian Mbappé'], answer: 3, fact: 'El hat-trick de Mbappé convirtió a Francia en el primer equipo desde 1966 en marcar 3 goles en una final mundial y perder.' },
  { id: 25, question: '¿En qué Mundial se usó el VAR (Asistente de Vídeo) por primera vez?', options: ['2014 Brasil', '2018 Rusia', '2022 Catar', '2010 Sudáfrica'], answer: 1, fact: 'El VAR debutó en Rusia 2018 y propició un número récord de penaltis pitados.' },
  { id: 26, question: '¿Qué selección logró la mayor goleada de la historia del Mundial, venciendo 10–1 a El Salvador?', options: ['Hungría', 'Yugoslavia', 'Alemania', 'Brasil'], answer: 0, fact: 'Hungría venció a El Salvador 10–1 en el Mundial de España 1982.' },

  // PAÍSES ANFITRIONES
  { id: 27, question: '¿En qué país se celebró el Mundial de 2010?', options: ['Sudáfrica', 'Brasil', 'Alemania', 'Japón'], answer: 0, fact: 'Sudáfrica 2010 fue el primer Mundial celebrado en el continente africano.' },
  { id: 28, question: '¿Qué tres países serán coanfitriones del Mundial de la FIFA 2026?', options: ['EE. UU., México y Brasil', 'EE. UU., Canadá y México', 'México, Canadá y Colombia', 'EE. UU., Canadá y Argentina'], answer: 1, fact: 'Con 16 ciudades sede en tres países, 2026 será el primer Mundial con triple anfitrión.' },
  { id: 29, question: '¿Qué Mundial fue el primero celebrado en Asia?', options: ['1998 Francia', '2002 Japón y Corea del Sur', '2006 Alemania', '2010 Sudáfrica'], answer: 1, fact: 'Japón y Corea del Sur fueron coanfitriones en 2002, el primer Mundial organizado conjuntamente.' },
  { id: 30, question: '¿Cuántos equipos participarán en el Mundial de la FIFA 2026, frente a los 32 actuales?', options: ['36', '40', '48', '64'], answer: 2, fact: 'El formato de 48 equipos añade una nueva ronda de 32 y da a más naciones la oportunidad de clasificarse.' },

  // TROFEOS
  { id: 31, question: '¿Cómo se llamaba el trofeo original del Mundial, entregado entre 1930 y 1970?', options: ['Trofeo Henri Delaunay', 'Trofeo Jules Rimet', 'Copa FIFA del Mundo', 'Coupe du Monde'], answer: 1, fact: 'Brasil lo ganó definitivamente en 1970 tras su tercer título. El original fue robado después y nunca se recuperó.' },
  { id: 32, question: '¿En qué año se entregó por primera vez el actual trofeo de la Copa del Mundo FIFA?', options: ['1966', '1970', '1974', '1982'], answer: 2, fact: 'Fabricado en oro de 18 quilates con base de malaquita, el trofeo actual fue diseñado por el artista italiano Silvio Gazzaniga.' },

  // MASCOTAS
  { id: 33, question: '¿Cuál fue el nombre de la primera mascota oficial del Mundial, presentada en Inglaterra 1966?', options: ['Striker', 'World Cup Willie', 'Footix', 'Goleo'], answer: 1, fact: 'World Cup Willie era un león con una camiseta de la Union Jack, pionero de todas las mascotas mundialistas.' },
  { id: 34, question: '¿Cuál fue la mascota del Mundial de 1998 en Francia?', options: ['Ciao', 'Footix', 'Pique', 'Naranjito'], answer: 1, fact: 'Footix era un gallo azul, símbolo nacional de Francia (el gallo galo), con equipación de fútbol.' },
  { id: 35, question: '¿Qué animal era Fuleco, la mascota del Mundial de Brasil 2014?', options: ['Tucán', 'Jaguar', 'Armadillo de tres bandas', 'Rana arborícola'], answer: 2, fact: 'Fuleco representaba a una especie en peligro de extinción nativa de Brasil, concienciando sobre la conservación.' },
  { id: 36, question: '¿Cuál fue la mascota del Mundial de 2010 en Sudáfrica?', options: ['Fuleco', 'Zakumi', 'Footix', 'Goleo'], answer: 1, fact: '"Za" significa Sudáfrica y "kumi" significa "diez" en varios idiomas africanos.' },
  { id: 37, question: '¿Cuál fue la mascota del Mundial de 2018 en Rusia?', options: ['Zabivaka', 'Goleo VI', 'Striker', 'Ciao'], answer: 0, fact: '"Zabivaka" significa "el que mete goles" en ruso: un simpático lobo con equipación de fútbol.' },
  { id: 38, question: '¿Cuál fue la mascota del Mundial de 2022 en Catar?', options: ['Goleo VI', 'Zabivaka', "La'eeb", 'Tazuni'], answer: 2, fact: "La'eeb significa 'jugador con mucha clase' en árabe y se representaba como una figura fantasmagórica y fluida." },
  { id: 39, question: '¿Cuál fue la mascota del Mundial de 1994 en Estados Unidos?', options: ['Striker', 'Ciao', 'Pique', 'Naranjito'], answer: 0, fact: 'Striker era un perro con la camiseta de EE. UU., una de las primeras mascotas mundialistas diseñada por un estudio de Hollywood.' },
  { id: 40, question: 'Naranjito, mascota del Mundial 1982 en España, ¿con qué fruta estaba disfrazado?', options: ['Limón', 'Naranja', 'Sandía', 'Tomate'], answer: 1, fact: '"Naranja" en español. Naranjito vestía la camiseta de España y fue enormemente popular.' },

  // FINALES
  { id: 41, question: '¿Qué estadio es el único que ha albergado dos finales distintas del Mundial?', options: ['Maracaná', 'Estadio Azteca', 'Luzhniki', 'Wembley'], answer: 1, fact: 'El Azteca en Ciudad de México acogió la final de 1970 (Brasil 4–1 Italia) y la de 1986 (Argentina 3–2 Alemania Occidental).' },
  { id: 42, question: '¿Quién marcó el gol de la victoria de España en la Final del Mundial 2010 ante Países Bajos?', options: ['David Villa', 'Fernando Torres', 'Andrés Iniesta', 'Xavi'], answer: 2, fact: 'Iniesta anotó en el minuto 116 de la prórroga. Sigue siendo el único título mundial de España.' },
  { id: 43, question: 'La Final del Mundial 1994 terminó 0–0 y se fue a penaltis. ¿Quién falló el decisivo de Italia?', options: ['Franco Baresi', 'Daniele Massaro', 'Roberto Baggio', 'Demetrio Albertini'], answer: 2, fact: 'El fallo de Baggio sobre la portería dio el título a Brasil 3–2 en los penaltis, una de las imágenes más icónicas del fútbol.' },
  { id: 44, question: '¿Qué país ha disputado más finales mundialistas (8 veces)?', options: ['Brasil', 'Italia', 'Alemania', 'Argentina'], answer: 2, fact: 'Alemania/Alemania Occidental ha llegado a 8 finales (1954, 1966, 1974, 1982, 1986, 1990, 2002, 2014), ganando 4.' },

  // GRANDES SORPRESAS
  { id: 45, question: '¿Qué selección sorprendió al campeón Francia 1–0 en el partido inaugural del Mundial 2002?', options: ['Corea del Sur', 'Senegal', 'Japón', 'Turquía'], answer: 1, fact: 'Senegal, en su segundo Mundial, dejó sin palabras a Francia, que había ganado en 1998 y la Euro 2000.' },
  { id: 46, question: '¿Qué campeón defensor fue eliminado en la fase de grupos en Rusia 2018?', options: ['España', 'Alemania', 'Italia', 'Brasil'], answer: 1, fact: 'Alemania, campeona en 2014, acabó última en su grupo tras caer ante México y Corea del Sur.' },
  { id: 47, question: 'EE. UU. venció a Inglaterra 1–0 en el Mundial de 1950. ¿Quién marcó el gol?', options: ['Joe Gaetjens', 'Walter Bahr', 'Frank Wallace', 'Eddie McIlvenny'], answer: 0, fact: 'El cabezazo de Joe Gaetjens en el minuto 37 produjo una de las mayores sorpresas de la historia del Mundial.' },
  { id: 48, question: '¿Qué selección africana inauguró Italia \'90 venciendo a la campeona Argentina?', options: ['Nigeria', 'Ghana', 'Senegal', 'Camerún'], answer: 3, fact: 'El Camerún de Roger Milla venció a Argentina 1–0 en el partido inaugural, un resultado que dejó atónito al mundo futbolístico.' },
  { id: 49, question: 'Arabia Saudí protagonizó una impresionante sorpresa en el grupo del Mundial 2022. ¿A quién venció 2–1?', options: ['Brasil', 'Francia', 'Argentina', 'Inglaterra'], answer: 2, fact: 'Arabia Saudí rompió la racha de 36 partidos invictos de Argentina, considerada una de las mayores sorpresas mundialistas.' },

  // APODOS DE SELECCIONES
  { id: 50, question: 'La selección brasileña se llama "A Seleção". ¿Qué significa?', options: ['Los Guerreros', 'La Selección', 'Los Amarillos', 'Los Campeones'], answer: 1, fact: '"A Seleção" simplemente significa "La Selección", usado tan universalmente en Brasil que no necesita más descripción.' },
  { id: 51, question: '¿Cuál es el apodo de la selección alemana de fútbol?', options: ['Die Roten', 'Die Adler', 'Die Mannschaft', 'Das Team'], answer: 2, fact: '"Die Mannschaft" significa "El Equipo" en alemán, consagrado globalmente tras su dominio en 2014.' },
  { id: 52, question: '¿Cuál es el apodo de la selección argentina, que hace referencia a los colores de su camiseta?', options: ['Los Pumas', 'La Albiceleste', 'Los Gauchos', 'El Tri'], answer: 1, fact: '"La Albiceleste" significa "la blanca y celeste", las icónicas franjas que lucen desde 1908.' },
  { id: 53, question: 'La selección de México se llama "El Tri". ¿A qué hace referencia?', options: ['Tres leyendas', 'El tricolor (bandera)', 'Tres veces campeones', 'Trinidad del ataque'], answer: 1, fact: '"El Tri" es la abreviatura de "El Tricolor", en referencia al verde, blanco y rojo de la bandera mexicana.' },

  // ENTRENADORES
  { id: 54, question: 'Vittorio Pozzo es el único seleccionador que ha ganado el Mundial dos veces (1934 y 1938). ¿Con qué país?', options: ['Argentina', 'Brasil', 'Italia', 'Uruguay'], answer: 2, fact: 'Pozzo llevó a Italia a dos títulos consecutivos, hazaña que ningún otro técnico ha igualado en la historia del Mundial.' },
  { id: 55, question: '¿Qué seleccionador neerlandés llevó a Corea del Sur a las semifinales del Mundial 2002?', options: ['Louis van Gaal', 'Guus Hiddink', 'Dick Advocaat', 'Johan Cruyff'], answer: 1, fact: 'El Corea del Sur de Hiddink eliminó a España e Italia para alcanzar las semifinales.' },
  { id: 56, question: 'Didier Deschamps (2018) fue la tercera persona en ganar el Mundial como jugador y como técnico. ¿Quién fue el primero?', options: ['Franz Beckenbauer', 'Johan Cruyff', 'Pelé', 'Michel Platini'], answer: 0, fact: 'Beckenbauer ganó como jugador en 1974 y como técnico en 1990 (ambas con Alemania). Zagallo lo hizo con Brasil; Deschamps con Francia.' },

  // ESTADIOS ICÓNICOS
  { id: 57, question: '¿Cómo se llama el impactante triunfo de Uruguay ante Brasil en el Maracaná en 1950?', options: ['El Milagro de Berna', 'El Maracanazo', 'La Tragedia de Río', 'El Golpe Final'], answer: 1, fact: '"El Maracanazo": Uruguay venció a Brasil 2–1 ante ~200.000 espectadores en Río, el recuerdo más doloroso del fútbol brasileño.' },
  { id: 58, question: '¿Qué estadio albergará la Final del Mundial 2026?', options: ['AT&T Stadium, Dallas', 'Rose Bowl, Los Ángeles', 'MetLife Stadium, Nueva Jersey', 'SoFi Stadium, Los Ángeles'], answer: 2, fact: 'El MetLife Stadium en East Rutherford (NJ), en el área metropolitana de Nueva York, acogerá la Final del Mundial 2026.' },

  // CANCIONES DEL MUNDIAL
  { id: 59, question: '¿Quién interpretó "Waka Waka (This Time for Africa)", la canción oficial del Mundial 2010?', options: ['Beyoncé', 'Shakira', 'Jennifer Lopez', 'Rihanna'], answer: 1, fact: 'El Waka Waka de Shakira se convirtió en una de las canciones mundialistas más vendidas, superando los 1.000 millones de visitas en YouTube.' },
  { id: 60, question: '¿Qué pieza operística se convirtió en el himno icónico de la BBC para el Mundial de Italia 1990?', options: ['World in Motion', 'Three Lions', 'Nessun Dorma', 'La Copa de la Vida'], answer: 2, fact: 'El Nessun Dorma de Pavarotti, usado como sintonía de la BBC, fue uno de los símbolos definitorios de Italia \'90.' },
  { id: 61, question: '"La Copa de la Vida" de Ricky Martin fue la canción oficial de qué Mundial?', options: ['1994 EE. UU.', '1998 Francia', '2002 Corea/Japón', '2006 Alemania'], answer: 1, fact: '"La Copa de la Vida", interpretada en directo en la ceremonia de la final en París, se convirtió en un himno global de estadio.' },

  // HAT-TRICKS
  { id: 62, question: '¿Quién es el único jugador que ha marcado un hat-trick en una Final de la Copa del Mundo?', options: ['Pelé', 'Geoff Hurst', 'Ronaldo (Brasil)', 'Zinedine Zidane'], answer: 1, fact: 'Hurst marcó 3 de los 4 goles de Inglaterra en la Final de 1966 ante Alemania Occidental, el único hat-trick en cualquier final mundialista.' },
  { id: 63, question: 'Cristiano Ronaldo marcó un hat-trick en el Mundial de 2018. ¿Contra qué rival?', options: ['Marruecos', 'Irán', 'España', 'Uruguay'], answer: 2, fact: 'El hat-trick de Ronaldo, incluido un espectacular gol de falta al final, selló un electrizante empate 3–3 con España en la fase de grupos.' },

  // PENALTIS Y TANDAS
  { id: 64, question: '¿Qué Final del Mundial fue la primera decidida por una tanda de penaltis?', options: ['1982 España', '1986 México', '1990 Italia', '1994 EE. UU.'], answer: 3, fact: 'La final de 1994 entre Brasil e Italia fue la primera decidida en los penaltis: Brasil ganó 3–2.' },
  { id: 65, question: '¿Qué selección ha ganado sus 5 tandas de penaltis en Mundiales, con pleno de victorias?', options: ['Alemania', 'Brasil', 'Argentina', 'España'], answer: 0, fact: 'El pleno de Alemania en tandas mundialistas (5 de 5) no tiene parangón entre las grandes naciones.' },

  // HITOS AFRICANOS Y ASIÁTICOS
  { id: 66, question: '¿En qué año llegó Camerún a los cuartos de final del Mundial por primera vez, siendo la primera selección africana?', options: ['1982', '1986', '1990', '1994'], answer: 2, fact: 'Los "Leones Indomables" en Italia \'90 vencieron a Argentina en el inicio y llegaron a cuartos.' },
  { id: 67, question: '¿Qué selección asiática llegó por primera vez a las semifinales de un Mundial en 2002?', options: ['Japón', 'Corea del Sur', 'Arabia Saudí', 'China'], answer: 1, fact: 'El anfitrión Corea del Sur venció a España e Italia para llegar a las semifinales, el mejor resultado de Asia en un Mundial.' },

  // INNOVACIÓN Y FORMATO
  { id: 68, question: '¿Qué Mundial fue el primero emitido en televisión a color en todo el mundo?', options: ['1966 Inglaterra', '1970 México', '1974 Alemania Occidental', '1978 Argentina'], answer: 1, fact: 'México 1970 fue el primer Mundial en color, transformando la experiencia de miles de millones de aficionados.' },
  { id: 69, question: 'Brasil 2014 introdujo la tecnología de línea de gol. ¿Qué otra innovación debutó en ese torneo?', options: ['VAR', 'Espray desvanecedor para faltas', 'GPS para jugadores', 'Repeticiones en pantallas'], answer: 1, fact: 'El espray desvanecedor para las barreras en las faltas se usó por primera vez en Brasil 2014 y se adoptó en todo el mundo poco después.' },
  { id: 70, question: '¿Cuántos grupos tendrá el Mundial 2026 con el formato de 48 equipos?', options: ['8', '10', '12', '16'], answer: 2, fact: '48 equipos en 12 grupos de 4: los 2 primeros más los 8 mejores terceros pasan a la nueva ronda de 32.' },

  // MÁS RÉCORDS Y MOMENTOS
  { id: 71, question: 'El "Gol del Siglo" de Maradona en 1986, en el que regateó a 5 jugadores, fue marcado ante...', options: ['Bélgica', 'Alemania Occidental', 'Inglaterra', 'Francia'], answer: 2, fact: 'Elegido el mejor gol mundialista, el regate de Maradona a Inglaterra se produjo en el mismo partido que la "Mano de Dios".' },
  { id: 72, question: 'Diego Maradona fue expulsado del Mundial de 1994 a mitad del torneo. ¿Por qué?', options: ['Conducta violenta', 'Dio positivo en un control antidopaje', 'Falsificación de pasaporte', 'Se negó a jugar'], answer: 1, fact: 'Maradona dio positivo por efedrina tras la victoria de Argentina ante Grecia, poniendo fin a su carrera mundialista de la peor manera.' },
  { id: 73, question: 'El Mundial de 1950 no tuvo una final eliminatoria. ¿Cómo se decidió el campeón?', options: ['Gol de oro', 'Liguilla final de cuatro equipos', 'Tanda de penaltis', 'Sorteo'], answer: 1, fact: 'Una liguilla de cuatro equipos: Uruguay venció a Brasil en el partido decisivo para proclamarse campeón.' },
  { id: 74, question: '¿Qué Mundial fue el primero celebrado fuera de Europa o América?', options: ['1994 EE. UU.', '2002 Japón y Corea del Sur', '2010 Sudáfrica', '2022 Catar'], answer: 1, fact: 'Japón y Corea del Sur 2002 fue el primer Mundial en Asia y la primera edición coorganizada.' },
  { id: 75, question: '¿Qué nación fue anfitriona Y ganadora del Mundial de 1978?', options: ['Chile', 'Brasil', 'Argentina', 'Perú'], answer: 2, fact: 'Argentina venció a Países Bajos 3–1 en la prórroga en Buenos Aires, su primer título mundial en casa.' },
  { id: 76, question: '¿Quién ganó el Balón de Oro (mejor jugador) en el Mundial de Catar 2022?', options: ['Kylian Mbappé', 'Luka Modrić', 'Lionel Messi', 'Antoine Griezmann'], answer: 2, fact: 'Los 7 goles y 3 asistencias de Messi le valieron el Balón de Oro, completando su camino hacia el máximo honor del fútbol.' },
  { id: 77, question: 'La "Batalla de Santiago" de 1962, el partido más violento del Mundial, fue entre...', options: ['Brasil vs Argentina', 'Italia vs Chile', 'Alemania vs Países Bajos', 'Inglaterra vs Francia'], answer: 1, fact: 'Chile venció a Italia 2–0, pero el partido tuvo 2 expulsiones, peleas masivas y policías en el campo. El periodista David Coleman de la BBC lo llamó "el partido más vergonzoso de la historia del Mundial".' },
  { id: 78, question: '¿Qué selección marcó en sus 7 partidos en el Mundial de Rusia 2018?', options: ['Francia', 'Inglaterra', 'Bélgica', 'Croacia'], answer: 2, fact: 'Bélgica marcó en todos sus 7 partidos en Rusia 2018, camino de un récord de tercer puesto.' },

  // MÁS CAMPEONES E HISTORIA
  { id: 79, question: 'Argentina ha ganado el Mundial tres veces. ¿En qué años?', options: ['1966, 1982, 2014', '1978, 1986, 2022', '1970, 1990, 2014', '1978, 1998, 2022'], answer: 1, fact: 'Argentina ganó en 1978 (en casa), 1986 (era Maradona) y 2022 (era Messi), abarcando 44 años.' },
  { id: 80, question: '¿Qué país ganó el Mundial de la FIFA 2022 en Catar?', options: ['Francia', 'Croacia', 'Marruecos', 'Argentina'], answer: 3, fact: 'Argentina venció a Francia en la tanda de penaltis tras un dramático empate 3–3.' },
  { id: 81, question: '¿Cuántos países diferentes han ganado alguna vez la Copa del Mundo FIFA?', options: ['6', '7', '8', '9'], answer: 2, fact: 'Brasil (5), Alemania (4), Italia (4), Argentina (3), Francia (2), Uruguay (2), Inglaterra (1), España (1): 8 naciones en total.' },
  { id: 82, question: 'Uruguay ha ganado el Mundial dos veces. ¿En qué años?', options: ['1930 y 1938', '1930 y 1950', '1950 y 1966', '1934 y 1950'], answer: 1, fact: 'Uruguay ganó el primer Mundial en 1930 en casa y el de 1950, derrotando famosamente a Brasil en el Maracaná.' },
  { id: 83, question: '¿Cuántas veces ganó Pelé el Mundial?', options: ['1', '2', '3', '4'], answer: 2, fact: 'Pelé ganó en 1958, 1962 y 1970, el único jugador que forma parte de tres selecciones campeonas del mundo.' },
  { id: 84, question: '¿Cuál de estos grupos de países anfitriones ganó TODOS el Mundial en casa?', options: ['Uruguay, Italia, Inglaterra, Argentina, Francia', 'Brasil, Inglaterra, Alemania, Argentina, Francia', 'Italia, Inglaterra, Brasil, Argentina, España', 'Uruguay, Italia, Argentina, Alemania, Francia'], answer: 0, fact: 'Uruguay (1930), Italia (1934), Inglaterra (1966), Argentina (1978) y Francia (1998) ganaron siendo anfitriones. Alemania en 2006 quedó tercera.' },
  { id: 85, question: '¿Quién marcó el tercer gol de Francia en la Final del Mundial 1998 para sellar la victoria 3–0 sobre Brasil?', options: ['Thierry Henry', 'David Trezeguet', 'Zinedine Zidane', 'Emmanuel Petit'], answer: 3, fact: 'Petit anotó de contragolpe en el minuto 90. Zidane había marcado dos goles de cabeza antes.' },
  { id: 86, question: 'Francia es bicampeona del mundo. ¿En qué dos años?', options: ['1994 y 2010', '1998 y 2014', '1998 y 2018', '2002 y 2018'], answer: 2, fact: 'Francia ganó como anfitriona en 1998 (3–0 a Brasil) y en Rusia 2018 (4–2 a Croacia).' },
  { id: 87, question: 'Alemania ha ganado 4 Mundiales. ¿Cuál de estos años NO fue uno de ellos?', options: ['1954', '1966', '1990', '2014'], answer: 1, fact: 'Alemania ganó en 1954, 1974, 1990 y 2014. Perdió finales en 1966, 1982, 1986 y 2002.' },

  // MÁS GOLEADORES
  { id: 88, question: '¿Quién ganó la Bota de Oro en el Mundial de Brasil 2014?', options: ['Neymar', 'Thomas Müller', 'James Rodríguez', 'Lionel Messi'], answer: 2, fact: 'El colombiano James Rodríguez marcó 6 goles en 5 partidos con solo 22 años, incluido un sensacional volea ante Uruguay.' },
  { id: 89, question: '¿Quién fue el máximo goleador del Mundial de Francia 1998 con 6 goles?', options: ['Ronaldo (Brasil)', 'Davor Šuker', 'Gabriel Batistuta', 'Marcelo Salas'], answer: 1, fact: 'El croata Davor Šuker marcó 6 goles, incluida una sutil vaselina ante Dinamarca, ayudando a Croacia a quedar tercera en su debut.' },
  { id: 90, question: '¿Quién marcó 8 goles en el primer Mundial de 1930 y ganó el trofeo al máximo goleador?', options: ['José Andrade', 'Guillermo Stábile', 'Pedro Cea', 'Héctor Castro'], answer: 1, fact: 'El argentino Stábile anotó 8 goles en solo 4 partidos, a pesar de no haber jugado el partido inaugural.' },
  { id: 91, question: 'Sándor Kocsis marcó 11 goles en el Mundial de 1954 con... ¿qué selección?', options: ['Checoslovaquia', 'Polonia', 'Hungría', 'Rumanía'], answer: 2, fact: '"La Cabeza de Oro" de Hungría marcó 11 goles en 5 partidos, pero Hungría aún así perdió la final 3–2 ante Alemania Occidental.' },
  { id: 92, question: 'Gabriel Batistuta marcó hat-tricks mundialistas en dos torneos distintos. ¿En qué años?', options: ['1990 y 1994', '1994 y 1998', '1998 y 2002', '1986 y 1990'], answer: 1, fact: 'Batistuta marcó ante Grecia en 1994 y ante Jamaica en 1998, uno de solo dos jugadores con hat-tricks mundialistas en dos ediciones.' },
  { id: 93, question: '¿Quién es el máximo goleador histórico de Brasil en Mundiales con 15 goles?', options: ['Pelé', 'Zico', 'Ronaldo (Fenômeno)', 'Neymar'], answer: 2, fact: 'Ronaldo (Brasil) marcó 15 goles mundialistas en cuatro torneos (1994–2006), más que los 12 de Pelé o los 8 de Neymar.' },
  { id: 94, question: '¿Cuántos goles mundialistas marcó Pelé en sus tres campañas ganadoras?', options: ['8', '10', '12', '14'], answer: 2, fact: 'Pelé marcó 12 goles en 1958, 1962 y 1970, incluyendo un récord de 6 en su debut mundialista a los 17 años.' },
  { id: 95, question: 'Antes de que Messi le superara en 2022, ¿quién era el máximo goleador histórico de Argentina en Mundiales?', options: ['Diego Maradona', 'Gabriel Batistuta', 'Mario Kempes', 'Hernán Crespo'], answer: 1, fact: 'Los 10 goles mundialistas de Batistuta fueron el récord argentino hasta que Messi le superó en Catar 2022, terminando con 13.' },

  // MÁS MOMENTOS MEMORABLES
  { id: 96, question: 'El "Milagro de Berna" fue la impactante victoria de Alemania Occidental en la Final de 1954 desde 0–2. ¿A quién vencieron?', options: ['Brasil', 'Uruguay', 'Hungría', 'Checoslovaquia'], answer: 2, fact: 'Hungría llevaba 4 años invicta en 33 partidos. Alemania Occidental remontó para ganar 3–2 en una de las mayores sorpresas del deporte.' },
  { id: 97, question: '¿Qué semifinal del Mundial de 1970 se conoció como "El Partido del Siglo"?', options: ['Brasil vs Inglaterra', 'Italia vs Alemania Occidental', 'Brasil vs Uruguay', 'Inglaterra vs Alemania Occidental'], answer: 1, fact: 'Italia venció a Alemania Occidental 4–3 en un extraordinario partido de prórroga, con 4 goles en los últimos 19 minutos.' },
  { id: 98, question: 'Las icónicas celebraciones de Roger Milla en el Mundial de 1990 consistían en bailar alrededor de...', options: ['El poste', 'El banderín de córner', 'El árbitro', 'El trofeo'], answer: 1, fact: 'El baile del banderín de Milla en Italia \'90 es una de las celebraciones más queridas del fútbol, que repitió 4 años después a los 42 años.' },
  { id: 99, question: 'Laurent Blanc marcó el primer gol de oro de la historia del Mundial en 1998. ¿Contra qué país?', options: ['México', 'Colombia', 'Paraguay', 'Ecuador'], answer: 2, fact: 'El cabezazo de Blanc en la prórroga eliminó a Paraguay en los octavos de final, el primer partido mundialista decidido por el gol de oro.' },
  { id: 100, question: 'Paolo Rossi marcó un hat-trick en el Mundial de 1982 para eliminar a un gran favorito. ¿A quién?', options: ['Alemania Occidental', 'Argentina', 'Brasil', 'Francia'], answer: 2, fact: 'Los 3 goles de Rossi ante Brasil (3–2) pusieron fin al camino de Zico y Falcão, candidatos al título, y llevaron a Italia a la corona.' },
  { id: 101, question: '¿Quién marcó el penalti de la victoria de Alemania Occidental en la Final del Mundial 1990 ante Argentina?', options: ['Lothar Matthäus', 'Andreas Brehme', 'Rudi Völler', 'Thomas Häßler'], answer: 1, fact: 'Brehme lo transformó en el minuto 85 para el 1–0, la primera final mundialista decidida por un penalti en el tiempo reglamentario.' },
  { id: 102, question: 'Gordon Banks realizó la que muchos consideran la mejor parada de la historia del fútbol en el Mundial 1970. ¿Cuyo remate detuvo?', options: ['Garrincha', 'Eusébio', 'Jairzinho', 'Pelé'], answer: 3, fact: 'Banks sacó de la línea un cabezazo de Pelé con la mano derecha. El propio Pelé dijo: "Fue la mejor parada que he visto en mi vida".' },
  { id: 103, question: 'Archie Gemmill marcó un famoso gol individual en el Mundial 1978 ante Países Bajos. ¿Con qué selección?', options: ['Inglaterra', 'República de Irlanda', 'Escocia', 'Gales'], answer: 2, fact: 'El regate de Gemmill es el momento más celebrado de Escocia en un Mundial, aunque acabaron eliminados en la fase de grupos.' },
  { id: 104, question: 'Ronaldo (Brasil) jugó la Final del Mundial 1998 pese a una misteriosa enfermedad la noche anterior. ¿Cuál fue el resultado?', options: ['Brasil ganó 1–0', 'Brasil empató 0–0 y ganó en penaltis', 'Francia ganó 3–0', 'Francia ganó 2–1 en la prórroga'], answer: 2, fact: 'Francia ganó 3–0 con dos goles de cabeza de Zidane. Ronaldo jugó pese a su estado y las circunstancias nunca se explicaron del todo.' },
  { id: 105, question: 'La "Vergüenza de Gijón" de 1982 hizo que Alemania Occidental y Austria jugaran un resultado que eliminó a Argelia. ¿Qué cambio de reglas trajo?', options: ['Tarjetas amarillas más duras', 'Los últimos partidos de grupo se juegan simultáneamente', 'Se introdujo la diferencia de goles', 'Se introdujo el gol de visitante'], answer: 1, fact: 'Desde 1986, todos los partidos finales de grupo son simultáneos para evitar la colusión. El 1–0 a favor de Alemania les beneficiaba a ambos.' },
  { id: 106, question: 'Carlos Alberto Torres marcó el legendario cuarto gol de Brasil en la Final del Mundial 1970. ¿Quién hizo el último pase?', options: ['Jairzinho', 'Tostão', 'Rivelino', 'Pelé'], answer: 3, fact: 'El pase perfecto de Pelé envió a Carlos Alberto en tromba para rematar con un cañonazo y sellar el 4–1 sobre Italia.' },

  // PORTEROS
  { id: 107, question: '¿Qué portero italiano estuvo 517 minutos sin encajar, un récord mundialista, en el Mundial de 1990?', options: ['Giovanni Galli', 'Walter Zenga', 'Dino Zoff', 'Gianluigi Buffon'], answer: 1, fact: 'La racha de Zenga acabó cuando Caniggia de Argentina le marcó de cabeza en la semifinal.' },
  { id: 108, question: '¿Quién ganó el Guante de Oro del Mundial 2002, siendo el único portero en ganar el Balón de Oro?', options: ['Brad Friedel', 'Gianluigi Buffon', 'Oliver Kahn', 'Rüştü Reçber'], answer: 2, fact: 'Kahn fue sobresaliente en todo el torneo, pero cometió un error clave en la final. Es el único portero en ganar el Balón de Oro.' },
  { id: 109, question: '¿Qué portero fue el héroe de Inglaterra en 1966, manteniendo 3 porterías a cero en las rondas eliminatorias?', options: ['Peter Bonetti', 'Gordon Banks', 'Ron Springett', 'Alex Stepney'], answer: 1, fact: 'Banks encajó solo 3 goles en todo el torneo y era ampliamente considerado el mejor portero del mundo.' },
  { id: 110, question: '¿Qué portero usó una hoja de trucos con los lanzadores de penaltis para parar dos tandas ante Argentina en los cuartos del Mundial 2006?', options: ['Oliver Kahn', 'Jens Lehmann', 'Robert Enke', 'Andreas Köpke'], answer: 1, fact: 'Lehmann paró a Ayala y Cambiasso con las notas de su entrenador de porteros, clasificando a Alemania para las semifinales.' },

  // BALONES OFICIALES
  { id: 111, question: '¿Qué empresa ha suministrado todos los balones oficiales de la Copa del Mundo FIFA desde 1970?', options: ['Nike', 'Puma', 'Adidas', 'Umbro'], answer: 2, fact: 'Adidas es proveedor oficial del balón mundialista desde el Telstar de 1970, el icónico diseño en blanco y negro sinónimo del fútbol.' },
  { id: 112, question: '¿Cómo se llamaba el balón oficial del Mundial de Sudáfrica 2010, criticado por los porteros por su vuelo imprevisible?', options: ['Tango', 'Jabulani', 'Brazuca', 'Al Rihla'], answer: 1, fact: 'La trayectoria errática del Jabulani desconcertó a los porteros, incluido Robert Green de Inglaterra, que lo dejó escapar ante EE. UU.' },
  { id: 113, question: '¿Qué significa "Al Rihla", el balón oficial del Mundial de Catar 2022, en árabe?', options: ['El Sueño', 'El Viaje', 'La Estrella', 'El Futuro'], answer: 1, fact: '"Al Rihla" (el viaje) fue el balón mundialista más veloz jamás probado, diseñado por Adidas con materiales sostenibles.' },
  { id: 114, question: '¿Cuál fue el balón oficial del Mundial de Brasil 2014?', options: ['Jabulani', 'Tango', 'Brazuca', 'Telstar'], answer: 2, fact: '"Brazuca" (jerga brasileña para "estilo de vida brasileño") fue elogiado por los jugadores por su regularidad.' },

  // MÁS APODOS Y COLORES
  { id: 115, question: 'La selección italiana se llama "Gli Azzurri". ¿Qué significa Azzurri?', options: ['Los Verdes', 'Los Azules', 'Los Rojos', 'Los Blancos'], answer: 1, fact: 'Azzurri significa "Los Azules". Italia viste de azul desde 1911, inspirado en el color real de la Casa de Saboya.' },
  { id: 116, question: '¿Cuál es el apodo más conocido de la selección española?', options: ['La Albiceleste', 'La Roja', 'Los Blancos', 'Los Matadores'], answer: 1, fact: '"La Roja" o "La Furia Roja": la camiseta roja tradicional de España se ha vuelto icónica desde su era dominante de 2008–2012.' },
  { id: 117, question: '¿Cuál es el apodo de la selección francesa de fútbol?', options: ['Les Bleus', 'Les Tricolores', 'Les Coqs', 'Les Gallois'], answer: 0, fact: '"Les Bleus" (Los Azules): la camiseta local de Francia es tradicionalmente azul, del tricolor francés.' },
  { id: 118, question: '¿Cuál es el apodo de la selección inglesa, derivado de su escudo?', options: ['Los Toros', 'Los Dragones Rojos', 'Los Tres Leones', 'Los Santos'], answer: 2, fact: 'Tres leones figuran en el escudo de Inglaterra desde el siglo XII, el mismo símbolo usado por Ricardo I de Inglaterra.' },
  { id: 119, question: '¿Cuál es el apodo de la selección de Países Bajos?', options: ['Het Elftal', 'Oranje', 'De Vlammen', 'Tulpen'], answer: 1, fact: '"Oranje" (Naranja): Países Bajos viste el color nacional, proveniente de la Casa Real de Orange-Nassau.' },
  { id: 120, question: '¿Cuál es el apodo de la selección de Portugal?', options: ['Os Verdes', 'A Seleção das Quinas', 'Os Navegadores', 'A Fúria Lusitana'], answer: 1, fact: '"A Seleção das Quinas" (La Selección de los Escudetes): las quinas son los cinco escudos del escudo de armas portugués.' },

  // HISTORIA DEL FORMATO
  { id: 121, question: '¿Cuántos equipos participaron en el primer Mundial de 1930?', options: ['10', '13', '16', '18'], answer: 1, fact: 'Solo 13 naciones tomaron parte en el primer Mundial: la mayoría de los equipos europeos rechazaron el largo viaje en barco a Uruguay.' },
  { id: 122, question: '¿En qué año se amplió el Mundial a 24 equipos?', options: ['1974', '1978', '1982', '1986'], answer: 2, fact: 'España 1982 fue el primer Mundial con 24 equipos, frente a los 16 anteriores, e introdujo la segunda fase de grupos.' },
  { id: 123, question: '¿En qué año se amplió el Mundial a 32 equipos?', options: ['1990', '1994', '1998', '2002'], answer: 2, fact: 'Francia 1998 fue el primer Mundial de 32 equipos, formato que se mantuvo hasta 2022.' },
  { id: 124, question: '¿Cuántos partidos se disputan en un Mundial estándar de 32 equipos?', options: ['56', '60', '64', '68'], answer: 2, fact: '64 partidos: 48 en fase de grupos + 8 en octavos + 4 en cuartos + 2 en semifinales + 1 tercer puesto + 1 final.' },
  { id: 125, question: '¿Qué continente ha producido más campeones del mundo?', options: ['América del Sur', 'Europa', 'Iguales — 6 cada uno', 'América del Norte'], answer: 1, fact: 'Europa ha ganado 12 títulos (Alemania 4, Italia 4, Francia 2, Inglaterra 1, España 1) frente a los 10 de América del Sur (Brasil 5, Argentina 3, Uruguay 2).' },
  { id: 126, question: '¿De qué grupo de continentes ningún equipo ha ganado jamás un Mundial?', options: ['América del Norte', 'África', 'Asia', 'Los tres anteriores'], answer: 3, fact: 'Ningún equipo de África, Asia o América del Norte/Central ha ganado el Mundial, aunque 2026 le da a América del Norte su primera oportunidad real.' },

  // DISCIPLINA Y RÉCORDS
  { id: 127, question: '¿Quién recibió la primera tarjeta roja de la historia del Mundial, en 1974?', options: ['Carlos Caszely (Chile)', 'Johan Cruyff (Países Bajos)', 'Franz Beckenbauer (Alemania Occidental)', 'Gerd Müller (Alemania Occidental)'], answer: 0, fact: 'Carlos Caszely de Chile fue el primer expulsado de la historia del Mundial, ante Alemania Occidental.' },
  { id: 128, question: 'Tras el defensivo Italia \'90, ¿qué cambio llegó en 1992 para mejorar el juego ofensivo?', options: ['Se introdujeron 3 puntos por victoria', 'Regla del pase atrás (los porteros no pueden coger pases deliberados con el pie)', 'Regla del gol de oro', 'Se relajó la regla del fuera de juego'], answer: 1, fact: 'Tras el fútbol defensivo de Italia \'90 (2,21 goles/partido), la FIFA introdujo la regla del pase atrás en 1992.' },
  { id: 129, question: '¿Qué edición del Mundial introdujo 3 puntos por victoria en lugar de 2?', options: ['1990 Italia', '1994 EE. UU.', '1998 Francia', '2002 Corea/Japón'], answer: 1, fact: 'EE. UU. 1994 introdujo los 3 puntos por victoria, animando a los equipos a buscar el triunfo en vez de conformarse con el empate.' },

  // RÉCORDS EN PARTIDOS
  { id: 130, question: '¿Cuál es el récord de goles en un solo partido del Mundial?', options: ['10 (Hungría 10-1 El Salvador)', '11 (Hungría 8-3 Alemania Occidental)', '12 (Austria 7-5 Suiza)', '9 (Yugoslavia 9-0 Zaire)'], answer: 2, fact: 'Austria vs Suiza en 1954 produjo 12 goles (7–5), todavía el partido más goleador de la historia del Mundial.' },
  { id: 131, question: 'Yugoslavia vs Zaire acabó 9–0 en el Mundial de 1974. ¿Qué importancia tiene ese partido?', options: ['Primer equipo africano en el Mundial', 'Segunda mayor diferencia de goles en la historia del Mundial', 'Primer partido del Mundial con tarjeta roja', 'Récord de goles en propia puerta en un partido'], answer: 1, fact: 'El 9–0 es la segunda mayor diferencia de goles en la historia del Mundial, por detrás del 10–1 de Hungría a El Salvador en 1982.' },

  // HISTORIA DE LA FIFA
  { id: 132, question: '¿Cuándo se fundó la FIFA, el organismo rector del fútbol mundial?', options: ['1896', '1900', '1904', '1912'], answer: 2, fact: 'La FIFA se fundó el 21 de mayo de 1904 en París con representantes de Francia, Bélgica, Dinamarca, Países Bajos, España, Suecia y Suiza.' },
  { id: 133, question: '¿Dónde tiene su sede la FIFA?', options: ['Ginebra', 'Zúrich', 'Berna', 'Basilea'], answer: 1, fact: 'La FIFA tiene su sede en Zúrich (Suiza) desde su fundación. La moderna Casa FIFA se inauguró en 2007.' },
  { id: 134, question: '¿Qué presidente de la FIFA impulsó la creación del Mundial y dio su nombre al trofeo original?', options: ['Sepp Blatter', 'João Havelange', 'Jules Rimet', 'Gianni Infantino'], answer: 2, fact: 'Jules Rimet (presidente de la FIFA 1921–1954) fue el artífice del Mundial; el primer trofeo lleva su nombre en su honor.' },

  // CULTURA E INNOVACIÓN
  { id: 135, question: '¿Qué instrumento ruidoso se asoció al Mundial de Sudáfrica 2010?', options: ['Tambores de acero', 'Vuvuzela', 'Djembe', 'Maracas'], answer: 1, fact: 'La vuvuzela, un largo cuerno de plástico, dominó todos los partidos en Sudáfrica, dividiendo a aficionados y medios de comunicación.' },
  { id: 136, question: '¿Con qué selección se asocia el cántico "Football\'s Coming Home"?', options: ['Australia', 'EE. UU.', 'Inglaterra', 'Escocia'], answer: 2, fact: '"Three Lions" de Baddiel, Skinner y Lightning Seeds fue el himno de Inglaterra en la Euro 96 y se revive en cada gran torneo.' },
  { id: 137, question: '¿En qué año se permitieron por primera vez los cambios en los partidos del Mundial?', options: ['1958', '1962', '1966', '1970'], answer: 3, fact: 'Los cambios se introdujeron en el Mundial de México 1970; en el de 1966 los jugadores lesionados tenían que seguir o abandonar el campo.' },
  { id: 138, question: '¿Cuántos cambios por equipo se permiten en un partido del Mundial desde 2022?', options: ['3', '4', '5', '6'], answer: 2, fact: 'Se permiten 5 cambios por equipo desde el Mundial 2022, una medida que se probó durante la pandemia de COVID-19.' },
  { id: 139, question: 'El Trofeo Jules Rimet fue robado en Inglaterra antes del Mundial de 1966 y lo encontró un perro. ¿Cómo se llamaba el perro?', options: ['Rover', 'Pickles', 'Buster', 'Bobby'], answer: 1, fact: 'Un perro mestizo llamado Pickles encontró el trofeo envuelto en papel de periódico bajo un seto en el sur de Londres, convirtiéndose en héroe nacional.' },

  // RÉCORDS DE JUGADORES
  { id: 140, question: '¿Qué jugador disputó más finales del Mundial (3)?', options: ['Pelé', 'Cafu', 'Ronaldo (Brasil)', 'Miroslav Klose'], answer: 1, fact: 'Cafu disputó tres finales mundialistas con Brasil: 1994 (ganó), 1998 (perdió) y 2002 (ganó), un récord sin igual.' },
  { id: 141, question: '¿Quién es el único jugador que marcó en todos los partidos de un mismo Mundial?', options: ['Pelé', 'Gerd Müller', 'Jairzinho', 'Just Fontaine'], answer: 2, fact: 'Jairzinho marcó en los 6 partidos de Brasil en el Mundial de 1970, una hazaña que nunca se ha repetido.' },
  { id: 142, question: 'Miroslav Klose marcó goles mundialistas en cuatro torneos consecutivos. ¿En qué años?', options: ['1998, 2002, 2006, 2010', '2002, 2006, 2010, 2014', '2006, 2010, 2014, 2018', '2002, 2006, 2010, 2018'], answer: 1, fact: 'Klose marcó en 2002, 2006, 2010 y 2014 con Alemania, ganando el oro en 2014 y el bronce en 2006 y 2010.' },
  { id: 143, question: '¿En cuántos Mundiales participó Lionel Messi a lo largo de su carrera?', options: ['3', '4', '5', '6'], answer: 3, fact: 'Messi jugó en 2006, 2010, 2014, 2018, 2022 y 2026 — seis Mundiales en total, ganando en Catar 2022.' },
  { id: 144, question: '¿Qué legendario jugador holandés NO participó en el Mundial 1978, pese a que Países Bajos llegó a la final?', options: ['Ruud Gullit', 'Marco van Basten', 'Johan Cruyff', 'Dennis Bergkamp'], answer: 2, fact: 'Cruyff se negó a viajar tras un intento de secuestro en su domicilio en 1977. Países Bajos llegó a la final sin él y perdió ante Argentina.' },
  { id: 145, question: 'Zinedine Zidane jugó tres Mundiales. ¿Cuáles?', options: ['1994, 1998, 2002', '1998, 2002, 2006', '2002, 2006, 2010', '1994, 2002, 2006'], answer: 1, fact: 'Zidane jugó en 1998 (ganó), 2002 (eliminado en grupos) y 2006 (final, expulsado). Sus dos goles de cabeza en el \'98 son icónicos.' },
  { id: 146, question: '¿Quién fue el jugador de más edad en disputar un partido del Mundial?', options: ['Roger Milla', 'Essam El-Hadary', 'Faryd Mondragón', 'Peter Shilton'], answer: 1, fact: 'El egipcio Essam El-Hadary jugó frente a Arabia Saudí en el Mundial 2018 con 45 años y 161 días, un récord vigente.' },
  { id: 147, question: '¿Quién fue el jugador más joven en disputar un partido del Mundial?', options: ['Pelé', 'Rubén Marcos', 'Norman Whiteside', 'Cesc Fàbregas'], answer: 2, fact: 'El norirlandés Norman Whiteside jugó ante Yugoslavia en 1982 con solo 17 años y 41 días, más joven que Pelé en 1958.' },
  { id: 148, question: '¿Quién fue el jugador más joven en marcar en una Final del Mundial?', options: ['Pelé', 'Ronaldo (Brasil)', 'Kylian Mbappé', 'Vavá'], answer: 0, fact: 'Pelé marcó en la Final del Mundial 1958 con 17 años y 249 días, el gol más joven en cualquier final mundialista.' },
  { id: 149, question: 'Lionel Messi ganó el Balón de Oro en el Mundial 2014 pese a que Argentina perdió la final. ¿Contra quién?', options: ['Brasil', 'Francia', 'Alemania', 'Países Bajos'], answer: 2, fact: 'Alemania venció a Argentina 1–0 con el gol de Götze en la prórroga. El Balón de Oro a Messi fue polémico.' },
  { id: 150, question: 'Italia se ausentó del Mundial 2018, la primera vez desde qué año?', options: ['1950', '1954', '1958', '1966'], answer: 2, fact: 'Italia no se clasificó por última vez en 1958. Su ausencia en Rusia 2018 rompió una racha de 60 años de participaciones consecutivas.' },

  // PRIMEROS PARTIDOS E HITOS
  { id: 151, question: '¿Qué selecciones jugaron el primer partido de la historia del Mundial, el 13 de julio de 1930?', options: ['Uruguay vs Argentina', 'Francia vs México', 'EE. UU. vs Bélgica', 'Brasil vs Bolivia'], answer: 1, fact: 'Francia vs México fue el primer partido mundialista. Francia ganó 4–1 y Lucien Laurent marcó el primer gol de la historia del Mundial.' },
  { id: 152, question: '¿Quién marcó el primer gol de la historia del Mundial?', options: ['Manuel Rosas', 'Héctor Scarone', 'Lucien Laurent', 'Bert Patenaude'], answer: 2, fact: 'El francés Lucien Laurent marcó al minuto 19 ante México el 13 de julio de 1930, el primer gol mundialista de la historia.' },
  { id: 153, question: '¿Quién marcó dos goles para Ecuador ante los anfitriones en el partido inaugural del Mundial de Catar 2022?', options: ['Romario Ibarra', 'Enner Valencia', 'Félix Torres', 'Pervis Estupiñán'], answer: 1, fact: 'Enner Valencia anotó dos veces en la victoria 2–0 de Ecuador. Catar fue el primer anfitrión en perder su partido inaugural.' },
  { id: 154, question: 'La primera tanda de penaltis de la historia del Mundial se disputó en 1982. ¿Qué selecciones participaron?', options: ['Brasil vs Italia', 'Alemania Occidental vs Francia', 'Inglaterra vs España', 'Argentina vs Países Bajos'], answer: 1, fact: 'Alemania Occidental venció a Francia 5–4 en Sevilla, la primera tanda mundialista, recordada como "La Noche de Sevilla".' },
  { id: 155, question: '¿Quién marcó el primer gol de oro de la historia del Mundial, eliminando a Paraguay en 1998?', options: ['Thierry Henry', 'David Trezeguet', 'Laurent Blanc', 'Youri Djorkaeff'], answer: 2, fact: 'Laurent Blanc cabeceó el gol de oro de Francia ante Paraguay en los octavos, el primer partido mundialista decidido así.' },

  // PREMIOS Y MÁS MASCOTAS
  { id: 156, question: '¿Qué galardón se entrega al mejor jugador del Mundial?', options: ['Balón de Oro', 'Bota de Oro', 'Premio Platino', 'Premio FIFA al Jugador'], answer: 0, fact: 'El Balón de Oro se entrega desde 1930. Messi lo ha ganado dos veces (2014, 2022). Ronaldo nunca lo ha ganado.' },
  { id: 157, question: '¿Cuál fue la mascota del Mundial de Alemania 2006?', options: ['Goleo VI', 'Zakumi', 'Striker', 'Ciao'], answer: 0, fact: 'Goleo VI era un león con la camiseta de Alemania acompañado de un balón parlante llamado Pille, nombre que combina "goal" y "leo" (león).' },
  { id: 158, question: '¿Cómo se llamaban colectivamente las tres mascotas futuristas del Mundial 2002?', options: ['Los Zubizarri', 'Los Spheriks', 'Los Triblasts', 'Los Futuro'], answer: 1, fact: 'Ato, Kaz y Nik, conocidos colectivamente como los Spheriks, fueron las mascotas alienígenas del Mundial de Japón/Corea del Sur 2002.' },
  { id: 159, question: 'Ciao, la mascota del Mundial de 1990, era una figura geométrica. ¿Con qué forma estaba construido su cuerpo?', options: ['Círculos y triángulos', 'Cubos de colores apilados como figura de palitos', 'Forma de balón', 'Forma de bota italiana'], answer: 1, fact: 'Ciao era una figura de palitos construida con cubos de diferentes colores, una de las mascotas mundialistas más abstractas y memorables.' },
  { id: 160, question: '¿Qué animal era Pique, la mascota del Mundial de México 1986?', options: ['Un águila', 'Un jaguar', 'Un chile jalapeño', 'Un armadillo'], answer: 2, fact: 'Pique era un simpático chile jalapeño con sombrero y equipación de fútbol mexicana, perfectamente representativo del espíritu de México.' },

  // SEDES DE LAS FINALES
  { id: 161, question: '¿Dónde se jugó la Final del Mundial de 1994?', options: ['Giants Stadium, Nueva Jersey', 'Rose Bowl, Pasadena', 'Stanford Stadium, San Francisco', 'Silverdome, Detroit'], answer: 1, fact: 'El Rose Bowl de Pasadena (California) albergó la final de 1994 entre Brasil e Italia ante 94.194 espectadores.' },
  { id: 162, question: '¿En qué ciudad se disputó la Final del Mundial de 2006?', options: ['Múnich', 'Hamburgo', 'Fráncfort', 'Berlín'], answer: 3, fact: 'El Olympiastadion de Berlín acogió la final de 2006, el polémico cabezazo de Zidane a Materazzi.' },
  { id: 163, question: '¿Dónde se disputó la Final del Mundial de 2018?', options: ['San Petersburgo', 'Moscú', 'Sochi', 'Kazán'], answer: 1, fact: 'El estadio Luzhniki de Moscú acogió la final de 2018: Francia venció a Croacia 4–2.' },
  { id: 164, question: '¿Dónde se disputó la Final del Mundial 2014 entre Alemania y Argentina?', options: ['São Paulo', 'Salvador', 'Brasilia', 'Río de Janeiro'], answer: 3, fact: 'El icónico Maracaná de Río acogió la final de 2014: Alemania ganó 1–0 con el gol de Götze en la prórroga.' },
  { id: 165, question: '¿En qué ciudad se disputó la Final del Mundial de 1966?', options: ['Mánchester', 'Birmingham', 'Liverpool', 'Londres'], answer: 3, fact: 'El estadio de Wembley en Londres albergó la final de 1966: Inglaterra venció a Alemania Occidental 4–2 ante 98.000 espectadores.' },

  // HISTORIA DE TANDAS Y ASISTENCIA
  { id: 166, question: '¿En qué Mundial se introdujeron las tandas de penaltis para resolver los empates en eliminatoria?', options: ['1966 Inglaterra', '1970 México', '1974 Alemania Occidental', '1978 Argentina'], answer: 2, fact: 'Las tandas se introdujeron en el reglamento del Mundial de 1974, aunque la primera se disputó realmente en un partido en 1982.' },
  { id: 167, question: 'En la primera tanda de penaltis mundialista (1982), ¿a qué selección venció Alemania Occidental?', options: ['Brasil', 'Francia', 'Inglaterra', 'España'], answer: 1, fact: 'Alemania Occidental venció a Francia 5–4 en Sevilla. El partido es recordado también por la brutal falta de Schumacher a Battiston.' },
  { id: 168, question: '¿Qué partido del Mundial tiene el récord mundial de asistencia de fútbol en vivo (~199.854)?', options: ['1970 México vs Brasil', '1950 Brasil vs Uruguay', '1966 Inglaterra vs Alemania Occidental', '1986 Argentina vs Alemania Occidental'], answer: 1, fact: 'El Maracanazo de 1950 (Brasil vs Uruguay) congregó a ~200.000 aficionados, la mayor multitud de la historia del fútbol.' },

  // MÁS HISTORIA
  { id: 169, question: '¿Qué Mundial fue el primero emitido en color en todo el mundo?', options: ['1966 Inglaterra', '1970 México', '1974 Alemania Occidental', '1978 Argentina'], answer: 1, fact: 'México 1970 fue el primer Mundial emitido en color a nivel global, revolucionando cómo vivían el fútbol los aficionados de todo el mundo.' },
  { id: 170, question: '¿Qué cambio de reglas siguió a la "Vergüenza de Gijón" de 1982?', options: ['Grupos más grandes', 'Los últimos partidos de grupo se juegan simultáneamente', 'Regla del gol de visitante introducida', 'Diferencia de goles modificada'], answer: 1, fact: 'Desde 1986, todos los partidos finales de grupo son simultáneos para evitar que los equipos acuerden un resultado conveniente.' },
  { id: 171, question: '¿En qué mes se celebró el Mundial de 2022 por primera vez, debido al extremo calor veraniego de Catar?', options: ['Septiembre', 'Octubre', 'Noviembre', 'Enero'], answer: 2, fact: 'Catar 2022 se disputó en noviembre-diciembre, el primer Mundial no celebrado en junio/julio desde el inaugural de Uruguay en 1930.' },
  { id: 172, question: '¿Cuántos goles marcó Kylian Mbappé en el Mundial de 2022, ganando la Bota de Oro a los 23 años?', options: ['6', '7', '8', '9'], answer: 2, fact: 'Mbappé anotó 8 goles, incluido un hat-trick en la final, ganando la Bota de Oro y convirtiéndose en el gran héroe de Francia pese a la derrota.' },
  { id: 173, question: '¿Cuál fue el marcador de la Final del Mundial de 1954 —el "Milagro de Berna"— entre Alemania Occidental y Hungría?', options: ['2-0', '3-1', '3-2', '4-2'], answer: 2, fact: 'Alemania Occidental remontó de 0–2 para ganar 3–2, considerado un momento definitorio de la Alemania de posguerra.' },
  { id: 174, question: 'La victoria de Argentina en el Mundial 2022 rompió una sequía de 36 años desde su título anterior. ¿En qué año fue ese?', options: ['1978', '1982', '1986', '1990'], answer: 2, fact: 'Los títulos de Argentina en 1986 (era Maradona) y 2022 (era Messi) están separados por 36 años, el mayor intervalo entre títulos.' },
  { id: 175, question: '¿Qué país ha acogido el Mundial más veces (dos, y una tercera en 2026)?', options: ['Brasil', 'Alemania', 'México', 'Francia'], answer: 2, fact: 'México organizó el torneo en 1970 y 1986, y será coanfitrión en 2026, el único país que acogerá tres Mundiales.' },
  { id: 176, question: 'El actual trofeo de la Copa del Mundo FIFA es de oro macizo de 18 quilates. ¿Cuánto pesa?', options: ['4,2 kg', '6,1 kg', '8,5 kg', '10,0 kg'], answer: 1, fact: 'El trofeo pesa 6,175 kg y mide 36,8 cm de altura, diseñado por el escultor italiano Silvio Gazzaniga y entregado por primera vez en 1974.' },
  { id: 177, question: '¿En qué Mundial se introdujo la tecnología de línea de gol por primera vez?', options: ['2010 Sudáfrica', '2014 Brasil', '2018 Rusia', '2022 Catar'], answer: 1, fact: 'Brasil 2014 introdujo la tecnología Hawk-Eye de línea de gol, junto con el espray desvanecedor para las faltas.' },
  { id: 178, question: '¿Qué equipo marcó el mayor número de goles en un solo torneo mundialista (27 goles en 5 partidos)?', options: ['Brasil 1970', 'Hungría 1954', 'Alemania Occidental 1954', 'Francia 1958'], answer: 1, fact: 'Hungría anotó 27 goles en 5 partidos en el Mundial de 1954 (5,4 goles/partido) y aun así perdió la final ante Alemania Occidental.' },
  { id: 179, question: '¿Quién debutó en el Mundial a los 17 años en 1958 y acabó ganándolo tres veces?', options: ['Ronaldo (Brasil)', 'Garrincha', 'Pelé', 'Rivaldo'], answer: 2, fact: 'Pelé debutó a los 17 años en 1958 (ganándolo), luego en 1962 y 1970, el único jugador en ganar el Mundial tres veces.' },
  { id: 180, question: '¿En qué Mundial se aplicó por primera vez la regla del pase atrás (los porteros no pueden recoger pases deliberados con el pie)?', options: ['1990 Italia', '1992 Eurocopa', '1994 EE. UU.', '1998 Francia'], answer: 2, fact: 'La regla del pase atrás la introdujo la FIFA en 1992, por lo que EE. UU. 1994 fue el primer Mundial jugado con ella.' },

  // MUNDIAL 2026 Y CULTURA
  { id: 181, question: '¿Cuántas ciudades de EE. UU. acogerán partidos del Mundial 2026?', options: ['8', '10', '11', '12'], answer: 1, fact: '10 ciudades de EE. UU. (Nueva York/NJ, LA, Dallas, Miami, San Francisco, Seattle, Boston, Filadelfia, Kansas City, Atlanta) más 3 en Canadá y 3 en México.' },
  { id: 182, question: '¿Qué ciudades canadienses acogerán partidos del Mundial 2026?', options: ['Montreal y Ottawa', 'Toronto y Vancouver', 'Calgary y Edmonton', 'Solo Toronto'], answer: 1, fact: 'Toronto (BMO Field) y Vancouver (BC Place) son las dos ciudades canadienses sede del Mundial 2026.' },
  { id: 183, question: 'El Mundial 2022 fue el más compacto de la historia: todos los estadios estaban a menos de cuántos km de Doha?', options: ['30 km', '55 km', '80 km', '120 km'], answer: 1, fact: 'Todos los estadios del Mundial 2022 estaban a menos de 55 km de Doha, permitiendo por primera vez asistir a varios partidos al día.' },

  // GOLES FAMOSOS Y JUGADORES
  { id: 184, question: '¿En qué partido mundialista debutó Michael Owen, de 17 años, con un gol individual que lo lanzó a la fama?', options: ['Inglaterra vs Colombia 1998', 'Inglaterra vs Argentina 1998', 'Inglaterra vs Alemania 2002', 'Inglaterra vs Brasil 2002'], answer: 1, fact: 'La carrera y el gol de Owen ante Argentina en los octavos de 1998 le presentó al mundo, aunque Inglaterra perdió en los penaltis.' },
  { id: 185, question: 'Brasil encadenó 11 victorias mundialistas consecutivas entre 2002 y 2006. ¿Quién puso fin a la racha?', options: ['Alemania', 'Francia', 'Argentina', 'Ghana'], answer: 1, fact: 'Francia cortó la racha de 11 partidos de Brasil en los cuartos del Mundial 2006, ganando 1–0 con un gol de Thierry Henry.' },
  { id: 186, question: '¿Qué selección ganó el Mundial sin encajar ningún gol en las rondas eliminatorias de Francia 1998?', options: ['Brasil', 'Francia', 'Países Bajos', 'Alemania'], answer: 1, fact: 'Francia mantuvo la portería a cero en cada eliminatoria ante Paraguay, Italia (prórroga), Croacia y Brasil.' },

  // MÁS RÉCORDS Y CURIOSIDADES
  { id: 187, question: '¿Quién fue el máximo goleador del Mundial de Alemania 2006?', options: ['Thierry Henry', 'Miroslav Klose', 'Fernando Torres', 'Luca Toni'], answer: 1, fact: 'Klose marcó 5 goles en Alemania 2006, su tercer Mundial, camino del récord histórico que lograría en Brasil 2014.' },
  { id: 188, question: '¿Qué edición del Mundial es famosa por la "Batalla de Santiago", el partido más violento de la historia?', options: ['1958 Suecia', '1962 Chile', '1966 Inglaterra', '1974 Alemania Occidental'], answer: 1, fact: 'El partido Italia vs Chile de 1962 tuvo 2 expulsiones, peleas y policías en el campo. David Coleman de la BBC lo calificó de "el partido más vergonzoso de la historia del Mundial".' },
  { id: 189, question: '¿Qué selección sudamericana llegó a las semifinales en 2018 y en 2022?', options: ['Colombia', 'Ecuador', 'Uruguay', 'Croacia'], answer: 3, fact: 'Croacia llegó a la final de 2018 (perdió 4–2 ante Francia) y a las semifinales de 2022 (perdió ante Argentina), notable para un país de 4 millones.' },
  { id: 190, question: '¿En qué Mundial que ganó Pelé no pudo jugar la final por lesión?', options: ['1958', '1962', '1970', 'Jugó todas las finales'], answer: 1, fact: 'Pelé se lesionó en la fase de grupos del Mundial de 1962 y se perdió la final: Brasil ganó igualmente 3–1 a Checoslovaquia.' },
  { id: 191, question: '¿Qué selección tiene el mayor número de victorias (partidos ganados) en la historia del Mundial?', options: ['Italia', 'Argentina', 'Brasil', 'Alemania'], answer: 2, fact: 'Brasil ha ganado más partidos mundialistas que ninguna otra nación, habiendo participado en las 22 ediciones y llegando siempre lejos.' },
  { id: 192, question: '¿Qué edición del Mundial fue la primera en utilizar un estadio con todas las localidades sentadas para la final?', options: ['1966 Inglaterra', '1974 Alemania Occidental', '1990 Italia', '1994 EE. UU.'], answer: 2, fact: 'El Estadio Olímpico de Roma fue completamente de asientos para la final de 1990, parte de las mejoras de Italia como anfitrión.' },
  { id: 193, question: 'Cafu disputó TRES finales mundialistas con Brasil. ¿Cuántas ganó?', options: ['1 (1994)', '1 (2002)', '2 (1994 y 2002)', 'Ninguna'], answer: 2, fact: 'Cafu ganó en 1994 y 2002, y perdió la final de 1998 ante Francia. Ningún otro jugador ha disputado tres finales mundialistas.' },
  { id: 194, question: '¿Qué leyenda alemana marcó 14 goles mundialistas, récord hasta que Klose le superó en 2014?', options: ['Franz Beckenbauer', 'Karl-Heinz Rummenigge', 'Gerd Müller', 'Rudi Völler'], answer: 2, fact: '"Der Bomber" Gerd Müller marcó 14 goles mundialistas con Alemania Occidental en 1970 y 1974; su récord duró 40 años.' },
  { id: 195, question: '¿En qué Mundial Ronaldinho, entonces el mejor jugador del mundo, tuvo un bajo rendimiento y fue eliminado pronto?', options: ['2002', '2006', '2010', '2014'], answer: 1, fact: 'Ronaldinho y Brasil cayeron en los cuartos del Mundial 2006 ante Francia. Su falta de forma fue una de las mayores decepciones del torneo.' },
  { id: 196, question: '¿Qué país tiene al fútbol como deporte nacional pero jamás se ha clasificado para el Mundial?', options: ['Groenlandia', 'Kosovo', 'Gibraltar', 'Islas Feroe'], answer: 0, fact: 'La asociación de fútbol de Groenlandia no está afiliada a la FIFA, lo que le impide clasificarse pese a la popularidad del fútbol allí.' },
  { id: 197, question: '¿En qué Mundial no participó Argentina, la única vez en su historia?', options: ['1930', '1934', '1938', 'Ha participado en todos'], answer: 2, fact: 'Argentina se ausentó del Mundial de 1938 en Francia, protestando porque Sudamérica debía ser de nuevo la sede. Ha asistido a todas las demás ediciones.' },
  { id: 198, question: '¿Cuántas veces ha llegado México a los cuartos de final del Mundial?', options: ['1', '2', '3', '4'], answer: 1, fact: 'México llegó a cuartos en 1970 y 1986, ambas como anfitrión. Cayó en los octavos en seis Mundiales consecutivos (1994–2018).' },
  { id: 199, question: '¿Qué Final del Mundial es la única que terminó sin goles en el tiempo reglamentario ni en la prórroga?', options: ['1990 Alemania Occidental vs Argentina', '1994 Brasil vs Italia', '2006 Italia vs Francia', '2022 Argentina vs Francia'], answer: 1, fact: 'La final de 1994 terminó 0–0 tras 120 minutos, la única final mundialista sin goles, y Brasil ganó 3–2 en la tanda.' },
  { id: 200, question: '¿Qué selección africana llegó por primera vez a las semifinales del Mundial en 2022?', options: ['Senegal', 'Camerún', 'Nigeria', 'Marruecos'], answer: 3, fact: 'Marruecos eliminó a España y Portugal de camino a las semifinales, el primer equipo africano en lograrlo.' },
  { id: 201, question: '¿Quién fue expulsado en el primer minuto de un partido mundialista, el rojo más rápido de la historia?', options: ['Zinedine Zidane', 'Luis Suárez', 'José Batista (Uruguay)', 'Giorgio Chiellini'], answer: 2, fact: 'José Batista de Uruguay fue expulsado a los 56 segundos ante Escocia en 1986, la expulsión más rápida de la historia del Mundial.' },
  { id: 202, question: '¿Qué afición es famosa por recoger siempre la basura tras sus partidos en los Mundiales?', options: ['Alemania', 'Japón', 'Corea del Sur', 'Brasil'], answer: 1, fact: 'Los aficionados japoneses son icónicos por quedarse al final de los partidos para limpiar su zona, tradición celebrada en todo el mundo.' },
  { id: 203, question: '¿Qué país anfitrión sufrió la mayor derrota en una semifinal del Mundial, cayendo 7–1 en 2014?', options: ['Argentina', 'Uruguay', 'Brasil', 'Colombia'], answer: 2, fact: 'Brasil perdió 7–1 ante Alemania en Belo Horizonte, el "Mineirazo". Alemania marcó 5 goles en 18 minutos, entre los minutos 23 y 29.' },
];
