export interface WCEdition {
  year: number;
  host: string;
  hostFlag: string;
  champion: string;
  championFlag: string;
  runnerUp: string;
  runnerUpFlag: string;
  finalScore: string;
  topScorer: string;
  topScorerGoals: number;
  topScorerCountry: string;
  teams: number;
  matches: number;
  goals: number;
  attendance: string;
  goldenBall?: string;
  goldenGlove?: string;
  mascot?: string;
  ball?: string;
  funFacts: string[];
}

export const WC_EDITIONS: WCEdition[] = [
  {
    year: 1930,
    host: 'Uruguay',
    hostFlag: '🇺🇾',
    champion: 'Uruguay',
    championFlag: '🇺🇾',
    runnerUp: 'Argentina',
    runnerUpFlag: '🇦🇷',
    finalScore: '4–2',
    topScorer: 'Guillermo Stábile',
    topScorerGoals: 8,
    topScorerCountry: '🇦🇷',
    teams: 13,
    matches: 18,
    goals: 70,
    attendance: '590,549',
    funFacts: [
      'The first World Cup — 13 nations competed, all invited by FIFA.',
      'European teams had to travel by ship for two weeks to reach Uruguay.',
      'The final was played at the brand-new Estadio Centenario in Montevideo.',
      'Uruguay and Argentina used different balls in each half — both claimed victory in their half.',
      'The Jules Rimet trophy was awarded for the first time.',
    ],
  },
  {
    year: 1934,
    host: 'Italy',
    hostFlag: '🇮🇹',
    champion: 'Italy',
    championFlag: '🇮🇹',
    runnerUp: 'Czechoslovakia',
    runnerUpFlag: '🇨🇿',
    finalScore: '2–1 (aet)',
    topScorer: 'Oldřich Nejedly',
    topScorerGoals: 5,
    topScorerCountry: '🇨🇿',
    teams: 16,
    matches: 17,
    goals: 70,
    attendance: '363,000',
    funFacts: [
      'First tournament to use a knock-out format from the start.',
      'Uruguay, the defending champions, boycotted in retaliation for Europe\'s absence in 1930.',
      'Vittorio Pozzo became the only manager to win two World Cups (1934 and 1938).',
      'Italy\'s win under Mussolini raised political controversy about pressure on referees.',
      'Brazil and Argentina were both eliminated in their opening matches.',
    ],
  },
  {
    year: 1938,
    host: 'France',
    hostFlag: '🇫🇷',
    champion: 'Italy',
    championFlag: '🇮🇹',
    runnerUp: 'Hungary',
    runnerUpFlag: '🇭🇺',
    finalScore: '4–2',
    topScorer: 'Leônidas',
    topScorerGoals: 7,
    topScorerCountry: '🇧🇷',
    teams: 15,
    matches: 18,
    goals: 84,
    attendance: '374,835',
    funFacts: [
      'Italy became back-to-back World Cup champions.',
      'Brazil\'s Leônidas was nicknamed "The Black Diamond" and scored 7 goals.',
      'Austria qualified but was absorbed into Germany before the tournament — their players joined the German squad.',
      'Spain was in the middle of its Civil War and couldn\'t participate.',
      'The next World Cup would not be held for 12 years due to World War II.',
    ],
  },
  {
    year: 1950,
    host: 'Brazil',
    hostFlag: '🇧🇷',
    champion: 'Uruguay',
    championFlag: '🇺🇾',
    runnerUp: 'Brazil',
    runnerUpFlag: '🇧🇷',
    finalScore: '2–1 (final group stage)',
    topScorer: 'Ademir',
    topScorerGoals: 9,
    topScorerCountry: '🇧🇷',
    teams: 13,
    matches: 22,
    goals: 88,
    attendance: '1,045,246',
    funFacts: [
      '"The Maracanazo" — Uruguay\'s 2–1 win over Brazil in front of ~200,000 fans at Maracanã remains one of sport\'s greatest upsets.',
      'The final was a round-robin "final pool," not a single knockout match.',
      'Scotland, India, and Turkey all withdrew before the tournament.',
      'England participated in the World Cup for the very first time — and lost to the USA 1–0.',
      'The shock Uruguay victory caused massive grief across Brazil; some fans reportedly died of heart attacks.',
    ],
  },
  {
    year: 1954,
    host: 'Switzerland',
    hostFlag: '🇨🇭',
    champion: 'West Germany',
    championFlag: '🇩🇪',
    runnerUp: 'Hungary',
    runnerUpFlag: '🇭🇺',
    finalScore: '3–2',
    topScorer: 'Sándor Kocsis',
    topScorerGoals: 11,
    topScorerCountry: '🇭🇺',
    teams: 16,
    matches: 26,
    goals: 140,
    attendance: '768,607',
    funFacts: [
      '"The Miracle of Bern" — West Germany defeated the unbeaten "Magnificent Magyars" of Hungary in the final.',
      'Hungary had beaten West Germany 8–3 in the group stage just weeks before.',
      'The tournament averaged 5.38 goals per game — the highest ever in World Cup history.',
      'Uruguay\'s match vs Hungary produced 4 red cards and a brawl; dubbed "The Battle of Bern."',
      'First World Cup to be televised.',
    ],
  },
  {
    year: 1958,
    host: 'Sweden',
    hostFlag: '🇸🇪',
    champion: 'Brazil',
    championFlag: '🇧🇷',
    runnerUp: 'Sweden',
    runnerUpFlag: '🇸🇪',
    finalScore: '5–2',
    topScorer: 'Just Fontaine',
    topScorerGoals: 13,
    topScorerCountry: '🇫🇷',
    funFacts: [
      'A 17-year-old Pelé became a sensation, scoring 6 goals including a hat-trick in the semi-final.',
      'Just Fontaine\'s 13 goals in one tournament is a record that still stands today.',
      'Vavá scored twice in the final to help Brazil win their first World Cup title.',
      'France finished 3rd — their best result until 1998.',
      'Brazil introduced the 4-2-4 formation that revolutionized football tactics.',
    ],
    teams: 16,
    matches: 35,
    goals: 126,
    attendance: '819,810',
  },
  {
    year: 1962,
    host: 'Chile',
    hostFlag: '🇨🇱',
    champion: 'Brazil',
    championFlag: '🇧🇷',
    runnerUp: 'Czechoslovakia',
    runnerUpFlag: '🇨🇿',
    finalScore: '3–1',
    topScorer: 'Garrincha / Vavá / Leonel Sánchez / Dražan Jerković',
    topScorerGoals: 4,
    topScorerCountry: '🌍',
    teams: 16,
    matches: 32,
    goals: 89,
    attendance: '893,172',
    funFacts: [
      'Brazil won back-to-back titles, becoming the first team to do so since Italy in 1934–38.',
      'Pelé was injured in the second group game and missed the rest of the tournament.',
      'Garrincha, "The Little Bird," was the tournament\'s outstanding player despite his bowed legs.',
      '"The Battle of Santiago" (Italy vs Chile) was so violent the BBC commentator called it "the most disgraceful exhibition of football."',
      'A magnitude 9.5 earthquake hit Chile the year before; hosting the tournament was a major achievement.',
    ],
  },
  {
    year: 1966,
    host: 'England',
    hostFlag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    champion: 'England',
    championFlag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    runnerUp: 'West Germany',
    runnerUpFlag: '🇩🇪',
    finalScore: '4–2 (aet)',
    topScorer: 'Eusébio',
    topScorerGoals: 9,
    topScorerCountry: '🇵🇹',
    mascot: 'World Cup Willie',
    teams: 16,
    matches: 32,
    goals: 89,
    attendance: '1,563,135',
    funFacts: [
      'England\'s only World Cup title — Geoff Hurst scored a hat-trick in the final.',
      'The famous "Wembley goal" — Hurst\'s third still divides opinion on whether it crossed the line.',
      'World Cup Willie became the first official World Cup mascot.',
      'North Korea knocked out Italy in the group stage — one of the biggest upsets ever.',
      'The Jules Rimet trophy was stolen and then found by a dog named Pickles.',
    ],
  },
  {
    year: 1970,
    host: 'Mexico',
    hostFlag: '🇲🇽',
    champion: 'Brazil',
    championFlag: '🇧🇷',
    runnerUp: 'Italy',
    runnerUpFlag: '🇮🇹',
    finalScore: '4–1',
    topScorer: 'Gerd Müller',
    topScorerGoals: 10,
    topScorerCountry: '🇩🇪',
    goldenBall: 'Pelé',
    mascot: 'Juanito',
    ball: 'Adidas Telstar',
    teams: 16,
    matches: 32,
    goals: 95,
    attendance: '1,603,975',
    funFacts: [
      'Brazil won their third title and kept the Jules Rimet trophy permanently.',
      'Widely considered the greatest World Cup ever — Pelé, Rivelino, Jairzinho, Tostão all in one squad.',
      'First World Cup shown in colour TV worldwide.',
      'The "Game of the Century" — Italy beat West Germany 4–3 in extra time in the semi-final.',
      'Jairzinho scored in every single game of the tournament — a unique feat.',
    ],
  },
  {
    year: 1974,
    host: 'West Germany',
    hostFlag: '🇩🇪',
    champion: 'West Germany',
    championFlag: '🇩🇪',
    runnerUp: 'Netherlands',
    runnerUpFlag: '🇳🇱',
    finalScore: '2–1',
    topScorer: 'Grzegorz Lato',
    topScorerGoals: 7,
    topScorerCountry: '🇵🇱',
    goldenBall: 'Johan Cruyff',
    mascot: 'Tip and Tap',
    ball: 'Adidas Telstar Durlast',
    teams: 16,
    matches: 38,
    goals: 97,
    attendance: '1,865,762',
    funFacts: [
      'Johan Cruyff\'s Netherlands introduced "Total Football" to the world.',
      'Netherlands reached the final without Cruyff in 1978 — he refused to go citing a kidnapping attempt.',
      'The current FIFA World Cup trophy was introduced for the first time.',
      'Pelé was absent — his Brazil squad was controversially eliminated in the second group stage.',
      'East Germany beat West Germany 1–0 in the group stage — the only time the two German states ever met.',
    ],
  },
  {
    year: 1978,
    host: 'Argentina',
    hostFlag: '🇦🇷',
    champion: 'Argentina',
    championFlag: '🇦🇷',
    runnerUp: 'Netherlands',
    runnerUpFlag: '🇳🇱',
    finalScore: '3–1 (aet)',
    topScorer: 'Mario Kempes',
    topScorerGoals: 6,
    topScorerCountry: '🇦🇷',
    goldenBall: 'Mario Kempes',
    mascot: 'Gauchito',
    ball: 'Adidas Tango',
    teams: 16,
    matches: 38,
    goals: 102,
    attendance: '1,545,791',
    funFacts: [
      'Argentina\'s first World Cup title, under military dictatorship — controversy surrounded the tournament.',
      'Mario Kempes, the tournament\'s top scorer, scored twice in the final.',
      'The ticker-tape paper storm at River Plate for Argentina\'s matches became iconic.',
      'Scotland\'s Archie Gemmill scored one of the greatest World Cup goals ever against the Netherlands.',
      'The tournament was held amid protests against Argentina\'s military junta government.',
    ],
  },
  {
    year: 1982,
    host: 'Spain',
    hostFlag: '🇪🇸',
    champion: 'Italy',
    championFlag: '🇮🇹',
    runnerUp: 'West Germany',
    runnerUpFlag: '🇩🇪',
    finalScore: '3–1',
    topScorer: 'Paolo Rossi',
    topScorerGoals: 6,
    topScorerCountry: '🇮🇹',
    goldenBall: 'Paolo Rossi',
    mascot: 'Naranjito',
    ball: 'Adidas Tango Español',
    teams: 24,
    matches: 52,
    goals: 146,
    attendance: '2,109,723',
    funFacts: [
      'Expanded to 24 teams for the first time.',
      'Paolo Rossi had returned from a 2-year ban for match-fixing and became the hero, scoring 6 goals in the final stages.',
      'Hungary beat El Salvador 10–1, the biggest winning margin in World Cup history.',
      '"Night of Shame" — West Germany and Austria played a 1–0 result that sent both through, with both teams happy with the score.',
      'Brazil\'s incredible attacking team (Zico, Sócrates, Falcão) was sensationally eliminated by Italy.',
    ],
  },
  {
    year: 1986,
    host: 'Mexico',
    hostFlag: '🇲🇽',
    champion: 'Argentina',
    championFlag: '🇦🇷',
    runnerUp: 'West Germany',
    runnerUpFlag: '🇩🇪',
    finalScore: '3–2',
    topScorer: 'Gary Lineker',
    topScorerGoals: 6,
    topScorerCountry: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    goldenBall: 'Diego Maradona',
    mascot: 'Pique',
    ball: 'Adidas Azteca',
    teams: 24,
    matches: 52,
    goals: 132,
    attendance: '2,394,031',
    funFacts: [
      'Diego Maradona\'s tournament — the "Hand of God" goal and the "Goal of the Century" came in the same match vs England.',
      'The Goal of the Century was voted the best World Cup goal in history in a FIFA online poll.',
      'Maradona had 10 assists in the tournament, an extraordinary tally for the era.',
      'First World Cup to use penalty shootouts to decide knockout matches.',
      'Mexico hosted on very short notice after Colombia withdrew — and was devastated by an earthquake in 1985.',
    ],
  },
  {
    year: 1990,
    host: 'Italy',
    hostFlag: '🇮🇹',
    champion: 'West Germany',
    championFlag: '🇩🇪',
    runnerUp: 'Argentina',
    runnerUpFlag: '🇦🇷',
    finalScore: '1–0',
    topScorer: 'Salvatore Schillaci',
    topScorerGoals: 6,
    topScorerCountry: '🇮🇹',
    goldenBall: 'Salvatore Schillaci',
    goldenGlove: 'Sergio Goycochea',
    mascot: 'Ciao',
    ball: 'Adidas Etrusco Unico',
    teams: 24,
    matches: 52,
    goals: 115,
    attendance: '2,516,215',
    funFacts: [
      'The lowest-scoring and most defensive World Cup ever — only 115 goals in 52 games.',
      'Cameroon\'s Roger Milla (38 years old) became a global icon with his corner-flag celebrations.',
      'The tournament featured a record 16 red cards.',
      '"Nessun Dorma" by Pavarotti became the iconic anthem of the tournament.',
      'Republic of Ireland reached the quarter-finals in their first-ever World Cup.',
    ],
  },
  {
    year: 1994,
    host: 'USA',
    hostFlag: '🇺🇸',
    champion: 'Brazil',
    championFlag: '🇧🇷',
    runnerUp: 'Italy',
    runnerUpFlag: '🇮🇹',
    finalScore: '0–0 (aet), 3–2 pens',
    topScorer: 'Oleg Salenko / Hristo Stoichkov',
    topScorerGoals: 6,
    topScorerCountry: '🇷🇺/🇧🇬',
    goldenBall: 'Romário',
    goldenGlove: 'Michel Preud\'homme',
    mascot: 'Striker',
    ball: 'Adidas Questra',
    teams: 24,
    matches: 52,
    goals: 141,
    attendance: '3,587,538',
    funFacts: [
      'First World Cup held in the United States — set an all-time attendance record of 3.58 million.',
      'First ever World Cup final decided by a penalty shootout — Roberto Baggio missed the decisive kick.',
      'Oleg Salenko scored 5 goals in a single game vs Cameroon — a World Cup record.',
      'Colombia\'s Andrés Escobar was shot dead after returning home, following his own goal vs USA.',
      'Brazil won their fourth title after a 24-year wait.',
    ],
  },
  {
    year: 1998,
    host: 'France',
    hostFlag: '🇫🇷',
    champion: 'France',
    championFlag: '🇫🇷',
    runnerUp: 'Brazil',
    runnerUpFlag: '🇧🇷',
    finalScore: '3–0',
    topScorer: 'Davor Šuker',
    topScorerGoals: 6,
    topScorerCountry: '🇭🇷',
    goldenBall: 'Ronaldo',
    goldenGlove: 'Fabien Barthez',
    mascot: 'Footix',
    ball: 'Adidas Tricolore',
    teams: 32,
    matches: 64,
    goals: 171,
    attendance: '2,785,100',
    funFacts: [
      'Expanded to 32 teams — the format used through 2022.',
      'France won their first World Cup on home soil; Zidane scored twice with headers in the final.',
      'Ronaldo\'s mysterious pre-match illness remains a football mystery — he started but was ineffective.',
      'Croatia finished 3rd in their first World Cup appearance.',
      'The Stade de France in Saint-Denis was built specifically for this tournament.',
    ],
  },
  {
    year: 2002,
    host: 'Japan & South Korea',
    hostFlag: '🇯🇵🇰🇷',
    champion: 'Brazil',
    championFlag: '🇧🇷',
    runnerUp: 'Germany',
    runnerUpFlag: '🇩🇪',
    finalScore: '2–0',
    topScorer: 'Ronaldo',
    topScorerGoals: 8,
    topScorerCountry: '🇧🇷',
    goldenBall: 'Oliver Kahn',
    goldenGlove: 'Oliver Kahn',
    mascot: 'Ato, Kaz, and Nik',
    ball: 'Adidas Fevernova',
    teams: 32,
    matches: 64,
    goals: 161,
    attendance: '2,705,197',
    funFacts: [
      'First World Cup held in Asia — and the only co-hosted tournament.',
      'Ronaldo scored 8 goals including both in the final, redeeming himself from 1998.',
      'South Korea reached the semi-finals in a run full of controversial refereeing decisions.',
      'Defending champion France failed to score a single goal and was eliminated in the group stage.',
      'Senegal, in their first World Cup, beat France and reached the quarter-finals.',
    ],
  },
  {
    year: 2006,
    host: 'Germany',
    hostFlag: '🇩🇪',
    champion: 'Italy',
    championFlag: '🇮🇹',
    runnerUp: 'France',
    runnerUpFlag: '🇫🇷',
    finalScore: '1–1 (aet), 5–3 pens',
    topScorer: 'Miroslav Klose',
    topScorerGoals: 5,
    topScorerCountry: '🇩🇪',
    goldenBall: 'Zinedine Zidane',
    goldenGlove: 'Gianluigi Buffon',
    mascot: 'Goleo VI',
    ball: 'Adidas Teamgeist',
    teams: 32,
    matches: 64,
    goals: 147,
    attendance: '3,359,439',
    funFacts: [
      'Zidane won the Golden Ball in his last professional match — after being sent off for a headbutt on Materazzi.',
      'Italy won their fourth World Cup title.',
      '"The Summer Fairy Tale" — Germany\'s hosting was celebrated for its carnival atmosphere.',
      'Australia returned to the World Cup after a 32-year absence.',
      'Germany vs Italy semi-final (2–0 in extra time) was one of the tournament\'s finest matches.',
    ],
  },
  {
    year: 2010,
    host: 'South Africa',
    hostFlag: '🇿🇦',
    champion: 'Spain',
    championFlag: '🇪🇸',
    runnerUp: 'Netherlands',
    runnerUpFlag: '🇳🇱',
    finalScore: '1–0 (aet)',
    topScorer: 'Thomas Müller / David Villa / Wesley Sneijder / Diego Forlán',
    topScorerGoals: 5,
    topScorerCountry: '🌍',
    goldenBall: 'Diego Forlán',
    goldenGlove: 'Iker Casillas',
    mascot: 'Zakumi',
    ball: 'Adidas Jabulani',
    teams: 32,
    matches: 64,
    goals: 145,
    attendance: '3,178,856',
    funFacts: [
      'First World Cup held in Africa — South Africa built 5 new stadiums.',
      'Spain won their first World Cup, completing a unique treble (Euro 2008, WC 2010, Euro 2012).',
      'The vuvuzela became the sound of the tournament — and of controversy.',
      'The Jabulani ball was criticized by goalkeepers for its unpredictable movement.',
      'Octopus Paul correctly predicted all of Germany\'s results and the final winner.',
    ],
  },
  {
    year: 2014,
    host: 'Brazil',
    hostFlag: '🇧🇷',
    champion: 'Germany',
    championFlag: '🇩🇪',
    runnerUp: 'Argentina',
    runnerUpFlag: '🇦🇷',
    finalScore: '1–0 (aet)',
    topScorer: 'James Rodríguez',
    topScorerGoals: 6,
    topScorerCountry: '🇨🇴',
    goldenBall: 'Lionel Messi',
    goldenGlove: 'Manuel Neuer',
    mascot: 'Fuleco',
    ball: 'Adidas Brazuca',
    teams: 32,
    matches: 64,
    goals: 171,
    attendance: '3,429,873',
    funFacts: [
      '"The Mineirazo" — Brazil lost 7–1 to Germany in the semi-final; Germany scored 5 goals in 18 minutes.',
      'Miroslav Klose scored his 16th World Cup goal to become the all-time top scorer.',
      'Mario Götze scored the winning extra-time goal as a substitute — Germany\'s 4th title.',
      'James Rodríguez\'s volley vs Uruguay was voted Goal of the Tournament.',
      'VAR was not yet in use — several controversial decisions sparked major debate.',
    ],
  },
  {
    year: 2018,
    host: 'Russia',
    hostFlag: '🇷🇺',
    champion: 'France',
    championFlag: '🇫🇷',
    runnerUp: 'Croatia',
    runnerUpFlag: '🇭🇷',
    finalScore: '4–2',
    topScorer: 'Harry Kane',
    topScorerGoals: 6,
    topScorerCountry: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    goldenBall: 'Luka Modrić',
    goldenGlove: 'Thibaut Courtois',
    mascot: 'Zabivaka',
    ball: 'Adidas Telstar 18',
    teams: 32,
    matches: 64,
    goals: 169,
    attendance: '3,031,768',
    funFacts: [
      'VAR (Video Assistant Referee) was used for the first time — a record 29 penalties were awarded.',
      'Croatia beat Russia, Denmark, and hosts in penalty shootouts to reach the final.',
      'Kylian Mbappé (19) became the second teenager ever, after Pelé, to score in a World Cup final.',
      'Luka Modrić won the Golden Ball; only the second player after Ronaldo (2002) to win it from a non-top-4 team.',
      'Germany, the defending champions, were eliminated in the group stage.',
    ],
  },
  {
    year: 2022,
    host: 'Qatar',
    hostFlag: '🇶🇦',
    champion: 'Argentina',
    championFlag: '🇦🇷',
    runnerUp: 'France',
    runnerUpFlag: '🇫🇷',
    finalScore: '3–3 (aet), 4–2 pens',
    topScorer: 'Kylian Mbappé',
    topScorerGoals: 8,
    topScorerCountry: '🇫🇷',
    goldenBall: 'Lionel Messi',
    goldenGlove: 'Emiliano Martínez',
    mascot: 'La\'eeb',
    ball: 'Adidas Al Rihla',
    teams: 32,
    matches: 64,
    goals: 172,
    attendance: '3,404,252',
    funFacts: [
      'The greatest World Cup final ever — Mbappé scored a hat-trick but Argentina won on penalties.',
      'Lionel Messi finally won the World Cup, cementing his legacy in the GOAT debate.',
      'Morocco became the first African team to reach the semi-finals.',
      'The first World Cup held in the Middle East — and in winter (November–December).',
      'All 8 stadiums were within 55 km of each other, making it the most compact World Cup ever.',
    ],
  },
];
