export interface WCEdition {
  year: number;
  host: string;
  hostFlag: string;
  champion: string;
  championFlag: string;
  runnerUp: string;
  runnerUpFlag: string;
  finalScore: string;
  topScorer: string;
  topScorerGoals: number;
  topScorerCountry: string;
  teams: number;
  matches: number;
  goals: number;
  attendance: string;
  goldenBall?: string;
  goldenGlove?: string;
  mascot?: string;
  ball?: string;
  funFacts: string[];
  funFactsEs: string[];
}

export const WC_EDITIONS: WCEdition[] = [
  {
    year: 1930,
    host: 'Uruguay',
    hostFlag: '🇺🇾',
    champion: 'Uruguay',
    championFlag: '🇺🇾',
    runnerUp: 'Argentina',
    runnerUpFlag: '🇦🇷',
    finalScore: '4–2',
    topScorer: 'Guillermo Stábile',
    topScorerGoals: 8,
    topScorerCountry: '🇦🇷',
    teams: 13,
    matches: 18,
    goals: 70,
    attendance: '590,549',
    funFacts: [
      'The first World Cup — 13 nations competed, all invited by FIFA.',
      'European teams had to travel by ship for two weeks to reach Uruguay.',
      'The final was played at the brand-new Estadio Centenario in Montevideo.',
      'Uruguay and Argentina used different balls in each half — both claimed victory in their half.',
      'The Jules Rimet trophy was awarded for the first time.',
    ],
    funFactsEs: [
      'El primer Mundial — 13 naciones compitieron, todas invitadas por la FIFA.',
      'Los equipos europeos tuvieron que viajar dos semanas en barco para llegar a Uruguay.',
      'La final se disputó en el recién construido Estadio Centenario de Montevideo.',
      'Uruguay y Argentina usaron balones distintos en cada parte — ambos reclamaron la victoria con su balón.',
      'El Trofeo Jules Rimet fue entregado por primera vez.',
    ],
  },
  {
    year: 1934,
    host: 'Italy',
    hostFlag: '🇮🇹',
    champion: 'Italy',
    championFlag: '🇮🇹',
    runnerUp: 'Czechoslovakia',
    runnerUpFlag: '🇨🇿',
    finalScore: '2–1 (aet)',
    topScorer: 'Oldřich Nejedly',
    topScorerGoals: 5,
    topScorerCountry: '🇨🇿',
    teams: 16,
    matches: 17,
    goals: 70,
    attendance: '363,000',
    funFacts: [
      'First tournament to use a knock-out format from the start.',
      'Uruguay, the defending champions, boycotted in retaliation for Europe\'s absence in 1930.',
      'Vittorio Pozzo became the only manager to win two World Cups (1934 and 1938).',
      'Italy\'s win under Mussolini raised political controversy about pressure on referees.',
      'Brazil and Argentina were both eliminated in their opening matches.',
    ],
    funFactsEs: [
      'El primer torneo con formato de eliminación directa desde el inicio.',
      'Uruguay, el campeón defensor, boicoteó en represalia por la ausencia europea en 1930.',
      'Vittorio Pozzo se convirtió en el único seleccionador en ganar dos Mundiales (1934 y 1938).',
      'La victoria italiana bajo Mussolini generó controversia sobre la presión a los árbitros.',
      'Brasil y Argentina fueron eliminados en sus partidos de apertura.',
    ],
  },
  {
    year: 1938,
    host: 'France',
    hostFlag: '🇫🇷',
    champion: 'Italy',
    championFlag: '🇮🇹',
    runnerUp: 'Hungary',
    runnerUpFlag: '🇭🇺',
    finalScore: '4–2',
    topScorer: 'Leônidas',
    topScorerGoals: 7,
    topScorerCountry: '🇧🇷',
    teams: 15,
    matches: 18,
    goals: 84,
    attendance: '374,835',
    funFacts: [
      'Italy became back-to-back World Cup champions.',
      'Brazil\'s Leônidas was nicknamed "The Black Diamond" and scored 7 goals.',
      'Austria qualified but was absorbed into Germany before the tournament — their players joined the German squad.',
      'Spain was in the middle of its Civil War and couldn\'t participate.',
      'The next World Cup would not be held for 12 years due to World War II.',
    ],
    funFactsEs: [
      'Italia se convirtió en bicampeón del mundo.',
      'Leônidas de Brasil, apodado \'El Diamante Negro\', marcó 7 goles.',
      'Austria se clasificó pero fue absorbida por Alemania antes del torneo; sus jugadores se unieron a la selección alemana.',
      'España estaba en plena Guerra Civil y no pudo participar.',
      'El siguiente Mundial no se celebraría hasta 12 años después, a causa de la Segunda Guerra Mundial.',
    ],
  },
  {
    year: 1950,
    host: 'Brazil',
    hostFlag: '🇧🇷',
    champion: 'Uruguay',
    championFlag: '🇺🇾',
    runnerUp: 'Brazil',
    runnerUpFlag: '🇧🇷',
    finalScore: '2–1 (final group stage)',
    topScorer: 'Ademir',
    topScorerGoals: 9,
    topScorerCountry: '🇧🇷',
    teams: 13,
    matches: 22,
    goals: 88,
    attendance: '1,045,246',
    funFacts: [
      '"The Maracanazo" — Uruguay\'s 2–1 win over Brazil in front of ~200,000 fans at Maracanã remains one of sport\'s greatest upsets.',
      'The final was a round-robin "final pool," not a single knockout match.',
      'Scotland, India, and Turkey all withdrew before the tournament.',
      'England participated in the World Cup for the very first time — and lost to the USA 1–0.',
      'The shock Uruguay victory caused massive grief across Brazil; some fans reportedly died of heart attacks.',
    ],
    funFactsEs: [
      '\'El Maracanazo\' — la victoria de Uruguay 2–1 sobre Brasil ante ~200.000 aficionados en el Maracaná sigue siendo uno de los mayores golpes del deporte.',
      'La final fue una \'liguilla final\', no un partido único de eliminación directa.',
      'Escocia, India y Turquía se retiraron antes del torneo.',
      'Inglaterra participó en el Mundial por primera vez — y perdió ante EE. UU. 1–0.',
      'La impactante victoria de Uruguay provocó una oleada de duelo en Brasil; se dice que algunos aficionados murieron de ataques al corazón.',
    ],
  },
  {
    year: 1954,
    host: 'Switzerland',
    hostFlag: '🇨🇭',
    champion: 'West Germany',
    championFlag: '🇩🇪',
    runnerUp: 'Hungary',
    runnerUpFlag: '🇭🇺',
    finalScore: '3–2',
    topScorer: 'Sándor Kocsis',
    topScorerGoals: 11,
    topScorerCountry: '🇭🇺',
    teams: 16,
    matches: 26,
    goals: 140,
    attendance: '768,607',
    funFacts: [
      '"The Miracle of Bern" — West Germany defeated the unbeaten "Magnificent Magyars" of Hungary in the final.',
      'Hungary had beaten West Germany 8–3 in the group stage just weeks before.',
      'The tournament averaged 5.38 goals per game — the highest ever in World Cup history.',
      'Uruguay\'s match vs Hungary produced 4 red cards and a brawl; dubbed "The Battle of Bern."',
      'First World Cup to be televised.',
    ],
    funFactsEs: [
      '\'El Milagro de Berna\' — Alemania Occidental venció en la final a los imbatibles \'Húngaros Magníficos\'.',
      'Hungría había derrotado a Alemania Occidental 8–3 en la fase de grupos pocas semanas antes.',
      'El torneo promedió 5,38 goles por partido, el mayor promedio en la historia del Mundial.',
      'El partido Uruguay–Hungría tuvo 4 expulsiones y una pelea campal; apodado \'La Batalla de Berna\'.',
      'Primer Mundial televisado.',
    ],
  },
  {
    year: 1958,
    host: 'Sweden',
    hostFlag: '🇸🇪',
    champion: 'Brazil',
    championFlag: '🇧🇷',
    runnerUp: 'Sweden',
    runnerUpFlag: '🇸🇪',
    finalScore: '5–2',
    topScorer: 'Just Fontaine',
    topScorerGoals: 13,
    topScorerCountry: '🇫🇷',
    funFacts: [
      'A 17-year-old Pelé became a sensation, scoring 6 goals including a hat-trick in the semi-final.',
      'Just Fontaine\'s 13 goals in one tournament is a record that still stands today.',
      'Vavá scored twice in the final to help Brazil win their first World Cup title.',
      'France finished 3rd — their best result until 1998.',
      'Brazil introduced the 4-2-4 formation that revolutionized football tactics.',
    ],
    funFactsEs: [
      'Un Pelé de 17 años se convirtió en sensación mundial, marcando 6 goles incluyendo un hat-trick en semifinales.',
      'Los 13 goles de Just Fontaine en un solo torneo son un récord que hoy aún se mantiene.',
      'Vavá marcó dos veces en la final para ayudar a Brasil a conquistar su primer título.',
      'Francia terminó tercera — su mejor resultado hasta 1998.',
      'Brasil introdujo el sistema 4-2-4 que revolucionó la táctica del fútbol.',
    ],
    teams: 16,
    matches: 35,
    goals: 126,
    attendance: '819,810',
  },
  {
    year: 1962,
    host: 'Chile',
    hostFlag: '🇨🇱',
    champion: 'Brazil',
    championFlag: '🇧🇷',
    runnerUp: 'Czechoslovakia',
    runnerUpFlag: '🇨🇿',
    finalScore: '3–1',
    topScorer: 'Garrincha / Vavá / Leonel Sánchez / Dražan Jerković',
    topScorerGoals: 4,
    topScorerCountry: '🌍',
    teams: 16,
    matches: 32,
    goals: 89,
    attendance: '893,172',
    funFacts: [
      'Brazil won back-to-back titles, becoming the first team to do so since Italy in 1934–38.',
      'Pelé was injured in the second group game and missed the rest of the tournament.',
      'Garrincha, "The Little Bird," was the tournament\'s outstanding player despite his bowed legs.',
      '"The Battle of Santiago" (Italy vs Chile) was so violent the BBC commentator called it "the most disgraceful exhibition of football."',
      'A magnitude 9.5 earthquake hit Chile the year before; hosting the tournament was a major achievement.',
    ],
    funFactsEs: [
      'Brasil ganó títulos consecutivos, siendo el primer equipo en lograrlo desde Italia en 1934–38.',
      'Pelé se lesionó en el segundo partido de la fase de grupos y se perdió el resto del torneo.',
      'Garrincha, \'El Pájaro\', fue el jugador más destacado pese a sus piernas arqueadas.',
      '\'La Batalla de Santiago\' (Italia vs Chile) fue tan violenta que el comentarista de la BBC la llamó \'la exposición más vergonzosa del fútbol\'.',
      'Un terremoto de magnitud 9,5 asoló Chile el año anterior; organizar el torneo fue un enorme logro.',
    ],
  },
  {
    year: 1966,
    host: 'England',
    hostFlag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    champion: 'England',
    championFlag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    runnerUp: 'West Germany',
    runnerUpFlag: '🇩🇪',
    finalScore: '4–2 (aet)',
    topScorer: 'Eusébio',
    topScorerGoals: 9,
    topScorerCountry: '🇵🇹',
    mascot: 'World Cup Willie',
    teams: 16,
    matches: 32,
    goals: 89,
    attendance: '1,563,135',
    funFacts: [
      'England\'s only World Cup title — Geoff Hurst scored a hat-trick in the final.',
      'The famous "Wembley goal" — Hurst\'s third still divides opinion on whether it crossed the line.',
      'World Cup Willie became the first official World Cup mascot.',
      'North Korea knocked out Italy in the group stage — one of the biggest upsets ever.',
      'The Jules Rimet trophy was stolen and then found by a dog named Pickles.',
    ],
    funFactsEs: [
      'El único título mundial de Inglaterra — Geoff Hurst marcó un hat-trick en la final.',
      'El famoso \'gol de Wembley\' — el tercer gol de Hurst sigue generando debate sobre si cruzó la línea.',
      'World Cup Willie se convirtió en la primera mascota oficial del Mundial.',
      'Corea del Norte eliminó a Italia en la fase de grupos, una de las mayores sorpresas de la historia.',
      'El Trofeo Jules Rimet fue robado y luego encontrado por un perro llamado Pickles.',
    ],
  },
  {
    year: 1970,
    host: 'Mexico',
    hostFlag: '🇲🇽',
    champion: 'Brazil',
    championFlag: '🇧🇷',
    runnerUp: 'Italy',
    runnerUpFlag: '🇮🇹',
    finalScore: '4–1',
    topScorer: 'Gerd Müller',
    topScorerGoals: 10,
    topScorerCountry: '🇩🇪',
    goldenBall: 'Pelé',
    mascot: 'Juanito',
    ball: 'Adidas Telstar',
    teams: 16,
    matches: 32,
    goals: 95,
    attendance: '1,603,975',
    funFacts: [
      'Brazil won their third title and kept the Jules Rimet trophy permanently.',
      'Widely considered the greatest World Cup ever — Pelé, Rivelino, Jairzinho, Tostão all in one squad.',
      'First World Cup shown in colour TV worldwide.',
      'The "Game of the Century" — Italy beat West Germany 4–3 in extra time in the semi-final.',
      'Jairzinho scored in every single game of the tournament — a unique feat.',
    ],
    funFactsEs: [
      'Brasil ganó su tercer título y se quedó definitivamente con el Trofeo Jules Rimet.',
      'Considerado ampliamente el mejor Mundial de la historia — Pelé, Rivelino, Jairzinho y Tostão en un mismo equipo.',
      'Primer Mundial retransmitido en color por todo el mundo.',
      '\'El Partido del Siglo\' — Italia venció a Alemania Occidental 4–3 en la prórroga de la semifinal.',
      'Jairzinho marcó en todos y cada uno de los partidos del torneo, un hito irrepetible.',
    ],
  },
  {
    year: 1974,
    host: 'West Germany',
    hostFlag: '🇩🇪',
    champion: 'West Germany',
    championFlag: '🇩🇪',
    runnerUp: 'Netherlands',
    runnerUpFlag: '🇳🇱',
    finalScore: '2–1',
    topScorer: 'Grzegorz Lato',
    topScorerGoals: 7,
    topScorerCountry: '🇵🇱',
    goldenBall: 'Johan Cruyff',
    mascot: 'Tip and Tap',
    ball: 'Adidas Telstar Durlast',
    teams: 16,
    matches: 38,
    goals: 97,
    attendance: '1,865,762',
    funFacts: [
      'Johan Cruyff\'s Netherlands introduced "Total Football" to the world.',
      'Netherlands reached the final without Cruyff in 1978 — he refused to go citing a kidnapping attempt.',
      'The current FIFA World Cup trophy was introduced for the first time.',
      'Pelé was absent — his Brazil squad was controversially eliminated in the second group stage.',
      'East Germany beat West Germany 1–0 in the group stage — the only time the two German states ever met.',
    ],
    funFactsEs: [
      'Johan Cruyff y los Países Bajos presentaron el \'Fútbol Total\' al mundo.',
      'Los Países Bajos llegaron a la final de 1978 sin Cruyff, quien se negó a ir alegando un intento de secuestro.',
      'El actual trofeo de la Copa del Mundo FIFA se entregó por primera vez.',
      'La ausencia de Pelé fue notable — su Brasil fue eliminado polémicamente en la segunda fase de grupos.',
      'Alemania del Este venció a Alemania Occidental 1–0 en la fase de grupos: el único enfrentamiento entre los dos estados alemanes.',
    ],
  },
  {
    year: 1978,
    host: 'Argentina',
    hostFlag: '🇦🇷',
    champion: 'Argentina',
    championFlag: '🇦🇷',
    runnerUp: 'Netherlands',
    runnerUpFlag: '🇳🇱',
    finalScore: '3–1 (aet)',
    topScorer: 'Mario Kempes',
    topScorerGoals: 6,
    topScorerCountry: '🇦🇷',
    goldenBall: 'Mario Kempes',
    mascot: 'Gauchito',
    ball: 'Adidas Tango',
    teams: 16,
    matches: 38,
    goals: 102,
    attendance: '1,545,791',
    funFacts: [
      'Argentina\'s first World Cup title, under military dictatorship — controversy surrounded the tournament.',
      'Mario Kempes, the tournament\'s top scorer, scored twice in the final.',
      'The ticker-tape paper storm at River Plate for Argentina\'s matches became iconic.',
      'Scotland\'s Archie Gemmill scored one of the greatest World Cup goals ever against the Netherlands.',
      'The tournament was held amid protests against Argentina\'s military junta government.',
    ],
    funFactsEs: [
      'El primer título mundial de Argentina, bajo dictadura militar — el torneo estuvo envuelto en polémica.',
      'Mario Kempes, máximo goleador del torneo, anotó dos goles en la final.',
      'La lluvia de papelitos en el estadio River Plate durante los partidos de Argentina se convirtió en imagen icónica.',
      'Archie Gemmill de Escocia marcó uno de los mejores goles de la historia del Mundial contra los Países Bajos.',
      'El torneo se celebró en medio de protestas contra la junta militar argentina.',
    ],
  },
  {
    year: 1982,
    host: 'Spain',
    hostFlag: '🇪🇸',
    champion: 'Italy',
    championFlag: '🇮🇹',
    runnerUp: 'West Germany',
    runnerUpFlag: '🇩🇪',
    finalScore: '3–1',
    topScorer: 'Paolo Rossi',
    topScorerGoals: 6,
    topScorerCountry: '🇮🇹',
    goldenBall: 'Paolo Rossi',
    mascot: 'Naranjito',
    ball: 'Adidas Tango Español',
    teams: 24,
    matches: 52,
    goals: 146,
    attendance: '2,109,723',
    funFacts: [
      'Expanded to 24 teams for the first time.',
      'Paolo Rossi had returned from a 2-year ban for match-fixing and became the hero, scoring 6 goals in the final stages.',
      'Hungary beat El Salvador 10–1, the biggest winning margin in World Cup history.',
      '"Night of Shame" — West Germany and Austria played a 1–0 result that sent both through, with both teams happy with the score.',
      'Brazil\'s incredible attacking team (Zico, Sócrates, Falcão) was sensationally eliminated by Italy.',
    ],
    funFactsEs: [
      'Se amplió a 24 equipos por primera vez.',
      'Paolo Rossi había regresado de una sanción de 2 años por amaño de partidos y se convirtió en el héroe marcando 6 goles en la fase final.',
      'Hungría venció a El Salvador 10–1, el mayor margen de victoria en la historia del Mundial.',
      '\'La Noche de la Vergüenza\' — Alemania Occidental y Austria jugaron un 1–0 con el que ambas avanzaban, sin ninguno intentar remontar.',
      'El increíble Brasil atacante (Zico, Sócrates, Falcão) fue sensacionalmente eliminado por Italia.',
    ],
  },
  {
    year: 1986,
    host: 'Mexico',
    hostFlag: '🇲🇽',
    champion: 'Argentina',
    championFlag: '🇦🇷',
    runnerUp: 'West Germany',
    runnerUpFlag: '🇩🇪',
    finalScore: '3–2',
    topScorer: 'Gary Lineker',
    topScorerGoals: 6,
    topScorerCountry: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    goldenBall: 'Diego Maradona',
    mascot: 'Pique',
    ball: 'Adidas Azteca',
    teams: 24,
    matches: 52,
    goals: 132,
    attendance: '2,394,031',
    funFacts: [
      'Diego Maradona\'s tournament — the "Hand of God" goal and the "Goal of the Century" came in the same match vs England.',
      'The Goal of the Century was voted the best World Cup goal in history in a FIFA online poll.',
      'Maradona had 10 assists in the tournament, an extraordinary tally for the era.',
      'First World Cup to use penalty shootouts to decide knockout matches.',
      'Mexico hosted on very short notice after Colombia withdrew — and was devastated by an earthquake in 1985.',
    ],
    funFactsEs: [
      'El torneo de Maradona — el gol con \'La Mano de Dios\' y el \'Gol del Siglo\' llegaron en el mismo partido ante Inglaterra.',
      'El Gol del Siglo fue elegido el mejor gol de la historia del Mundial en una encuesta online de la FIFA.',
      'Maradona acumuló 10 asistencias en el torneo, una cifra extraordinaria para la época.',
      'Primer Mundial en resolver los partidos de eliminatoria mediante tanda de penaltis.',
      'México acogió el torneo con muy poco margen tras la retirada de Colombia — y pese a un devastador terremoto en 1985.',
    ],
  },
  {
    year: 1990,
    host: 'Italy',
    hostFlag: '🇮🇹',
    champion: 'West Germany',
    championFlag: '🇩🇪',
    runnerUp: 'Argentina',
    runnerUpFlag: '🇦🇷',
    finalScore: '1–0',
    topScorer: 'Salvatore Schillaci',
    topScorerGoals: 6,
    topScorerCountry: '🇮🇹',
    goldenBall: 'Salvatore Schillaci',
    goldenGlove: 'Sergio Goycochea',
    mascot: 'Ciao',
    ball: 'Adidas Etrusco Unico',
    teams: 24,
    matches: 52,
    goals: 115,
    attendance: '2,516,215',
    funFacts: [
      'The lowest-scoring and most defensive World Cup ever — only 115 goals in 52 games.',
      'Cameroon\'s Roger Milla (38 years old) became a global icon with his corner-flag celebrations.',
      'The tournament featured a record 16 red cards.',
      '"Nessun Dorma" by Pavarotti became the iconic anthem of the tournament.',
      'Republic of Ireland reached the quarter-finals in their first-ever World Cup.',
    ],
    funFactsEs: [
      'El Mundial más defensivo y con menos goles — solo 115 en 52 partidos.',
      'El camerunés Roger Milla (38 años) se hizo leyenda mundial con sus celebraciones en el banderín de córner.',
      'El torneo batió el récord con 16 tarjetas rojas.',
      '\'Nessun Dorma\' de Pavarotti se convirtió en el himno icónico del torneo.',
      'La República de Irlanda llegó a los cuartos de final en su primera Copa del Mundo.',
    ],
  },
  {
    year: 1994,
    host: 'USA',
    hostFlag: '🇺🇸',
    champion: 'Brazil',
    championFlag: '🇧🇷',
    runnerUp: 'Italy',
    runnerUpFlag: '🇮🇹',
    finalScore: '0–0 (aet), 3–2 pens',
    topScorer: 'Oleg Salenko / Hristo Stoichkov',
    topScorerGoals: 6,
    topScorerCountry: '🇷🇺/🇧🇬',
    goldenBall: 'Romário',
    goldenGlove: 'Michel Preud\'homme',
    mascot: 'Striker',
    ball: 'Adidas Questra',
    teams: 24,
    matches: 52,
    goals: 141,
    attendance: '3,587,538',
    funFacts: [
      'First World Cup held in the United States — set an all-time attendance record of 3.58 million.',
      'First ever World Cup final decided by a penalty shootout — Roberto Baggio missed the decisive kick.',
      'Oleg Salenko scored 5 goals in a single game vs Cameroon — a World Cup record.',
      'Colombia\'s Andrés Escobar was shot dead after returning home, following his own goal vs USA.',
      'Brazil won their fourth title after a 24-year wait.',
    ],
    funFactsEs: [
      'Primer Mundial celebrado en Estados Unidos — batió el récord histórico de asistencia con 3,58 millones.',
      'Primera final del Mundial resuelta mediante tanda de penaltis — Roberto Baggio falló el penalti decisivo.',
      'Oleg Salenko marcó 5 goles en un solo partido ante Camerún, récord del Mundial.',
      'El colombiano Andrés Escobar fue asesinado a tiros al volver a su país, tras su gol en propia puerta ante EE. UU.',
      'Brasil conquistó su cuarto título tras 24 años de espera.',
    ],
  },
  {
    year: 1998,
    host: 'France',
    hostFlag: '🇫🇷',
    champion: 'France',
    championFlag: '🇫🇷',
    runnerUp: 'Brazil',
    runnerUpFlag: '🇧🇷',
    finalScore: '3–0',
    topScorer: 'Davor Šuker',
    topScorerGoals: 6,
    topScorerCountry: '🇭🇷',
    goldenBall: 'Ronaldo',
    goldenGlove: 'Fabien Barthez',
    mascot: 'Footix',
    ball: 'Adidas Tricolore',
    teams: 32,
    matches: 64,
    goals: 171,
    attendance: '2,785,100',
    funFacts: [
      'Expanded to 32 teams — the format used through 2022.',
      'France won their first World Cup on home soil; Zidane scored twice with headers in the final.',
      'Ronaldo\'s mysterious pre-match illness remains a football mystery — he started but was ineffective.',
      'Croatia finished 3rd in their first World Cup appearance.',
      'The Stade de France in Saint-Denis was built specifically for this tournament.',
    ],
    funFactsEs: [
      'Se amplió a 32 equipos — el formato utilizado hasta 2022.',
      'Francia ganó su primer Mundial en casa; Zidane marcó dos goles de cabeza en la final.',
      'La misteriosa enfermedad de Ronaldo antes del partido sigue siendo un enigma del fútbol — salió al campo pero fue muy discreto.',
      'Croacia terminó tercera en su primera participación en el Mundial.',
      'El Stade de France en Saint-Denis se construyó expresamente para este torneo.',
    ],
  },
  {
    year: 2002,
    host: 'Japan & South Korea',
    hostFlag: '🇯🇵🇰🇷',
    champion: 'Brazil',
    championFlag: '🇧🇷',
    runnerUp: 'Germany',
    runnerUpFlag: '🇩🇪',
    finalScore: '2–0',
    topScorer: 'Ronaldo',
    topScorerGoals: 8,
    topScorerCountry: '🇧🇷',
    goldenBall: 'Oliver Kahn',
    goldenGlove: 'Oliver Kahn',
    mascot: 'Ato, Kaz, and Nik',
    ball: 'Adidas Fevernova',
    teams: 32,
    matches: 64,
    goals: 161,
    attendance: '2,705,197',
    funFacts: [
      'First World Cup held in Asia — and the only co-hosted tournament.',
      'Ronaldo scored 8 goals including both in the final, redeeming himself from 1998.',
      'South Korea reached the semi-finals in a run full of controversial refereeing decisions.',
      'Defending champion France failed to score a single goal and was eliminated in the group stage.',
      'Senegal, in their first World Cup, beat France and reached the quarter-finals.',
    ],
    funFactsEs: [
      'Primer Mundial celebrado en Asia — y el único torneo coanfitrionado.',
      'Ronaldo marcó 8 goles, incluyendo los dos de la final, para redimirse del Mundial de 1998.',
      'Corea del Sur llegó a las semifinales en una carrera marcada por polémicas decisiones arbitrales.',
      'La campeona defensora Francia no marcó un solo gol y fue eliminada en la fase de grupos.',
      'Senegal, en su primer Mundial, venció a Francia y llegó a los cuartos de final.',
    ],
  },
  {
    year: 2006,
    host: 'Germany',
    hostFlag: '🇩🇪',
    champion: 'Italy',
    championFlag: '🇮🇹',
    runnerUp: 'France',
    runnerUpFlag: '🇫🇷',
    finalScore: '1–1 (aet), 5–3 pens',
    topScorer: 'Miroslav Klose',
    topScorerGoals: 5,
    topScorerCountry: '🇩🇪',
    goldenBall: 'Zinedine Zidane',
    goldenGlove: 'Gianluigi Buffon',
    mascot: 'Goleo VI',
    ball: 'Adidas Teamgeist',
    teams: 32,
    matches: 64,
    goals: 147,
    attendance: '3,359,439',
    funFacts: [
      'Zidane won the Golden Ball in his last professional match — after being sent off for a headbutt on Materazzi.',
      'Italy won their fourth World Cup title.',
      '"The Summer Fairy Tale" — Germany\'s hosting was celebrated for its carnival atmosphere.',
      'Australia returned to the World Cup after a 32-year absence.',
      'Germany vs Italy semi-final (2–0 in extra time) was one of the tournament\'s finest matches.',
    ],
    funFactsEs: [
      'Zidane ganó el Balón de Oro en su último partido profesional — tras ser expulsado por su cabezazo a Materazzi.',
      'Italia conquistó su cuarto título.',
      '\'El cuento de hadas del verano\' — Alemania disfrutó de un ambiente de fiesta como país anfitrión.',
      'Australia regresó al Mundial tras 32 años de ausencia.',
      'La semifinal Alemania–Italia (2–0 en la prórroga) fue uno de los mejores partidos del torneo.',
    ],
  },
  {
    year: 2010,
    host: 'South Africa',
    hostFlag: '🇿🇦',
    champion: 'Spain',
    championFlag: '🇪🇸',
    runnerUp: 'Netherlands',
    runnerUpFlag: '🇳🇱',
    finalScore: '1–0 (aet)',
    topScorer: 'Thomas Müller / David Villa / Wesley Sneijder / Diego Forlán',
    topScorerGoals: 5,
    topScorerCountry: '🌍',
    goldenBall: 'Diego Forlán',
    goldenGlove: 'Iker Casillas',
    mascot: 'Zakumi',
    ball: 'Adidas Jabulani',
    teams: 32,
    matches: 64,
    goals: 145,
    attendance: '3,178,856',
    funFacts: [
      'First World Cup held in Africa — South Africa built 5 new stadiums.',
      'Spain won their first World Cup, completing a unique treble (Euro 2008, WC 2010, Euro 2012).',
      'The vuvuzela became the sound of the tournament — and of controversy.',
      'The Jabulani ball was criticized by goalkeepers for its unpredictable movement.',
      'Octopus Paul correctly predicted all of Germany\'s results and the final winner.',
    ],
    funFactsEs: [
      'Primer Mundial celebrado en África — Sudáfrica construyó 5 nuevos estadios.',
      'España ganó su primer Mundial, completando un triplete único (Eurocopa 2008, Mundial 2010, Eurocopa 2012).',
      'La vuvuzela se convirtió en el sonido del torneo — y de la polémica.',
      'El balón Jabulani fue criticado por los porteros por su trayectoria imprevisible.',
      'El pulpo Paul acertó todos los resultados de Alemania y el ganador del torneo.',
    ],
  },
  {
    year: 2014,
    host: 'Brazil',
    hostFlag: '🇧🇷',
    champion: 'Germany',
    championFlag: '🇩🇪',
    runnerUp: 'Argentina',
    runnerUpFlag: '🇦🇷',
    finalScore: '1–0 (aet)',
    topScorer: 'James Rodríguez',
    topScorerGoals: 6,
    topScorerCountry: '🇨🇴',
    goldenBall: 'Lionel Messi',
    goldenGlove: 'Manuel Neuer',
    mascot: 'Fuleco',
    ball: 'Adidas Brazuca',
    teams: 32,
    matches: 64,
    goals: 171,
    attendance: '3,429,873',
    funFacts: [
      '"The Mineirazo" — Brazil lost 7–1 to Germany in the semi-final; Germany scored 5 goals in 18 minutes.',
      'Miroslav Klose scored his 16th World Cup goal to become the all-time top scorer.',
      'Mario Götze scored the winning extra-time goal as a substitute — Germany\'s 4th title.',
      'James Rodríguez\'s volley vs Uruguay was voted Goal of the Tournament.',
      'VAR was not yet in use — several controversial decisions sparked major debate.',
    ],
    funFactsEs: [
      '\'El Mineirazo\' — Brasil cayó 7–1 ante Alemania en la semifinal; los alemanes marcaron 5 goles en 18 minutos.',
      'Miroslav Klose marcó su 16.º gol mundialista para convertirse en el máximo goleador histórico.',
      'Mario Götze, entrando desde el banquillo, anotó el gol de la prórroga — Alemania conquistó su 4.º título.',
      'El voleo de James Rodríguez ante Uruguay fue elegido Gol del Torneo.',
      'El VAR aún no estaba en uso — varias decisiones polémicas generaron un intenso debate.',
    ],
  },
  {
    year: 2018,
    host: 'Russia',
    hostFlag: '🇷🇺',
    champion: 'France',
    championFlag: '🇫🇷',
    runnerUp: 'Croatia',
    runnerUpFlag: '🇭🇷',
    finalScore: '4–2',
    topScorer: 'Harry Kane',
    topScorerGoals: 6,
    topScorerCountry: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    goldenBall: 'Luka Modrić',
    goldenGlove: 'Thibaut Courtois',
    mascot: 'Zabivaka',
    ball: 'Adidas Telstar 18',
    teams: 32,
    matches: 64,
    goals: 169,
    attendance: '3,031,768',
    funFacts: [
      'VAR (Video Assistant Referee) was used for the first time — a record 29 penalties were awarded.',
      'Croatia beat Russia, Denmark, and hosts in penalty shootouts to reach the final.',
      'Kylian Mbappé (19) became the second teenager ever, after Pelé, to score in a World Cup final.',
      'Luka Modrić won the Golden Ball; only the second player after Ronaldo (2002) to win it from a non-top-4 team.',
      'Germany, the defending champions, were eliminated in the group stage.',
    ],
    funFactsEs: [
      'El VAR se usó por primera vez — se pitaron un récord de 29 penaltis.',
      'Croacia eliminó a Rusia, Dinamarca y al país anfitrión en tanda de penaltis para llegar a la final.',
      'Kylian Mbappé (19 años) se convirtió en el segundo adolescente, tras Pelé, en marcar en una final del Mundial.',
      'Luka Modrić ganó el Balón de Oro; solo el segundo jugador tras Ronaldo (2002) en lograrlo sin ser del Top 4.',
      'Alemania, la campeona defensora, fue eliminada en la fase de grupos.',
    ],
  },
  {
    year: 2022,
    host: 'Qatar',
    hostFlag: '🇶🇦',
    champion: 'Argentina',
    championFlag: '🇦🇷',
    runnerUp: 'France',
    runnerUpFlag: '🇫🇷',
    finalScore: '3–3 (aet), 4–2 pens',
    topScorer: 'Kylian Mbappé',
    topScorerGoals: 8,
    topScorerCountry: '🇫🇷',
    goldenBall: 'Lionel Messi',
    goldenGlove: 'Emiliano Martínez',
    mascot: 'La\'eeb',
    ball: 'Adidas Al Rihla',
    teams: 32,
    matches: 64,
    goals: 172,
    attendance: '3,404,252',
    funFacts: [
      'The greatest World Cup final ever — Mbappé scored a hat-trick but Argentina won on penalties.',
      'Lionel Messi finally won the World Cup, cementing his legacy in the GOAT debate.',
      'Morocco became the first African team to reach the semi-finals.',
      'The first World Cup held in the Middle East — and in winter (November–December).',
      'All 8 stadiums were within 55 km of each other, making it the most compact World Cup ever.',
    ],
    funFactsEs: [
      'La mejor final de la historia — Mbappé marcó un hat-trick, pero Argentina ganó en los penaltis.',
      'Lionel Messi finalmente ganó el Mundial, afianzando su legado en el debate del GOAT.',
      'Marruecos se convirtió en el primer equipo africano en llegar a las semifinales.',
      'El primer Mundial celebrado en Oriente Medio — y en invierno (noviembre–diciembre).',
      'Los 8 estadios estaban a menos de 55 km entre sí, convirtiéndolo en el Mundial más compacto de la historia.',
    ],
  },
];
